# Initial Setup

Library installation

Random seed initialization

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 35.8 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
!pip install -U transformers bitsandbytes

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.8.0-py3-none-any.whl.metadata (33 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.10.0+cu128)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes) (1.5.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.8.0-py3-none-any.whl (10.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 104.5 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 14.1 MB/s eta 0:00:00
Installing collected packages: bitsandbytes, transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed bitsandbytes-0.49.2 transformers-5.8.0

In [ ]:
import random

seed = 9514 #random.randint(1000, 9999)

# Data Import

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data_path = '/content/drive/My Drive/Apziva/Project 3 - Potential Talents/potential-talents.csv'

In [ ]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)

In [ ]:
import duckdb

In [ ]:
duckdb_conn = duckdb.connect(database=':memory:', read_only=False)

In [ ]:
data = duckdb_conn.sql(f"SELECT * FROM '{data_path}'")

# Data cleaning

In [ ]:
import nltk
import string

# Download the 'stopwords' corpus if not already downloaded
nltk.download('stopwords', quiet=True)

from nltk.corpus import stopwords

# Get the list of English stopwords
stop_words = set(stopwords.words('english'))

def clean_text(text):
    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Tokenize words and remove stopwords
    words = [word for word in text.split() if word not in stop_words]

    # Join the words back into a string
    return ' '.join(words)

In [ ]:
import duckdb # Keep the main duckdb import

try:
    # Register the Python function as a DuckDB UDF
    # Using 'str' as the return_type and for parameters instead of duckdb.typing.VARCHAR
    duckdb_conn.create_function("clean_text_udf", clean_text, return_type=str, parameters=[str])
except duckdb.NotImplementedException as e:
    if "A function by the name of 'clean_text_udf' is already created" in str(e):
        print("UDF 'clean_text_udf' already exists. Skipping creation.")
    else:
        raise # Re-raise other NotImplementedExceptions

# Apply the UDF to 'job_title' and 'location' columns and create a new DuckDB relation
data = duckdb_conn.sql("""
SELECT
    *, -- Select all existing columns
    clean_text_udf(job_title) AS cleaned_job_title,
    clean_text_udf(location) AS cleaned_location
FROM data
""")

print("Cleaning applied to 'job_title' and 'location' columns. The 'data' relation has been updated.")
print("New 'data' relation head with cleaned columns:")
data.show()

Cleaning applied to 'job_title' and 'location' columns. The 'data' relation has been updated.
New 'data' relation head with cleaned columns:
┌───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────┬────────────┬─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────┐
│  id   │                                                       job_title                                                       │              location               │ connection │   fit   │                                             cleaned_job_title                                             │         cleaned_location          │
│ int64 │                                                        varchar                                                        │               varchar               │  varchar   │ varchar │                                                  varchar                                                  │              varchar              │
├───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────┼────────────┼─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────┤
│     1 │ 2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional              │ Houston, Texas                      │ 85         │ NULL    │ 2019 ct bauer college business graduate magna cum laude aspiring human resources professional             │ houston texas                     │
│     2 │ Native English Teacher at EPIK (English Program in Korea)                                                             │ Kanada                              │ 500+       │ NULL    │ native english teacher epik english program korea                                                         │ kanada                            │
│     3 │ Aspiring Human Resources Professional                                                                                 │ Raleigh-Durham, North Carolina Area │ 44         │ NULL    │ aspiring human resources professional                                                                     │ raleighdurham north carolina area │
│     4 │ People Development Coordinator at Ryan                                                                                │ Denton, Texas                       │ 500+       │ NULL    │ people development coordinator ryan                                                                       │ denton texas                      │
│     5 │ Advisory Board Member at Celal Bayar University                                                                       │ İzmir, Türkiye                      │ 500+       │ NULL    │ advisory board member celal bayar university                                                              │ i̇zmir türkiye                     │
│     6 │ Aspiring Human Resources Specialist                                                                                   │ Greater New York City Area          │ 1          │ NULL    │ aspiring human resources specialist                                                                       │ greater new york city area        │
│     7 │ Student at Humber College and Aspiring Human Resources Generalist                                                     │ Kanada                              │ 61         │ NULL    │ student humber college aspiring human resources generalist                                                │ kanada                            │
│     8 │ HR Senior Specialist                                                                                                  │ San Francisco Bay Area              │ 500+       │ NULL    │ hr senior specialist                                                                                      │ san francisco bay area            │
│     9 │ Student at Humber College and Aspiring Human Resources Generalist                                                     │ Kanada                              │ 61         │ NULL    │ student humber college aspiring human resources generalist                                                │ kanada                            │
│    10 │ Seeking Human Resources HRIS and Generalist Positions                                                                 │ Greater Philadelphia Area           │ 500+       │ NULL    │ seeking human resources hris generalist positions                                                         │ greater philadelphia area         │
│     · │                   ·                                                                                                   │             ·                       │ ·          │  ·      │                 ·                                                                                         │             ·                     │
│     · │                   ·                                                                                                   │             ·                       │ ·          │  ·      │                 ·                                                                                         │             ·                     │
│     · │                   ·                                                                                                   │             ·                       │ ·          │  ·      │                 ·                                                                                         │             ·                     │
│    95 │ Student at Westfield State University                                                                                 │ Bridgewater, Massachusetts          │ 57         │ NULL    │ student westfield state university                                                                        │ bridgewater massachusetts         │
│    96 │ Student at Indiana University Kokomo - Business Management - \nRetail Manager at Delphi Hardware and Paint            │ Lafayette, Indiana                  │ 19         │ NULL    │ student indiana university kokomo business management retail manager delphi hardware paint                │ lafayette indiana                 │
│    97 │ Aspiring Human Resources Professional                                                                                 │ Kokomo, Indiana Area                │ 71         │ NULL    │ aspiring human resources professional                                                                     │ kokomo indiana area               │
│    98 │ Student                                                                                                               │ Houston, Texas Area                 │ 4          │ NULL    │ student                                                                                                   │ houston texas area                │
│    99 │ Seeking Human Resources Position                                                                                      │ Las Vegas, Nevada Area              │ 48         │ NULL    │ seeking human resources position                                                                          │ las vegas nevada area             │
│   100 │ Aspiring Human Resources Manager | Graduating May 2020 | Seeking an Entry-Level Human Resources Position in St. Louis │ Cape Girardeau, Missouri            │ 103        │ NULL    │ aspiring human resources manager graduating may 2020 seeking entrylevel human resources position st louis │ cape girardeau missouri           │
│   101 │ Human Resources Generalist at Loparex                                                                                 │ Raleigh-Durham, North Carolina Area │ 500+       │ NULL    │ human resources generalist loparex                                                                        │ raleighdurham north carolina area │
│   102 │ Business Intelligence and Analytics at Travelers                                                                      │ Greater New York City Area          │ 49         │ NULL    │ business intelligence analytics travelers                                                                 │ greater new york city area        │
│   103 │ Always set them up for Success                                                                                        │ Greater Los Angeles Area            │ 500+       │ NULL    │ always set success                                                                                        │ greater los angeles area          │
│   104 │ Director Of Administration at Excellence Logging                                                                      │ Katy, Texas                         │ 500+       │ NULL    │ director administration excellence logging                                                                │ katy texas                        │
├───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────┴────────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────┤
│ 104 rows (20 shown)                                                                                                                                                                                                                                                                                                              7 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Tf-Idf Vectorization

I use Tf(Term Frequency)-Idf (Inverse Document Frequency) to convert job titles into numerical vectors, weighting words by their importance and enabling mathematical computations.

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Convert DuckDB relation to Pandas DataFrame
df = data.fetchdf()

# Initialize TfidfVectorizer
vectorizer_job_title = TfidfVectorizer(stop_words='english', max_features=5000)

# Fill NaN values in 'job_title' column with empty strings to prevent errors during vectorization
df['cleaned_job_title'] = df['cleaned_job_title'].fillna('')

# Fit and transform the 'job_title' column
job_title_tfidf_matrix = vectorizer_job_title.fit_transform(df['cleaned_job_title'])

job_title_feature_names = vectorizer_job_title.get_feature_names_out()

print("TF-IDF matrix shape:", job_title_tfidf_matrix.shape)
print("Features (words):", vectorizer_job_title.get_feature_names_out()[:20]) # Print first 20 features

tf_idf_job_title_df = pd.DataFrame(job_title_tfidf_matrix.toarray(), columns=job_title_feature_names)
print(tf_idf_job_title_df)

TF-IDF matrix shape: (104, 178)
Features (words): ['2019' '2020' '408' '7092621' 'administration' 'administrative'
 'admissions' 'advisory' 'america' 'analyst' 'analytics' 'army' 'arts'
 'aspiring' 'assistant' 'atlanta' 'bachelor' 'bauer' 'bayar' 'beach']
         2019      2020  408  7092621  administration  administrative  \
0    0.321105  0.000000  0.0      0.0        0.000000             0.0
1    0.000000  0.000000  0.0      0.0        0.000000             0.0
2    0.000000  0.000000  0.0      0.0        0.000000             0.0
3    0.000000  0.000000  0.0      0.0        0.000000             0.0
4    0.000000  0.000000  0.0      0.0        0.000000             0.0
..        ...       ...  ...      ...             ...             ...
99   0.000000  0.364453  0.0      0.0        0.000000             0.0
100  0.000000  0.000000  0.0      0.0        0.000000             0.0
101  0.000000  0.000000  0.0      0.0        0.000000             0.0
102  0.000000  0.000000  0.0      0.0        0.000000             0.0
103  0.000000  0.000000  0.0      0.0        0.517083             0.0

     admissions  advisory  america  analyst  ...  travelers  undergraduate  \
0           0.0  0.000000      0.0      0.0  ...   0.000000            0.0
1           0.0  0.000000      0.0      0.0  ...   0.000000            0.0
2           0.0  0.000000      0.0      0.0  ...   0.000000            0.0
3           0.0  0.000000      0.0      0.0  ...   0.000000            0.0
4           0.0  0.423208      0.0      0.0  ...   0.000000            0.0
..          ...       ...      ...      ...  ...        ...            ...
99          0.0  0.000000      0.0      0.0  ...   0.000000            0.0
100         0.0  0.000000      0.0      0.0  ...   0.000000            0.0
101         0.0  0.000000      0.0      0.0  ...   0.541682            0.0
102         0.0  0.000000      0.0      0.0  ...   0.000000            0.0
103         0.0  0.000000      0.0      0.0  ...   0.000000            0.0

     university  victoria  wellington  western  westfield  woodlands  work  \
0      0.000000       0.0         0.0      0.0        0.0        0.0   0.0
1      0.000000       0.0         0.0      0.0        0.0        0.0   0.0
2      0.000000       0.0         0.0      0.0        0.0        0.0   0.0
3      0.000000       0.0         0.0      0.0        0.0        0.0   0.0
4      0.323226       0.0         0.0      0.0        0.0        0.0   0.0
..          ...       ...         ...      ...        ...        ...   ...
99     0.000000       0.0         0.0      0.0        0.0        0.0   0.0
100    0.000000       0.0         0.0      0.0        0.0        0.0   0.0
101    0.000000       0.0         0.0      0.0        0.0        0.0   0.0
102    0.000000       0.0         0.0      0.0        0.0        0.0   0.0
103    0.000000       0.0         0.0      0.0        0.0        0.0   0.0

     world
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
..     ...
99     0.0
100    0.0
101    0.0
102    0.0
103    0.0

[104 rows x 178 columns]

## Ranking Candidates Based on the fitness score from TF-Idf Vectorization

I have implemented a system that ranks the candidates based on the fitness with the given search keywords.

By representing both the job title dataset and search keywords in a shared TF-IDF vector space, the system computes the similiary by calculating the cosine similarity scores of the vector represenations.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import hstack

class RankCandidatesTfIdf:
  def __init__(self, job_title_vectorizer, combined_features_matrix, dataframe):
    self.job_title_vectorizer = job_title_vectorizer
    self.combined_features_matrix = combined_features_matrix
    self.dataframe = dataframe

  def return_top_profiles(self, search_term: str, n_profiles: int):
    # Vectorize the search term for job title
    search_term_job_title_vector = self.job_title_vectorizer.transform([search_term])

    # Calculate cosine similarity between the search term and all combined profiles
    search_term_similarities = cosine_similarity(search_term_job_title_vector, self.combined_features_matrix).flatten()

    # Get the indices that would sort these similarities in descending order
    sorted_indices = search_term_similarities.argsort()[::-1]

    # Select the top n_profiles indices
    top_profile_indices = sorted_indices[:n_profiles]

    # Create a list of dictionaries for the top profiles
    ranked_profiles = []
    for idx in top_profile_indices:
        profile_info = {
            "id": self.dataframe.loc[idx, 'id'],
            "job_title": self.dataframe.loc[idx, 'job_title'],
            "location": self.dataframe.loc[idx, 'location'],
            "similarity_score": search_term_similarities[idx]
        }
        ranked_profiles.append(profile_info)

    return ranked_profiles

In [ ]:
rank_profile_obj = RankCandidatesTfIdf(vectorizer_job_title, job_title_tfidf_matrix, df)

In [ ]:
rank_profile_obj.return_top_profiles("Human Resources", 5)

[{'id': np.int64(74),
  'job_title': 'Human Resources Professional',
  'location': 'Greater Boston Area',
  'similarity_score': np.float64(0.6375192019339917)},
 {'id': np.int64(73),
  'job_title': 'Aspiring Human Resources Manager, seeking internship in Human Resources.',
  'location': 'Houston, Texas Area',
  'similarity_score': np.float64(0.547443027634779)},
 {'id': np.int64(97),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Kokomo, Indiana Area',
  'similarity_score': np.float64(0.5439387582130529)},
 {'id': np.int64(21),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float64(0.5439387582130529)},
 {'id': np.int64(17),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float64(0.5439387582130529)}]

In [ ]:
rank_profile_obj.return_top_profiles("Aspiring human resources", 3)

[{'id': np.int64(97),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Kokomo, Indiana Area',
  'similarity_score': np.float64(0.7535909978974563)},
 {'id': np.int64(33),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float64(0.7535909978974563)},
 {'id': np.int64(3),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float64(0.7535909978974563)}]

In [ ]:
rank_profile_obj.return_top_profiles("seeking human resources", 3)

[{'id': np.int64(30),
  'job_title': 'Seeking Human Resources Opportunities',
  'location': 'Chicago, Illinois',
  'similarity_score': np.float64(0.6649332283463288)},
 {'id': np.int64(28),
  'job_title': 'Seeking Human Resources Opportunities',
  'location': 'Chicago, Illinois',
  'similarity_score': np.float64(0.6649332283463288)},
 {'id': np.int64(99),
  'job_title': 'Seeking Human Resources Position',
  'location': 'Las Vegas, Nevada Area',
  'similarity_score': np.float64(0.6448509778309305)}]

In [ ]:
rank_profile_obj.return_top_profiles("Software", 3)

[{'id': np.int64(84),
  'job_title': 'Human Resources professional for the world leader in GIS software',
  'location': 'Highland, California',
  'similarity_score': np.float64(0.48171917384456087)},
 {'id': np.int64(104),
  'job_title': 'Director Of Administration at Excellence Logging',
  'location': 'Katy, Texas',
  'similarity_score': np.float64(0.0)},
 {'id': np.int64(102),
  'job_title': 'Business Intelligence and Analytics at Travelers',
  'location': 'Greater New York City Area',
  'similarity_score': np.float64(0.0)}]

In [ ]:
rank_profile_obj.return_top_profiles("Business", 3)

[{'id': np.int64(72),
  'job_title': 'Business Management Major and Aspiring Human Resources Manager',
  'location': 'Monroe, Louisiana Area',
  'similarity_score': np.float64(0.3969642939291679)},
 {'id': np.int64(102),
  'job_title': 'Business Intelligence and Analytics at Travelers',
  'location': 'Greater New York City Area',
  'similarity_score': np.float64(0.34603605269646276)},
 {'id': np.int64(81),
  'job_title': 'Senior Human Resources Business Partner at Heil Environmental',
  'location': 'Chattanooga, Tennessee Area',
  'similarity_score': np.float64(0.3133472484941707)}]

In [ ]:
rank_profile_obj.return_top_profiles("blah", 3)

[{'id': np.int64(104),
  'job_title': 'Director Of Administration at Excellence Logging',
  'location': 'Katy, Texas',
  'similarity_score': np.float64(0.0)},
 {'id': np.int64(103),
  'job_title': 'Always set them up for Success',
  'location': 'Greater Los Angeles Area',
  'similarity_score': np.float64(0.0)},
 {'id': np.int64(102),
  'job_title': 'Business Intelligence and Analytics at Travelers',
  'location': 'Greater New York City Area',
  'similarity_score': np.float64(0.0)}]

# Word Embedding

Tokenization: I tokenize the job title corpus and the search term by segmenting into individual words, treating each word as a distinct token.

## word2vec

word2vec is superior to tf-idf, but it has some shortcomings. For example, the fruit 'apple' and the Mac 'apple' are mapped to the same embeddings.

In [ ]:
from gensim.models import Word2Vec

# Tokenize the cleaned job titles into lists of words
tokenized_job_titles = [title.split() for title in df['cleaned_job_title']]

# Train the Word2Vec model
# window: maximum distance between the current and predicted word within a sentence
# min_count: Ignores all words with total frequency lower than this
# workers: Use these many worker threads to train the model
# seed: Seed for the random number generator, for reproducibility
word2vec_model = Word2Vec(sentences=tokenized_job_titles, vector_size=100, window=5, min_count=1, workers=1, seed=seed)

In [ ]:
word2vec_model.wv["human"]

array([-5.9152381e-03, -2.6968075e-03, -1.5343941e-03, -5.0976002e-03,
       -6.9142012e-03,  6.0090707e-03,  5.1979902e-03,  9.0153534e-03,
        8.0017000e-03, -7.5834668e-03, -5.9088003e-03,  2.7579004e-03,
        8.6597512e-03, -8.1006018e-03, -6.5313699e-03,  9.8591612e-04,
       -9.0751229e-03,  2.5883680e-03, -2.0894301e-03, -1.6212407e-03,
       -6.0914136e-03,  3.5206235e-03, -3.0131908e-03,  2.0821884e-03,
        3.6356868e-03, -6.7392229e-03,  1.9735850e-03,  5.8846958e-03,
        5.8228704e-03, -4.7258058e-04,  7.3038586e-03, -3.1477665e-03,
       -2.8815919e-03, -6.8486365e-04,  3.0971970e-04, -8.9085801e-03,
       -4.6188328e-03, -3.3424911e-03, -3.7590687e-03, -2.9012668e-03,
       -7.1161641e-03,  6.2174466e-03, -5.7525379e-03,  6.6746944e-03,
       -9.7030587e-03,  5.7526249e-03,  7.1490468e-03,  6.3909744e-03,
       -3.3946845e-03,  6.2694098e-03, -2.4358279e-03,  9.6385684e-03,
       -7.1207215e-03, -4.1405484e-03, -7.3408177e-03,  2.8443804e-03,
        6.4725140e-03, -5.1398291e-03, -7.9038637e-03,  1.7403375e-03,
        2.7515420e-03,  3.8959747e-03, -8.6754374e-03,  9.3789666e-04,
        6.3856882e-03,  2.1558132e-03,  1.2875363e-03,  1.4068591e-03,
       -4.4316482e-03,  7.4722678e-03,  5.9056785e-03,  7.4709095e-03,
        7.2194943e-03, -2.8847638e-03,  4.5183544e-05,  4.6347347e-03,
       -8.3690444e-03, -6.7373291e-03, -8.9833644e-05,  8.3777187e-03,
        5.8506923e-03, -8.6564319e-03, -2.5244129e-03,  6.6269180e-03,
        8.4123835e-03, -8.4811915e-03, -9.8412018e-03,  3.8000366e-03,
        2.5590104e-03,  5.8565340e-03, -1.5297531e-03,  5.2344273e-03,
        7.5075626e-03, -4.9612569e-03, -4.1524447e-03, -8.7762596e-03,
        9.4776712e-03, -7.9735061e-03, -3.0249900e-03, -8.7940972e-03],
      dtype=float32)

In [ ]:
word2vec_model.wv["AI"]

KeyError: "Key 'AI' not present"

Limitation of wordvec: I get a KeyError if I try to find the word embedding of a word that's not in the training data.

### Ranking Candidates Based on the similarity score from word2vec embedding

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

class RankCandidatesWord2vec:
    def __init__(self, word2vec_model, dataframe):
        self.word2vec_model = word2vec_model
        self.dataframe = dataframe
        self.vector_size = self.word2vec_model.vector_size

    def _get_phrase_vector(self, phrase_words):
        # Filter out words not in the model's vocabulary
        valid_words = [word for word in phrase_words if word in self.word2vec_model.wv.key_to_index]

        if not valid_words:
            # If no words are in vocabulary, return a zero vector
            return np.zeros((1, self.vector_size))

        # Get vectors for valid words and calculate their mean
        vectors = [self.word2vec_model.wv[word] for word in valid_words]
        return np.mean(vectors, axis=0).reshape(1, -1)

    def return_top_profiles(self, search_term: str, n_profiles: int):
        # Clean and tokenize the search term
        cleaned_search_term = clean_text(search_term)
        tokenized_search_term = cleaned_search_term.split()

        # Get the vector for the search term
        search_term_vector = self._get_phrase_vector(tokenized_search_term)

        # Get vectors for all cleaned job titles in the dataframe
        # Ensure 'cleaned_job_title' is treated as a list of words for tokenization
        job_title_vectors = np.vstack([
            self._get_phrase_vector(str(title).split())
            for title in self.dataframe['cleaned_job_title'].tolist()
        ])

        # Calculate cosine similarity between the search term vector and all job title vectors
        similarities = cosine_similarity(search_term_vector, job_title_vectors).flatten()

        # Get the indices that would sort these similarities in descending order
        sorted_indices = similarities.argsort()[::-1]

        # Select the top n_profiles indices
        top_profile_indices = sorted_indices[:n_profiles]

        # Create a list of dictionaries for the top profiles
        ranked_profiles = []
        for idx in top_profile_indices:
            profile_info = {
                "id": self.dataframe.loc[idx, 'id'],
                "job_title": self.dataframe.loc[idx, 'job_title'],
                "location": self.dataframe.loc[idx, 'location'],
                "similarity_score": similarities[idx]
            }
            ranked_profiles.append(profile_info)

        return ranked_profiles

In [ ]:
rank_profile_word_embedding_obj = RankCandidatesWord2vec(word2vec_model, df)

In [ ]:
rank_profile_word_embedding_obj.return_top_profiles("Human Resources", 5)

[{'id': np.int64(74),
  'job_title': 'Human Resources Professional',
  'location': 'Greater Boston Area',
  'similarity_score': np.float32(0.8579174)},
 {'id': np.int64(73),
  'job_title': 'Aspiring Human Resources Manager, seeking internship in Human Resources.',
  'location': 'Houston, Texas Area',
  'similarity_score': np.float32(0.839593)},
 {'id': np.int64(97),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Kokomo, Indiana Area',
  'similarity_score': np.float32(0.79859436)},
 {'id': np.int64(21),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float32(0.79859436)},
 {'id': np.int64(17),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float32(0.79859436)}]

In [ ]:
rank_profile_word_embedding_obj.return_top_profiles("Aspiring human resources", 3)

[{'id': np.int64(24),
  'job_title': 'Aspiring Human Resources Specialist',
  'location': 'Greater New York City Area',
  'similarity_score': np.float32(0.89259577)},
 {'id': np.int64(36),
  'job_title': 'Aspiring Human Resources Specialist',
  'location': 'Greater New York City Area',
  'similarity_score': np.float32(0.89259577)},
 {'id': np.int64(49),
  'job_title': 'Aspiring Human Resources Specialist',
  'location': 'Greater New York City Area',
  'similarity_score': np.float32(0.89259577)}]

In [ ]:
rank_profile_word_embedding_obj.return_top_profiles("Software", 3)

[{'id': np.int64(84),
  'job_title': 'Human Resources professional for the world leader in GIS software',
  'location': 'Highland, California',
  'similarity_score': np.float32(0.3278067)},
 {'id': np.int64(34),
  'job_title': 'People Development Coordinator at Ryan',
  'location': 'Denton, Texas',
  'similarity_score': np.float32(0.17579666)},
 {'id': np.int64(4),
  'job_title': 'People Development Coordinator at Ryan',
  'location': 'Denton, Texas',
  'similarity_score': np.float32(0.17579666)}]

In [ ]:
rank_profile_word_embedding_obj.return_top_profiles("Data", 3)

[{'id': np.int64(86),
  'job_title': 'Information Systems Specialist and Programmer with a love for data and organization.',
  'location': 'Gaithersburg, Maryland',
  'similarity_score': np.float32(0.44628224)},
 {'id': np.int64(72),
  'job_title': 'Business Management Major and Aspiring Human Resources Manager',
  'location': 'Monroe, Louisiana Area',
  'similarity_score': np.float32(0.14968173)},
 {'id': np.int64(76),
  'job_title': 'Aspiring Human Resources Professional | Passionate about helping to create an inclusive and engaging work environment',
  'location': 'New York, New York',
  'similarity_score': np.float32(0.13735649)}]

## GloVe: Global Vectors

In [ ]:
import os

# Define the URL for the GloVe embeddings
glove_url = "http://nlp.stanford.edu/data/glove.6B.zip"
zip_file_name = "glove.6B.zip"

# Download the GloVe embeddings if not already downloaded
if not os.path.exists(zip_file_name):
    print(f"Downloading {zip_file_name}...")
    !wget {glove_url}
else:
    print(f"{zip_file_name} already exists. Skipping download.")

# Extract the GloVe embeddings if not already extracted (check for one of the expected files)
expected_glove_file = "glove.6B.100d.txt"
if not os.path.exists(expected_glove_file):
    print(f"Extracting {zip_file_name}...")
    !unzip -q {zip_file_name}
else:
    print(f"GloVe embeddings (e.g., {expected_glove_file}) already extracted. Skipping extraction.")

print("GloVe download and extraction complete.")

Downloading glove.6B.zip...
--2026-03-27 12:55:50--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2026-03-27 12:55:50--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2026-03-27 12:55:50--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.02MB/s    in 2m 41s

2026-03-27 12:58:31 (5.11 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]

Extracting glove.6B.zip...
GloVe download and extraction complete.

In [ ]:
glove_model_path = "glove.6B.100d.txt"
glove_embeddings = {}

with open(glove_model_path, 'r', encoding='utf-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], dtype='float32')
        glove_embeddings[word] = vector

In [ ]:
glove_embeddings['human'][:10]

array([ 0.33864  ,  0.59663  ,  0.53322  ,  0.31404  ,  0.15321  ,
        0.31749  , -0.4294   , -0.2915   , -0.0021047, -0.39309  ],
      dtype=float32)

In [ ]:
glove_embeddings['AI'][:10]

KeyError: 'AI'

Limitation of GloVe: I get a KeyError if I try to find the word embedding of a word that's not in the training data.

### Ranking Candidates Based on the similarity score from GloVe Embedding

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

class RankCandidatesGloVe:
    def __init__(self, glove_embeddings, dataframe):
        self.glove_embeddings = glove_embeddings
        self.dataframe = dataframe
        # Assuming 100d embeddings as per `glove.6B.100d.txt`
        self.vector_size = 100

    def _get_phrase_vector(self, phrase_words):
        # Filter out words not in the model's vocabulary
        valid_words = [word for word in phrase_words if word in self.glove_embeddings]

        if not valid_words:
            # If no words are in vocabulary, return a zero vector
            return np.zeros((1, self.vector_size))

        # Get vectors for valid words and calculate their mean
        vectors = [self.glove_embeddings[word] for word in valid_words]
        return np.mean(vectors, axis=0).reshape(1, -1)

    def return_top_profiles(self, search_term: str, n_profiles: int):
        # Clean and tokenize the search term using the existing clean_text function
        cleaned_search_term = clean_text(search_term)
        tokenized_search_term = cleaned_search_term.split()

        # Get the vector for the search term
        search_term_vector = self._get_phrase_vector(tokenized_search_term)

        # Get vectors for all cleaned job titles in the dataframe
        job_title_vectors = np.vstack([
            self._get_phrase_vector(str(title).split())
            for title in self.dataframe['cleaned_job_title'].tolist()
        ])

        # Calculate cosine similarity between the search term vector and all job title vectors
        similarities = cosine_similarity(search_term_vector, job_title_vectors).flatten()

        # Get the indices that would sort these similarities in descending order
        sorted_indices = similarities.argsort()[::-1]

        # Select the top n_profiles indices
        top_profile_indices = sorted_indices[:n_profiles]

        # Create a list of dictionaries for the top profiles
        ranked_profiles = []
        for idx in top_profile_indices:
            profile_info = {
                "id": self.dataframe.loc[idx, 'id'],
                "job_title": self.dataframe.loc[idx, 'job_title'],
                "location": self.dataframe.loc[idx, 'location'],
                "similarity_score": similarities[idx]
            }
            ranked_profiles.append(profile_info)

        return ranked_profiles

In [ ]:
rank_profile_glove_obj = RankCandidatesGloVe(glove_embeddings, df)

In [ ]:
rank_profile_glove_obj.return_top_profiles("Human Resources", 5)

[{'id': np.int64(101),
  'job_title': 'Human Resources Generalist at Loparex',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float32(0.9271207)},
 {'id': np.int64(78),
  'job_title': "Human Resources Generalist at Schwan's",
  'location': 'Amerika Birleşik Devletleri',
  'similarity_score': np.float32(0.9271207)},
 {'id': np.int64(74),
  'job_title': 'Human Resources Professional',
  'location': 'Greater Boston Area',
  'similarity_score': np.float32(0.9202033)},
 {'id': np.int64(28),
  'job_title': 'Seeking Human Resources Opportunities',
  'location': 'Chicago, Illinois',
  'similarity_score': np.float32(0.9121238)},
 {'id': np.int64(30),
  'job_title': 'Seeking Human Resources Opportunities',
  'location': 'Chicago, Illinois',
  'similarity_score': np.float32(0.9121238)}]

In [ ]:
rank_profile_glove_obj.return_top_profiles("AI", 3)

[{'id': np.int64(103),
  'job_title': 'Always set them up for Success',
  'location': 'Greater Los Angeles Area',
  'similarity_score': np.float32(0.3870576)},
 {'id': np.int64(86),
  'job_title': 'Information Systems Specialist and Programmer with a love for data and organization.',
  'location': 'Gaithersburg, Maryland',
  'similarity_score': np.float32(0.33819702)},
 {'id': np.int64(84),
  'job_title': 'Human Resources professional for the world leader in GIS software',
  'location': 'Highland, California',
  'similarity_score': np.float32(0.30733305)}]

## FastText

- character n-gram
  - resilient to typos
  - supports morphologically rich languages
  - byte pair encoding
    - improved computational efficiency
    - "based" and "base" have similar semantic meanings: encodes "base" and "d"
    - "encoding": "encod" and "ing"

In [ ]:
!pip install fasttext

Collecting fasttext
  Downloading fasttext-0.9.3.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-3.0.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fasttext) (2.0.2)
Using cached pybind11-3.0.2-py3-none-any.whl (310 kB)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (pyproject.toml) ... done
  Created wheel for fasttext: filename=fasttext-0.9.3-cp312-cp312-linux_x86_64.whl size=4647420 sha256=ea3823746c613a52a9fe7b8bfc75a55f1837ba379e90f476915c9844557743f6
  Stored in directory: /root/.cache/pip/wheels/20/27/95/a7baf1b435f1cbde017cabdf1e9688526d2b0e929255a359c6
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.3 pybind11-3.0.2

In [ ]:
fasttext_input_file = "cleaned_job_titles.txt"
with open(fasttext_input_file, 'w') as f:
    for item in df['cleaned_job_title'].dropna():
        f.write(item + '\n')

In [ ]:
import fasttext

In [ ]:
fasttext_model = fasttext.train_unsupervised(fasttext_input_file, model='skipgram', dim=100, epoch=10, minCount=1)

In [ ]:
print(fasttext_model.get_word_vector("human")[:10])

[ 4.4122807e-04 -4.7833481e-04 -9.1423477e-05 -2.4253734e-04
  2.3381428e-05 -4.6130156e-04 -5.5204681e-04 -6.2492763e-04
  6.9250591e-04  6.6774746e-04]

In [ ]:
print(fasttext_model.get_word_vector("AI")[:10])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

### Ranking Candidates Based on the similarity score from fasttext

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

class RankCandidatesFastText:
    def __init__(self, fasttext_model, dataframe):
        self.fasttext_model = fasttext_model
        self.dataframe = dataframe
        # FastText model dimension is set to 100 during training (dim=100)
        self.vector_size = self.fasttext_model.get_dimension()

    def _get_phrase_vector(self, phrase_words):
        # Filter out words not in the model's vocabulary (though FastText handles OOV words)
        # For simplicity, we'll still check for words that might not produce meaningful vectors
        # or average only from words that have actual vectors.

        # FastText can generate vectors for OOV words by using subword information,
        # so we don't strictly need to check if word in model.words.

        vectors = [self.fasttext_model.get_word_vector(word) for word in phrase_words if word.strip() != '']

        if not vectors:
            # If no words in the phrase, return a zero vector
            return np.zeros((1, self.vector_size))

        # Average the word vectors
        return np.mean(vectors, axis=0).reshape(1, -1)

    def return_top_profiles(self, search_term: str, n_profiles: int):
        # Clean and tokenize the search term using the existing clean_text function
        cleaned_search_term = clean_text(search_term)
        tokenized_search_term = cleaned_search_term.split()

        # Get the vector for the search term
        search_term_vector = self._get_phrase_vector(tokenized_search_term)

        # Initialize a list to hold job title vectors
        job_title_vectors_list = []
        for title in self.dataframe['cleaned_job_title'].tolist():
            # Ensure the title is treated as a string before splitting
            tokenized_title = str(title).split()
            job_title_vectors_list.append(self._get_phrase_vector(tokenized_title))

        # Stack the list of vectors into a NumPy array
        job_title_vectors = np.vstack(job_title_vectors_list)

        # Calculate cosine similarity between the search term vector and all job title vectors
        similarities = cosine_similarity(search_term_vector, job_title_vectors).flatten()

        # Get the indices that would sort these similarities in descending order
        sorted_indices = similarities.argsort()[::-1]

        # Select the top n_profiles indices
        top_profile_indices = sorted_indices[:n_profiles]

        # Create a list of dictionaries for the top profiles
        ranked_profiles = []
        for idx in top_profile_indices:
            profile_info = {
                "id": self.dataframe.loc[idx, 'id'],
                "job_title": self.dataframe.loc[idx, 'job_title'],
                "location": self.dataframe.loc[idx, 'location'],
                "similarity_score": similarities[idx]
            }
            ranked_profiles.append(profile_info)

        return ranked_profiles

In [ ]:
rank_profile_fasttext_obj = RankCandidatesFastText(fasttext_model, df)

In [ ]:
rank_profile_fasttext_obj.return_top_profiles("Human Resources", 5)

[{'id': np.int64(74),
  'job_title': 'Human Resources Professional',
  'location': 'Greater Boston Area',
  'similarity_score': np.float32(0.9216496)},
 {'id': np.int64(73),
  'job_title': 'Aspiring Human Resources Manager, seeking internship in Human Resources.',
  'location': 'Houston, Texas Area',
  'similarity_score': np.float32(0.8066384)},
 {'id': np.int64(101),
  'job_title': 'Human Resources Generalist at Loparex',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float32(0.78805536)},
 {'id': np.int64(97),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Kokomo, Indiana Area',
  'similarity_score': np.float32(0.7448012)},
 {'id': np.int64(17),
  'job_title': 'Aspiring Human Resources Professional',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float32(0.7448012)}]

In [ ]:
rank_profile_fasttext_obj.return_top_profiles("Software", 3)

[{'id': np.int64(84),
  'job_title': 'Human Resources professional for the world leader in GIS software',
  'location': 'Highland, California',
  'similarity_score': np.float32(0.3352996)},
 {'id': np.int64(93),
  'job_title': 'Admissions Representative at Community medical center long beach',
  'location': 'Long Beach, California',
  'similarity_score': np.float32(0.2580709)},
 {'id': np.int64(71),
  'job_title': 'Human Resources Generalist at ScottMadden, Inc.',
  'location': 'Raleigh-Durham, North Carolina Area',
  'similarity_score': np.float32(0.22797754)}]

In [ ]:
rank_profile_fasttext_obj.return_top_profiles("AI", 3)

[{'id': np.int64(104),
  'job_title': 'Director Of Administration at Excellence Logging',
  'location': 'Katy, Texas',
  'similarity_score': np.float32(0.0)},
 {'id': np.int64(103),
  'job_title': 'Always set them up for Success',
  'location': 'Greater Los Angeles Area',
  'similarity_score': np.float32(0.0)},
 {'id': np.int64(102),
  'job_title': 'Business Intelligence and Analytics at Travelers',
  'location': 'Greater New York City Area',
  'similarity_score': np.float32(0.0)}]

# Contextualized Embedding

In [ ]:
!pip install tensorflow
!pip install tensorflow-hub

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Requirement already satisfied: tensorflow-hub in /usr/local/lib/python3.12/dist-packages (0.16.1)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow-hub) (2.0.2)
Requirement already satisfied: protobuf>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow-hub) (5.29.6)
Requirement already satisfied: tf-keras>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow-hub) (2.19.0)
Requirement already satisfied: tensorflow<2.20,>=2.19 in /usr/local/lib/python3.12/dist-packages (from tf-keras>=2.14.1->tensorflow-hub) (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (26.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.13.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras>=2.14.1->tensorflow-hub) (0.1.2)

## ELMo

In [ ]:
elmo_model = hub.load("https://tfhub.dev/google/elmo/3")

def get_elmo_embedding(text_list):
    if not text_list or all(not s.strip() for s in text_list):
        # Return a zero vector if the input list is empty or contains only empty strings
        # ELMo default output dimension is 1024 for the 'default' signature.
        return np.zeros(1024)

    # The ELMo module expects a list of strings for signature='default'
    # It returns a dictionary with 'elmo', 'default', 'word_emb' keys.
    # 'default' is typically the average of the 3 layers.
    embeddings = elmo_model.signatures["default"](tf.constant(text_list))["default"]
    return embeddings.numpy().mean(axis=0)

# Apply ELMo embeddings to the 'cleaned_job_title' column
# This will be computationally intensive and might take a long time.
# Ensure 'cleaned_job_title' column has string values for ELMo.
df['elmo_embedding'] = df['cleaned_job_title'].apply(lambda x: get_elmo_embedding([str(x)]))

print("ELMo embeddings generated.")
print(f"Shape of first ELMo embedding: {df['elmo_embedding'].iloc[0].shape}")

class RankCandidatesELMo:
    def __init__(self, elmo_model, dataframe, embedding_column='elmo_embedding'):
        self.elmo_model = elmo_model
        self.dataframe = dataframe
        self.embedding_column = embedding_column
        self.vector_size = 1024 # ELMo's 'default' output dimension

    def _get_search_term_vector(self, search_term: str):
        if not search_term:
            return np.zeros(self.vector_size).reshape(1, -1)

        cleaned_search_term = clean_text(search_term)
        return get_elmo_embedding([cleaned_search_term]).reshape(1, -1)

    def return_top_profiles(self, search_term: str, n_profiles: int):
        search_term_vector = self._get_search_term_vector(search_term)

        # Stack the ELMo embeddings from the DataFrame into a single NumPy array
        job_title_vectors = np.vstack(self.dataframe[self.embedding_column].tolist())

        similarities = cosine_similarity(search_term_vector, job_title_vectors).flatten()

        sorted_indices = similarities.argsort()[::-1]
        top_profile_indices = sorted_indices[:n_profiles]

        ranked_profiles = []
        for idx in top_profile_indices:
            profile_info = {
                "id": self.dataframe.loc[idx, 'id'],
                "job_title": self.dataframe.loc[idx, 'job_title'],
                "location": self.dataframe.loc[idx, 'location'],
                "similarity_score": similarities[idx]
            }
            ranked_profiles.append(profile_info)

        return ranked_profiles

ELMo embeddings generated.
Shape of first ELMo embedding: (1024,)
[{'id': np.int64(74), 'job_title': 'Human Resources Professional', 'location': 'Greater Boston Area', 'similarity_score': np.float32(0.8433589)}, {'id': np.int64(78), 'job_title': "Human Resources Generalist at Schwan's", 'location': 'Amerika Birleşik Devletleri', 'similarity_score': np.float32(0.7674339)}, {'id': np.int64(101), 'job_title': 'Human Resources Generalist at Loparex', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.76362324)}, {'id': np.int64(88), 'job_title': 'Human Resources Management Major', 'location': 'Milpitas, California', 'similarity_score': np.float32(0.72693616)}, {'id': np.int64(73), 'job_title': 'Aspiring Human Resources Manager, seeking internship in Human Resources.', 'location': 'Houston, Texas Area', 'similarity_score': np.float32(0.7257056)}]
[{'id': np.int64(97), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Kokomo, Indiana Area', 'similarity_score': np.float32(0.87471354)}, {'id': np.int64(33), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.87471354)}, {'id': np.int64(3), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.87471354)}]
[{'id': np.int64(84), 'job_title': 'Human Resources professional for the world leader in GIS software', 'location': 'Highland, California', 'similarity_score': np.float32(0.54951435)}, {'id': np.int64(86), 'job_title': 'Information Systems Specialist and Programmer with a love for data and organization.', 'location': 'Gaithersburg, Maryland', 'similarity_score': np.float32(0.5426526)}, {'id': np.int64(102), 'job_title': 'Business Intelligence and Analytics at Travelers', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.52345294)}]
[{'id': np.int64(86), 'job_title': 'Information Systems Specialist and Programmer with a love for data and organization.', 'location': 'Gaithersburg, Maryland', 'similarity_score': np.float32(0.5722693)}, {'id': np.int64(102), 'job_title': 'Business Intelligence and Analytics at Travelers', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.47402236)}, {'id': np.int64(80), 'job_title': 'Junior MES Engineer| Information Systems', 'location': 'Myrtle Beach, South Carolina Area', 'similarity_score': np.float32(0.4622829)}]
[{'id': np.int64(83), 'job_title': 'HR Manager at Endemol Shine North America', 'location': 'Los Angeles, California', 'similarity_score': np.float32(0.45817816)}, {'id': np.int64(85), 'job_title': 'RRP Brand Portfolio Executive at JTI (Japan Tobacco International)', 'location': 'Greater Philadelphia Area', 'similarity_score': np.float32(0.44970262)}, {'id': np.int64(51), 'job_title': 'HR Senior Specialist', 'location': 'San Francisco Bay Area', 'similarity_score': np.float32(0.4440644)}]

In [ ]:
rank_profile_elmo_obj = RankCandidatesELMo(elmo_model, df)

In [ ]:
print(rank_profile_elmo_obj.return_top_profiles("Human Resources", 5))

[{'id': np.int64(74), 'job_title': 'Human Resources Professional', 'location': 'Greater Boston Area', 'similarity_score': np.float32(0.8433589)}, {'id': np.int64(78), 'job_title': "Human Resources Generalist at Schwan's", 'location': 'Amerika Birleşik Devletleri', 'similarity_score': np.float32(0.7674339)}, {'id': np.int64(101), 'job_title': 'Human Resources Generalist at Loparex', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.76362324)}, {'id': np.int64(88), 'job_title': 'Human Resources Management Major', 'location': 'Milpitas, California', 'similarity_score': np.float32(0.72693616)}, {'id': np.int64(73), 'job_title': 'Aspiring Human Resources Manager, seeking internship in Human Resources.', 'location': 'Houston, Texas Area', 'similarity_score': np.float32(0.7257056)}]

In [ ]:
print(rank_profile_elmo_obj.return_top_profiles("Aspiring human resources", 3))
print(rank_profile_elmo_obj.return_top_profiles("Software", 3))
print(rank_profile_elmo_obj.return_top_profiles("Data", 3))
print(rank_profile_elmo_obj.return_top_profiles("AI", 3))

[{'id': np.int64(97), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Kokomo, Indiana Area', 'similarity_score': np.float32(0.87471354)}, {'id': np.int64(33), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.87471354)}, {'id': np.int64(3), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.87471354)}]
[{'id': np.int64(84), 'job_title': 'Human Resources professional for the world leader in GIS software', 'location': 'Highland, California', 'similarity_score': np.float32(0.54951435)}, {'id': np.int64(86), 'job_title': 'Information Systems Specialist and Programmer with a love for data and organization.', 'location': 'Gaithersburg, Maryland', 'similarity_score': np.float32(0.5426526)}, {'id': np.int64(102), 'job_title': 'Business Intelligence and Analytics at Travelers', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.52345294)}]
[{'id': np.int64(86), 'job_title': 'Information Systems Specialist and Programmer with a love for data and organization.', 'location': 'Gaithersburg, Maryland', 'similarity_score': np.float32(0.5722693)}, {'id': np.int64(102), 'job_title': 'Business Intelligence and Analytics at Travelers', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.47402236)}, {'id': np.int64(80), 'job_title': 'Junior MES Engineer| Information Systems', 'location': 'Myrtle Beach, South Carolina Area', 'similarity_score': np.float32(0.4622829)}]
[{'id': np.int64(83), 'job_title': 'HR Manager at Endemol Shine North America', 'location': 'Los Angeles, California', 'similarity_score': np.float32(0.45817816)}, {'id': np.int64(85), 'job_title': 'RRP Brand Portfolio Executive at JTI (Japan Tobacco International)', 'location': 'Greater Philadelphia Area', 'similarity_score': np.float32(0.44970262)}, {'id': np.int64(51), 'job_title': 'HR Senior Specialist', 'location': 'San Francisco Bay Area', 'similarity_score': np.float32(0.4440644)}]

## BERT

In [ ]:
!pip install transformers[sentencepiece] torch

import torch
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import tensorflow_hub as hub
import tensorflow as tf

# Load pre-trained BERT model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

def get_bert_embedding(text):
    if not text:
        return torch.zeros(model.config.hidden_size)
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=128)
    with torch.no_grad():
        outputs = model(**inputs)
    # Use the mean of the last hidden state as the sentence embedding
    return outputs.last_hidden_state.mean(dim=1).squeeze()

# Apply to job titles
# This might take a while depending on the size of your dataframe
df['bert_embedding'] = df['cleaned_job_title'].apply(get_bert_embedding)

print("BERT embeddings generated.")
print(f"Shape of first BERT embedding: {df['bert_embedding'].iloc[0].shape}")

class RankCandidatesBERT:
    def __init__(self, model, tokenizer, dataframe, embedding_column='bert_embedding'):
        self.model = model
        self.tokenizer = tokenizer
        self.dataframe = dataframe
        self.embedding_column = embedding_column
        self.vector_size = self.model.config.hidden_size

    def _get_search_term_vector(self, search_term: str):
        if not search_term:
            return torch.zeros(self.vector_size).unsqueeze(0)

        # Clean the search term using the existing clean_text function
        cleaned_search_term = clean_text(search_term)

        inputs = self.tokenizer(cleaned_search_term, return_tensors='pt', padding=True, truncation=True, max_length=128)
        with torch.no_grad():
            outputs = self.model(**inputs)
        return outputs.last_hidden_state.mean(dim=1)

    def return_top_profiles(self, search_term: str, n_profiles: int):
        search_term_vector = self._get_search_term_vector(search_term).numpy()

        # Convert list of tensors to a single NumPy array for similarity calculation
        job_title_vectors = np.vstack([embedding.numpy() for embedding in self.dataframe[self.embedding_column]])

        similarities = cosine_similarity(search_term_vector, job_title_vectors).flatten()

        sorted_indices = similarities.argsort()[::-1]
        top_profile_indices = sorted_indices[:n_profiles]

        ranked_profiles = []
        for idx in top_profile_indices:
            profile_info = {
                "id": self.dataframe.loc[idx, 'id'],
                "job_title": self.dataframe.loc[idx, 'job_title'],
                "location": self.dataframe.loc[idx, 'location'],
                "similarity_score": similarities[idx]
            }
            ranked_profiles.append(profile_info)

        return ranked_profiles

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: transformers[sentencepiece] in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (4.67.3)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]) (5.29.6)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (0.24.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers[sentencepiece]) (0.1.2)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

BERT embeddings generated.
Shape of first BERT embedding: torch.Size([768])

In [ ]:
rank_profile_bert_obj = RankCandidatesBERT(model, tokenizer, df)

print(rank_profile_bert_obj.return_top_profiles("Human Resources", 5))
print(rank_profile_bert_obj.return_top_profiles("Aspiring human resources", 3))
print(rank_profile_bert_obj.return_top_profiles("Software", 3))
print(rank_profile_bert_obj.return_top_profiles("Data", 3))
print(rank_profile_bert_obj.return_top_profiles("AI", 3))

[{'id': np.int64(74), 'job_title': 'Human Resources Professional', 'location': 'Greater Boston Area', 'similarity_score': np.float32(0.8730361)}, {'id': np.int64(88), 'job_title': 'Human Resources Management Major', 'location': 'Milpitas, California', 'similarity_score': np.float32(0.7823341)}, {'id': np.int64(89), 'job_title': 'Director Human Resources  at EY', 'location': 'Greater Atlanta Area', 'similarity_score': np.float32(0.77355504)}, {'id': np.int64(28), 'job_title': 'Seeking Human Resources Opportunities', 'location': 'Chicago, Illinois', 'similarity_score': np.float32(0.7523645)}, {'id': np.int64(30), 'job_title': 'Seeking Human Resources Opportunities', 'location': 'Chicago, Illinois', 'similarity_score': np.float32(0.7523645)}]
[{'id': np.int64(24), 'job_title': 'Aspiring Human Resources Specialist', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.90548)}, {'id': np.int64(36), 'job_title': 'Aspiring Human Resources Specialist', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.90548)}, {'id': np.int64(49), 'job_title': 'Aspiring Human Resources Specialist', 'location': 'Greater New York City Area', 'similarity_score': np.float32(0.90548)}]
[{'id': np.int64(98), 'job_title': 'Student', 'location': 'Houston, Texas Area', 'similarity_score': np.float32(0.8685982)}, {'id': np.int64(97), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Kokomo, Indiana Area', 'similarity_score': np.float32(0.70756316)}, {'id': np.int64(3), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.70756316)}]
[{'id': np.int64(98), 'job_title': 'Student', 'location': 'Houston, Texas Area', 'similarity_score': np.float32(0.79775035)}, {'id': np.int64(97), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Kokomo, Indiana Area', 'similarity_score': np.float32(0.6333132)}, {'id': np.int64(3), 'job_title': 'Aspiring Human Resources Professional', 'location': 'Raleigh-Durham, North Carolina Area', 'similarity_score': np.float32(0.6333132)}]
[{'id': np.int64(98), 'job_title': 'Student', 'location': 'Houston, Texas Area', 'similarity_score': np.float32(0.84635067)}, {'id': np.int64(38), 'job_title': 'HR Senior Specialist', 'location': 'San Francisco Bay Area', 'similarity_score': np.float32(0.62524176)}, {'id': np.int64(51), 'job_title': 'HR Senior Specialist', 'location': 'San Francisco Bay Area', 'similarity_score': np.float32(0.62524176)}]

# LLM

In this section, I use LLMs to compute the similarity scores between job profiles and search terms, and then rank the candidates based on the scores. Using LLM feels like I am communicating with a human: it gives conversational insights and makes the results more interpretible.

There are three main types of LLM's:
- Chat based LLM

- Instruction based LLM

- Reasoning LLM model

I have opted for an instruction-based LLM. Since the client is requesting a functional ranking system rather than a chatbot, this model type is a better fit for this project.

LLM usage
- local model: constraints with the hardware resources (e.g. RAM, disk space), inference latency
- cloud-based API approach: billed based on token usage, low network latency

## Qwen model

### Atomic approach

In this approach, I ran the LLM on each individual data entry to compute the semantic similarity score between the search term and each candidate's job title. Using the returned computation results, I returned the top candidates.

#### Hugging Face

I import the LLM from the Hugging Face model hub.

In [ ]:
model_path = "Qwen/Qwen3.5-9B-Base"

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

quantization_config = BitsAndBytesConfig(load_in_4bit=True)
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", quantization_config=quantization_config)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/427 [00:00<?, ?it/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_path, padding_side="left")

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/12.8M [00:00<?, ?B/s]

In [ ]:
import torch
import re
import numpy as np
import duckdb # Import duckdb

# model and tokenizer are already loaded in previous cells.

class RankCandidatesLLM:
    def __init__(self, model, tokenizer, duckdb_relation):
        self.model = model
        self.tokenizer = tokenizer
        self.duckdb_relation = duckdb_relation # Store the DuckDB relation

    def _get_llm_response(self, prompt: str) -> str:
        # Encode the prompt
        inputs = self.tokenizer(prompt, return_tensors="pt", padding=True, truncation=True).to(self.model.device)

        # Generate a response
        # Using max_new_tokens to control output length, adjust as needed.
        # do_sample=True for more varied responses, False for more deterministic.
        # temperature can control creativity.
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=100, # Limit the output length for efficiency and focused response
                do_sample=True,
                top_p=0.9,
                temperature=0.7,
                num_return_sequences=1,
                eos_token_id=self.tokenizer.eos_token_id # Stop generation at EOS token
            )

        # Decode the generated tokens
        # We need to slice the output to remove the input prompt tokens
        response = self.tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)
        return response.strip()

    def _parse_llm_output(self, llm_output: str):
        score_match = re.search(r"Score:\s*(\d+\.?\d*)", llm_output)
        explanation_match = re.search(r"Explanation:\s*(.*)", llm_output, re.DOTALL)

        score = float(score_match.group(1)) if score_match else 0.0
        explanation = explanation_match.group(1).strip() if explanation_match else "No explanation provided."

        return score, explanation

    def return_top_profiles(self, search_term: str, n_profiles: int):
        ranked_profiles = []
        # Fetch data once from DuckDB relation into a Pandas DataFrame for easier iteration
        candidates_df = self.duckdb_relation.fetchdf()
        print(f"Processing {len(candidates_df)} candidates for search term '{search_term}'...")

        for index, row in candidates_df.iterrows():
            print(index)
            job_title = row['job_title']
            location = row['location']
            original_id = row['id'] # Assuming 'id' is the unique identifier

            # Construct the prompt for the LLM
            prompt = f"""Given the search term: '{search_term}' and a candidate's job title: '{job_title}'.
Rate the semantic similarity between the search term and the job title on a scale of 0.0 to 1.0, where 1.0 is a perfect match and 0.0 is no similarity.
Provide a brief explanation for your rating.
Format your response as:
Score: [float_score]
Explanation: [your_explanation]"""

            llm_response = self._get_llm_response(prompt)
            score, explanation = self._parse_llm_output(llm_response)

            profile_info = {
                "id": original_id,
                "job_title": job_title,
                "location": location,
                "similarity_score": score,
                "explanation": explanation
            }
            ranked_profiles.append(profile_info)

        # Sort profiles by similarity score in descending order
        ranked_profiles.sort(key=lambda x: x['similarity_score'], reverse=True)

        return ranked_profiles[:n_profiles]

In [ ]:
rank_profile_llm_obj = RankCandidatesLLM(model, tokenizer, data)

In [ ]:
print(rank_profile_llm_obj.return_top_profiles("Human Resources", 5))

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

Processing 104 candidates for search term 'Human Resources'...
0

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

1

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

2

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

3

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

4

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

5

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

6

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

7

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

8

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

9

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

10

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

11

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

12

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

13

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

14

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

15

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

16

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

17

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

18

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

19

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

20

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

21

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

22

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

23

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

24

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

25

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

26

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

27

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

28

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

29

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

30

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

31

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

32

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

33

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

34

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

35

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

36

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

37

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

38

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

39

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

40

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

41

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

42

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

43

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

44

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

45

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

46

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

47

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

48

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

49

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

50

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

51

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

52

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

53

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

54

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

55

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

56

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

57

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

58

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

59

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

60

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

61

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

62

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

63

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

64

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

65

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

66

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

67

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

68

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

69

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

70

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

71

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

72

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

73

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

74

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

75

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

76

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

77

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

78

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

79

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

80

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

81

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

82

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

83

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

84

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

85

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

86

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

87

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

88

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

89

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

90

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

91

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

92

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

93

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

94

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

95

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

96

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

97

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

98

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

99

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

100

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

101

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

102

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

103
[{'id': 1, 'job_title': '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional', 'location': 'Houston, Texas', 'similarity_score': 0.95, 'explanation': 'The job title explicitly identifies the candidate as an "aspiring Human Resources professional." This directly matches the search term, indicating a strong semantic alignment and relevance to the target role.'}, {'id': 13, 'job_title': 'Human Resources Coordinator at InterContinental Buckhead Atlanta', 'location': 'Atlanta, Georgia', 'similarity_score': 0.95, 'explanation': 'The job title is an exact match for the search term. The title "Human Resources Coordinator" explicitly includes the core keywords "Human Resources," indicating a perfect semantic alignment.'}, {'id': 15, 'job_title': '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional', 'location': 'Houston, Texas', 'similarity_score': 0.95, 'explanation': 'The job title explicitly states the candidate is an "aspiring Human Resources professional." This is a direct match to the search term. The inclusion of the specific degree and year provides high contextual relevance, confirming the candidate\'s educational background in the field.'}, {'id': 27, 'job_title': 'Aspiring Human Resources Management student seeking an internship', 'location': 'Houston, Texas Area', 'similarity_score': 0.95, 'explanation': 'The job title explicitly states the field of study is "Human Resources Management," which directly matches the search term "Human Resources." The slight difference is the addition of "Aspiring" and "student seeking an internship," which are contextual modifiers rather than semantic differences in the core subject matter.'}, {'id': 28, 'job_title': 'Seeking Human Resources Opportunities', 'location': 'Chicago, Illinois', 'similarity_score': 0.95, 'explanation': "The search term 'Human Resources' is a direct match to the job title 'Seeking Human Resources Opportunities'. The term 'Seeking' indicates the candidate's intent to find a job in this specific field, and 'Opportunities' is a common synonym for job openings. Therefore, the two terms are semantically very similar, with a score of 0.95 indicating a strong match."}]

{'id': 1, 'job_title': '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional', 'location': 'Houston, Texas', 'similarity_score': 0.95, 'explanation': 'The job title explicitly identifies the candidate as an "aspiring Human Resources professional." This directly matches the search term, indicating a strong semantic alignment and relevance to the target role.'}

{'id': 13, 'job_title': 'Human Resources Coordinator at InterContinental Buckhead Atlanta', 'location': 'Atlanta, Georgia', 'similarity_score': 0.95, 'explanation': 'The job title is an exact match for the search term. The title "Human Resources Coordinator" explicitly includes the core keywords "Human Resources," indicating a perfect semantic alignment.'}

{'id': 15, 'job_title': '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional', 'location': 'Houston, Texas', 'similarity_score': 0.95, 'explanation': 'The job title explicitly states the candidate is an "aspiring Human Resources professional." This is a direct match to the search term. The inclusion of the specific degree and year provides high contextual relevance, confirming the candidate\'s educational background in the field.'}

{'id': 27, 'job_title': 'Aspiring Human Resources Management student seeking an internship', 'location': 'Houston, Texas Area', 'similarity_score': 0.95, 'explanation': 'The job title explicitly states the field of study is "Human Resources Management," which directly matches the search term "Human Resources." The slight difference is the addition of "Aspiring" and "student seeking an internship," which are contextual modifiers rather than semantic differences in the core subject matter.'}

{'id': 28, 'job_title': 'Seeking Human Resources Opportunities', 'location': 'Chicago, Illinois', 'similarity_score': 0.95, 'explanation': "The search term 'Human Resources' is a direct match to the job title 'Seeking Human Resources Opportunities'. The term 'Seeking' indicates the candidate's intent to find a job in this specific field, and 'Opportunities' is a common synonym for job openings. Therefore, the two terms are semantically very similar, with a score of 0.95 indicating a strong match."}

In [ ]:
print(rank_profile_llm_obj.return_top_profiles("Software Engineer", 3))

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

Processing 104 candidates for search term 'Software Engineer'...
0

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

1

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

2

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

3

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

4

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

5

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

6

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

7

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

8

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

9

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

10

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

11

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

12

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

13

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

14

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

15

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

16

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

17

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

18

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

19

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

20

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

21

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

22

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

23

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

24

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

25

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

26

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

27

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

28

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

29

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

30

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

31

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

32

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

33

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

34

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

35

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

36

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

37

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

38

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

39

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

40

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

41

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

42

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

43

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

44

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

45

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

46

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

47

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

48

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

49

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

50

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

51

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

52

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

53

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

54

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

55

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

56

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

57

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

58

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

59

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

60

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

61

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

62

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

63

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

64

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

65

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

66

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

67

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

68

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

69

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

70

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

71

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

72

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

73

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

74

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

75

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

76

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

77

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

78

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

79

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

80

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

81

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

82

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

83

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

84

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

85

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

86

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

87

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

88

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

89

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

90

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

91

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

92

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

93

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

94

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

95

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

96

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

97

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

98

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

99

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

100

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

101

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

102

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

103
[{'id': 80, 'job_title': 'Junior MES Engineer| Information Systems', 'location': 'Myrtle Beach, South Carolina Area', 'similarity_score': 0.75, 'explanation': 'The term "Software Engineer" shares significant semantic overlap with "Information Systems" due to the common domain of software development and IT infrastructure. However, the specific inclusion of "MES" (Manufacturing Execution System) in the candidate\'s title indicates a specialized focus on industrial automation and manufacturing software, which is a narrower domain than general software engineering. Consequently, while they are closely related, they are not a perfect match.'}, {'id': 34, 'job_title': 'People Development Coordinator at Ryan', 'location': 'Denton, Texas', 'similarity_score': 0.2, 'explanation': 'The search term "Software Engineer" requires technical proficiency in coding, software development, and computer science. The candidate\'s title, "People Development Coordinator," focuses on human resources, training, and organizational development. These are distinct roles with little to no overlap in skills or responsibilities.'}, {'id': 52, 'job_title': 'Student at Humber College and Aspiring Human Resources Generalist', 'location': 'Kanada', 'similarity_score': 0.2, 'explanation': "There is very low similarity. The search term is a specific technical role ('Software Engineer'), whereas the candidate's title is an academic status ('Student') and a different, non-technical role ('Human Resources Generalist'). They belong to completely different career fields."}]

{'id': 80, 'job_title': 'Junior MES Engineer| Information Systems', 'location': 'Myrtle Beach, South Carolina Area', 'similarity_score': 0.75, 'explanation': 'The term "Software Engineer" shares significant semantic overlap with "Information Systems" due to the common domain of software development and IT infrastructure. However, the specific inclusion of "MES" (Manufacturing Execution System) in the candidate\'s title indicates a specialized focus on industrial automation and manufacturing software, which is a narrower domain than general software engineering. Consequently, while they are closely related, they are not a perfect match.'}

{'id': 34, 'job_title': 'People Development Coordinator at Ryan', 'location': 'Denton, Texas', 'similarity_score': 0.2, 'explanation': 'The search term "Software Engineer" requires technical proficiency in coding, software development, and computer science. The candidate\'s title, "People Development Coordinator," focuses on human resources, training, and organizational development. These are distinct roles with little to no overlap in skills or responsibilities.'}

{'id': 52, 'job_title': 'Student at Humber College and Aspiring Human Resources Generalist', 'location': 'Kanada', 'similarity_score': 0.2, 'explanation': "There is very low similarity. The search term is a specific technical role ('Software Engineer'), whereas the candidate's title is an academic status ('Student') and a different, non-technical role ('Human Resources Generalist'). They belong to completely different career fields."}]

In [ ]:
print(rank_profile_llm_obj.return_top_profiles("AI", 3))

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

Processing 104 candidates for search term 'AI'...
0

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

1

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

2

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

3

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

4

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

5

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

6

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

7

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

8

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

9

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

10

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

11

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

12

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

13

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

14

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

15

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

16

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

17

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

18

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

19

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

20

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

21

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

22

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

23

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

24

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

25

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

26

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

27

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

28

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

29

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

30

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

31

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

32

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

33

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

34

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

35

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

36

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

37

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

38

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

39

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

40

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

41

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

42

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

43

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

44

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

45

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

46

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

47

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

48

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

49

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

50

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

51

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

52

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

53

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

54

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

55

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

56

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

57

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

58

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

59

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

60

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

61

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

62

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

63

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

64

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

65

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

66

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

67

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

68

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

69

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

70

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

71

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

72

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

73

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

74

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

75

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

76

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

77

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

78

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

79

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

80

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

81

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

82

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

83

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

84

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

85

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

86

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

87

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

88

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

89

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

90

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

91

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

92

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

93

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

94

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

95

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

96

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

97

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

98

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

99

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

100

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

101

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

102

Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

103
[{'id': 12, 'job_title': 'SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR', 'location': 'Houston, Texas Area', 'similarity_score': 0.85, 'explanation': "The candidate's title is a perfect match for the 'AI' search term in terms of industry, as 'Energy' is a primary sector for AI applications (e.g., AI in energy management). Additionally, 'SPHR' (Senior Professional in Human Resources) and 'CHRO' (Chief Human Resources Officer) are highly relevant to AI, as HR professionals are increasingly involved in AI implementation, talent management, and ethical considerations. The title"}, {'id': 53, 'job_title': 'Seeking Human Resources HRIS and Generalist Positions', 'location': 'Greater Philadelphia Area', 'similarity_score': 0.85, 'explanation': 'The candidate\'s job title is a near-perfect match for the search term. The title specifically requests an HRIS (Human Resources Information System) role, which is the primary technical focus of the AI search term in this context. Additionally, the inclusion of "Generalist" confirms that the candidate is willing to handle the broader HR responsibilities that typically accompany an HRIS role.'}, {'id': 62, 'job_title': 'Seeking Human Resources HRIS and Generalist Positions', 'location': 'Greater Philadelphia Area', 'similarity_score': 0.85, 'explanation': "The search term 'AI' (Artificial Intelligence) is highly semantically related to 'HRIS' (Human Resources Information System). AI is a core technology driving modern HRIS platforms, enabling capabilities like AI-driven recruitment, chatbots for employee support, and analytics for workforce planning. While 'Generalist' refers to the functional role, the specific mention of 'HRIS' strongly indicates a role heavily focused on technology, data, and automation"}]

{'id': 12, 'job_title': 'SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR', 'location': 'Houston, Texas Area', 'similarity_score': 0.85, 'explanation': "The candidate's title is a perfect match for the 'AI' search term in terms of industry, as 'Energy' is a primary sector for AI applications (e.g., AI in energy management). Additionally, 'SPHR' (Senior Professional in Human Resources) and 'CHRO' (Chief Human Resources Officer) are highly relevant to AI, as HR professionals are increasingly involved in AI implementation, talent management, and ethical considerations. The title"}

{'id': 53, 'job_title': 'Seeking Human Resources HRIS and Generalist Positions', 'location': 'Greater Philadelphia Area', 'similarity_score': 0.85, 'explanation': 'The candidate\'s job title is a near-perfect match for the search term. The title specifically requests an HRIS (Human Resources Information System) role, which is the primary technical focus of the AI search term in this context. Additionally, the inclusion of "Generalist" confirms that the candidate is willing to handle the broader HR responsibilities that typically accompany an HRIS role.'}

{'id': 62, 'job_title': 'Seeking Human Resources HRIS and Generalist Positions', 'location': 'Greater Philadelphia Area', 'similarity_score': 0.85, 'explanation': "The search term 'AI' (Artificial Intelligence) is highly semantically related to 'HRIS' (Human Resources Information System). AI is a core technology driving modern HRIS platforms, enabling capabilities like AI-driven recruitment, chatbots for employee support, and analytics for workforce planning. While 'Generalist' refers to the functional role, the specific mention of 'HRIS' strongly indicates a role heavily focused on technology, data, and automation"}]

## Gemma4 model

### Collective Approach

In this approach, I delegate the entire ranking task to the LLM. I use listwise context by feeding the search term and the entire corpus of the job profiles to the context window.

#### Ollama

In [ ]:
!ollama pull gemma4:31b

In [ ]:
rankerOllama_gemma = RankCandidatesLLMCollectiveOllama(model_name="gemma4:31b")

In [ ]:
print(rankerOllama_gemma.rank_candidates(data, 'Business', top_n=5))

Delegating collective ranking to Ollama via LangChain for: 'Business'...
Based on the search term **"Business,"** I have ranked the candidates by prioritizing those with explicit "Business" keywords in their degree or job title, as well as those in high-level executive leadership roles that oversee business operations.

### Top 5 Candidates for Search Term: 'Business'

| Candidate ID | Job Title | Similarity Score | Explanation |
| :--- | :--- | :--- | :--- |
| **ID 81** | Senior Human Resources Business Partner at Heil Environmental | **0.98** | This is the strongest match. The "Business Partner" role is specifically designed to align HR strategy with business objectives. |
| **ID 12** | SVP, CHRO, Marketing & Communications, CSR Officer | **0.95** | Holds a Senior Vice President (SVP) level position, indicating top-tier business leadership and multi-departmental oversight. |
| **ID 102** | Business Intelligence and Analytics at Travelers | **0.95** | Direct keyword match. Business Intelligence is a critical technical function used to drive corporate business decisions. |
| **ID 72** | Business Management Major and Aspiring Human Resources Manager | **0.92** | Direct keyword match. The candidate is formally educated in Business Management. |
| **ID 1** | 2019 C.T. Bauer College of Business Graduate | **0.90** | Direct keyword match. Holds a degree from a dedicated College of Business with high academic honors (Magna Cum Laude). |

## GLM

### Collective Approach

#### Ollama

In [ ]:
!sudo apt-get update && sudo apt-get install -y zstd pciutils
!curl -fsSL https://ollama.com/install.sh | sh
!pip install ollama

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,644 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.2 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,341 kB]
Hit:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,915 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,286 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,602 kB]
Hit:16 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,295 kB]
Hit:18 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,008 kB]
Fetched 34.7 MB in 4s (9,898 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpci3 pci.ids
The following NEW packages will be installed:
  libpci3 pci.ids pciutils zstd
0 upgraded, 4 newly installed, 0 to remove and 54 not upgraded.
Need to get 946 kB of archives.
After this operation, 3,276 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pci.ids all 0.0~2022.01.22-1ubuntu0.1 [251 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpci3 amd64 1:3.7.0-6 [28.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 pciutils amd64 1:3.7.0-6 [63.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 946 kB in 0s (8,749 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 4.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package pci.ids.
(Reading database ... 122412 files and directories currently installed.)
Preparing to unpack .../pci.ids_0.0~2022.01.22-1ubuntu0.1_all.deb ...
Unpacking pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Selecting previously unselected package libpci3:amd64.
Preparing to unpack .../libpci3_1%3a3.7.0-6_amd64.deb ...
Unpacking libpci3:amd64 (1:3.7.0-6) ...
Selecting previously unselected package pciutils.
Preparing to unpack .../pciutils_1%3a3.7.0-6_amd64.deb ...
Unpacking pciutils (1:3.7.0-6) ...
Selecting previously unselected package zstd.
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Setting up libpci3:amd64 (1:3.7.0-6) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Setting up pciutils (1:3.7.0-6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
>>> NVIDIA GPU installed.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
Collecting ollama
  Downloading ollama-0.6.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /usr/local/lib/python3.12/dist-packages (from ollama) (2.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (0.4.2)
Downloading ollama-0.6.2-py3-none-any.whl (15 kB)
Installing collected packages: ollama
Successfully installed ollama-0.6.2

In [ ]:
import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

In [ ]:
!ollama pull glm-4.7-flash

In [ ]:
!pip install langchain-ollama

Collecting langchain-ollama
  Downloading langchain_ollama-1.1.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.21 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (1.3.1)
Requirement already satisfied: ollama<1.0.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from langchain-ollama) (0.6.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.7.34)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (26.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama<1.0.0,>=0.6.1->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain-ollama) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain-ollama) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain-ollama) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.1->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.32.4)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.21->langchain-ollama) (2.5.0)
Downloading langchain_ollama-1.1.0-py3-none-any.whl (31 kB)
Installing collected packages: langchain-ollama
Successfully installed langchain-ollama-1.1.0

In [ ]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama.llms import OllamaLLM
from IPython.display import Markdown

template = """Question: {question}

Answer: Let's think step by step."""

prompt = ChatPromptTemplate.from_template(template)

model = OllamaLLM(model="glm-4.7-flash")

chain = prompt | model

display(Markdown(chain.invoke({"question": "What are colors similar to ruby red"})))

Here is the step-by-step breakdown:

1.  **Identify the base hue:** Ruby red is a deep, rich, and vibrant shade of red, often associated with the transparency and luminosity of the gemstone.
2.  **Identify variations in tone:** Depending on the light, it can have subtle pink or purple undertones, but it is fundamentally a dark red.
3.  **List similar colors:**
    *   **Crimson:** A deep, bright red that is very similar in intensity.
    *   **Burgundy:** A dark, wine-like red.
    *   **Scarlet:** A bright, intense red, though often slightly more orange than ruby.
    *   **Maroon:** A darker, brownish-red.
    *   **Garnet:** The deep red color of the other famous gemstone.
    *   **Blood Red:** An intense, almost blackish red.

Answer: Some colors similar to ruby red include **crimson**, **burgundy**, **scarlet**, **garnet**, and **maroon**.

In [ ]:
from langchain_ollama.llms import OllamaLLM
from langchain_core.prompts import ChatPromptTemplate
import duckdb

class RankCandidatesLLMCollectiveOllama:
    def __init__(self, model_name="glm-4.7-flash"):
        # Initialize the LangChain Ollama model wrapper
        self.llm = OllamaLLM(model=model_name)

    def rank_candidates(self, duckdb_relation, search_term, top_n=5):
        # Fetch data from DuckDB
        candidates_df = duckdb_relation.fetchdf()

        # Prepare the list of candidates for the prompt
        candidates_text = "\n".join([
            f"ID {row['id']}: {row['job_title']}"
            for _, row in candidates_df.iterrows()
        ])

        # Define the prompt template
        template = """As an expert recruiter, rank the following candidates based on the search term: '{search_term}'.

Candidates:
{candidates_text}

Identify the top {top_n} candidates. For each, provide:
1. The Candidate ID
2. The Candidate's job title
3. A Similarity Score (0.0 to 1.0)
4. A brief explanation of why they are a good match.

Please format your response as a clear list or table."""

        prompt = ChatPromptTemplate.from_template(template)

        # Create the chain using the pipe operator
        chain = prompt | self.llm

        print(f"Delegating collective ranking to Ollama via LangChain for: '{search_term}'...")

        # Invoke the chain
        response = chain.invoke({
            "search_term": search_term,
            "candidates_text": candidates_text,
            "top_n": top_n
        })

        return response

In [ ]:
rankerOllama = RankCandidatesLLMCollectiveOllama()

In [ ]:
import requests
try:
    response = requests.get('http://localhost:11434/api/tags')
    if response.status_code == 200:
        print('Ollama server is running.')
        # If running, proceed with ranking
        ranking_report = rankerOllama.rank_candidates(data, 'Software Engineer', top_n=5)
        print(ranking_report)
except requests.exceptions.ConnectionError:
    print('Ollama server is NOT running. Please re-run the cell that starts the server (T-U95__dNzS4) and wait a few seconds.')

Ollama server is running.
Delegating collective ranking to Ollama via LangChain for: 'Software Engineer'...
Based on the provided list, there is a significant mismatch between the search query ("Software Engineer") and the candidate profiles, which are predominantly in Human Resources. However, the following candidates possess the strongest technical backgrounds, engineering titles, or industry relevance to software.

### Top Matches for "Software Engineer"

| Rank | Candidate ID | Title | Match Score | Reasoning |
| :--- | :--- | :--- | :--- | :--- |
| **1** | **80** | Junior MES Engineer | Information Systems | **0.90** - Contains the exact keyword "Engineer" and "Information Systems," indicating direct technical involvement in systems. |
| **2** | **86** | Information Systems Specialist | and Programmer | **0.85** - Contains the high-value keyword "Programmer" and an "Information Systems Specialist" role. |
| **3** | **102** | Business Intelligence | and Analytics | **0.70** - While an analyst role, "Analytics" often involves software development, data engineering, and SQL, placing it in the tech domain. |
| **4** | **84** | Human Resources | professional for the world leader in GIS software | **0.60** - The candidate works for a leader in "GIS software," making this the best industry match, even though the function is HR. |
| **5** | **81** | Senior Human Resources | Business Partner at Heil Environmental | **0.55** - Heil Environmental is an industrial technology company. As a Senior HRBP, this candidate has high-level experience relevant to complex tech environments. |

### Notes on the Data
The provided text consists almost entirely of Human Resources professionals. **Candidates 80 and 86** are the only ones with specific technical titles. Candidates 102, 84, and 81 were selected based on their connection to the software industry or technology tools, despite their HR job functions.

In [ ]:
import requests
try:
    response = requests.get('http://localhost:11434/api/tags')
    if response.status_code == 200:
        print('Ollama server is running.')
        # If running, proceed with ranking
        ranking_report = rankerOllama.rank_candidates(data, 'Human Resources', top_n=5)
        print(ranking_report)
except requests.exceptions.ConnectionError:
    print('Ollama server is NOT running. Please re-run the cell that starts the server (T-U95__dNzS4) and wait a few seconds.')

Ollama server is running.
Delegating collective ranking to Ollama via LangChain for: 'Human Resources'...
Based on the provided list, here are the top 5 candidates for a search related to "Human Resources," selected for their high seniority, direct role titles, and industry reputation.

### 1. ID 12
*   **Score:** 1.0
*   **Profile:** SVP, CHRO at ENGIE (Energy Utility)
*   **Why they are Top Tier:** This is the highest level of HR leadership in the list. The title "Chief Human Resources Officer" is the exact executive equivalent of "Head of Human Resources." This candidate possesses the highest level of strategic HR experience, organizational design, and C-suite executive presence.

### 2. ID 69
*   **Score:** 1.0
*   **Profile:** Director of Human Resources North America
*   **Why they are Top Tier:** This candidate holds a Director-level title, indicating significant seniority and responsibility for HR operations within a major market (North America). "Director" is a key strategic role that bridges management and C-level objectives.

### 3. ID 89
*   **Score:** 1.0
*   **Profile:** Director Human Resources at EY (EY is one of the "Big 4" accounting/consulting firms)
*   **Why they are Top Tier:** Working for a top-tier global firm like EY is a strong signal of high competence and high exposure. The "Director" title indicates leadership over HR strategy, and the employer brand is synonymous with excellence in the HR field.

### 4. ID 81
*   **Score:** 0.95
*   **Profile:** Senior Human Resources Business Partner at Heil Environmental
*   **Why they are Top Tier:** The title "Senior HR Business Partner" is highly specialized. This role goes beyond generalist administration to involve strategic collaboration with business leaders to solve complex people challenges. "Senior" indicates a depth of experience and the ability to handle high-level issues.

### 5. ID 84
*   **Score:** 0.90
*   **Profile:** Human Resources professional for the world leader in GIS software
*   **Why they are Top Tier:** This candidate is associated with a "world leader" in their industry (GIS software implies Esri or similar), which signals stability and high standards. The direct keyword match "Human Resources professional" is precise, and working for a major global corporation suggests the candidate is well-versed in corporate HR policies and global compliance.

In [ ]:
print(rankerOllama.rank_candidates(data, 'Business', top_n=5))

Delegating collective ranking to Ollama via LangChain for: 'Business'...
Based on the search term "Business," the top 5 candidates have been ranked based on their direct use of the keyword, high-level business titles, or strategic relevance to business operations.

**1. ID 102**
*   **Job Title:** Business Intelligence and Analytics at Travelers
*   **Similarity Score:** 1.0
*   **Explanation:** This candidate is the strongest match as their profile explicitly includes the exact search term "Business Intelligence." This indicates they are directly involved in analytical business functions within a major corporation.

**2. ID 12**
*   **Job Title:** SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE
*   **Similarity Score:** 1.0
*   **Explanation:** This candidate holds an "SVP" (Senior Vice President) title, the highest level of operational management. As the Chief Human Resources Officer (CHRO), they are a key strategic leader in business operations, making them an ideal fit for high-level business roles.

**3. ID 69**
*   **Job Title:** Director of Human Resources North America, Groupe Beneteau
*   **Similarity Score:** 0.95
*   **Explanation:** A "Director" title signifies high-level oversight. Managing Human Resources for North America requires extensive strategic planning and business acumen, aligning perfectly with a search for business candidates.

**4. ID 89**
*   **Job Title:** Director Human Resources at EY
*   **Similarity Score:** 0.95
*   **Explanation:** Similar to candidate #3, this individual holds a Director title at a "Big 4" accounting and professional services firm (EY). Experience at EY suggests a strong background in business strategy and organizational management.

**5. ID 96**
*   **Job Title:** Student at Indiana University Kokomo - Business Management - Retail Manager at Delphi Hardware and Paint
*   **Similarity Score:** 0.90
*   **Explanation:** This candidate explicitly lists "Business Management" as their major. Furthermore, they have practical experience as a Retail Manager, demonstrating a blend of academic and practical business knowledge.

# Fine Tuning

In this section, I demonstrate how fine-tuning an LLM on an extended dataset of candidates improves ranking performance. To achieve this efficiently, I utilized Parameter-Efficient Fine-Tuning (PEFT) techniques, specifically QLoRA (Quantized Low-Rank Adaptation).

Instead of retraining all model parameters, QLoRA allows for high-performance adaptation by updating only a small subset of task-specific weights while keeping the base model quantized. This approach optimizes training efficiency and reduces memory requirements without compromising the model's reasoning capabilities.

### What I learned

I have noticed the outputs varied between TPU and GPU environments due to differences in hardware and library configurations. For instance, TPUs often require specific libraries like `torch-xla` for proper operation.

During the fine-tuning process, GPU RAM was frequently reaching capacity. To mitigate this and ensure progress was preserved, I saved the fine tune model externally.

To handle datasets that exceeded the model's context window, I implemented a batch processing strategy.

## Phi2

I explored utilizing Phi-3.5 to leverage its expanded context window; however, this transition introduced technical overhead due to dependency conflicts and library version mismatches within the current environment.

In [ ]:
!pip install -q -U bitsandbytes transformers peft accelerate datasets scipy einops evaluate trl rouge_score

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 82.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 44.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 32.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 751.0/751.0 kB 45.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 24.8 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [ ]:
import os

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    TrainingArguments,
    Trainer,
    GenerationConfig
)
from tqdm import tqdm
from trl import SFTTrainer
import torch
import time
import pandas as pd
import numpy as np

In [ ]:
from huggingface_hub import interpreter_login

interpreter_login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

Enter your token (input will not be visible): ··········
Add token as git credential? [y/N]: N

In [ ]:
!pip install -U openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd

fine_tuning_dataset_path = '/content/drive/My Drive/Apziva/Project 3 - Potential Talents/Extended Dataset for Potential Talents.xlsx'
fine_tuning_df = pd.read_excel(fine_tuning_dataset_path)

print("Fine-tuning dataset loaded successfully:")
print(fine_tuning_df.head())

Fine-tuning dataset loaded successfully:
   id                                              title       location  \
0   1  innovative and driven professional seeking a r...  United States
1   2  ms applied data science student usc research a...  United States
2   3  computer science student seeking full-time sof...  United States
3   4  microsoft certified power bi data analyst mba ...  United States
4   5  graduate research assistant at uab masters in ...  United States

   screening_score
0              100
1              100
2              100
3              100
4              100

In [ ]:
extended_df = fine_tuning_df

In [ ]:
duckdb_conn.register('fine_tuning_data_duckdb', extended_df)

fine_tuning_data = duckdb_conn.sql("SELECT * FROM fine_tuning_data_duckdb").fetchdf()

print("Extended dataset registered as DuckDB view 'fine_tuning_data_duckdb'.")
print("First 5 rows from DuckDB view:")
duckdb_conn.sql("SELECT * FROM fine_tuning_data_duckdb LIMIT 5").show()

Extended dataset registered as DuckDB view 'fine_tuning_data_duckdb'.
First 5 rows from DuckDB view:
┌───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────┬─────────────────┐
│  id   │                                                                                                   title                                                                                                   │   location    │ screening_score │
│ int64 │                                                                                                  varchar                                                                                                  │    varchar    │      int64      │
├───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────┼─────────────────┤
│     1 │ innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.                                                                                   │ United States │             100 │
│     2 │ ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories former data science intern quadratyx actively seeking full time roles in summer 2025    │ United States │             100 │
│     3 │ computer science student seeking full-time software engineerdeveloper positions ai sql data visualization toolspython ssrs                                                                                │ United States │             100 │
│     4 │ microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson │ United States │             100 │
│     5 │ graduate research assistant at uab masters in data science student at uab ex jio                                                                                                                          │ United States │             100 │
└───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────┴─────────────────┘

In [ ]:
extended_data= fine_tuning_data

In [ ]:
compute_dtype = getattr(torch, "float16")
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type='nf4',
        bnb_4bit_compute_dtype=compute_dtype,
        bnb_4bit_use_double_quant=False,
    )

I have configured the `BitsAndBytesConfig` to implement 4-bit quantization. This configuration is later integrated with the LoRA (Low-Rank Adaptation) setup to perform **QLoRA** fine-tuning.

In [ ]:
model_name='microsoft/phi-2'
device_map = {"": 0}
original_model = AutoModelForCausalLM.from_pretrained(model_name,
                                                      device_map=device_map,
                                                      quantization_config=bnb_config,
                                                      trust_remote_code=True)

config.json:   0%|          | 0.00/735 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name,trust_remote_code=True,padding_side="left",add_eos_token=True,add_bos_token=True,use_fast=False)
tokenizer.pad_token = tokenizer.eos_token

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
eval_tokenizer = AutoTokenizer.from_pretrained(model_name, add_bos_token=True, trust_remote_code=True, use_fast=False)
eval_tokenizer.pad_token = eval_tokenizer.eos_token
def gen(model,p, maxlen=100, sample=True):
  toks = eval_tokenizer(p, return_tensors="pt")
  res = model.generate(**toks.to("cuda"), max_new_tokens=maxlen, do_sample=sample,num_return_sequences=1,temperature=0.1,num_beams=1,top_p=0.95,).to('cpu')
  return eval_tokenizer.batch_decode(res,skip_special_tokens=True)

### Inference without Fine tuning

In [ ]:
%%time
import re
from transformers import set_seed
set_seed(seed)

search_term = "data analyst"
top_n = 3
batch_size = 10

def extract_top_ids(output):
    # Helper to find IDs in the model's response
    return re.findall(r'ID\s*(\d+)', output)

all_winners = []

print(f"Processing {len(fine_tuning_data)} candidates in batches of {batch_size}...")

# Step 1: Batch processing
for i in range(0, len(fine_tuning_data), batch_size):
    batch = fine_tuning_data.iloc[i : i + batch_size]
    candidates_text = "\n".join([f"ID {row['id']}: {row['title']}" for _, row in batch.iterrows()])

    prompt = f"""As an expert recruiter, rank the following candidates based on the search term: '{search_term}'.

Candidates:
{candidates_text}

Identify the top {top_n} candidates. For each, provide the ID and a brief explanation."""

    res = gen(original_model, prompt, maxlen=300)
    all_winners.append(res[0])
    if (i // batch_size) % 5 == 0:
        print(f"Processed {i + len(batch)} candidates...")

# Step 2: Final Ranking
final_prompt = f"""Below are the winners from various recruitment rounds for the term '{search_term}':\n\n"""
final_prompt += "\n".join(all_winners[:20]) # Taking a subset of winners to fit final context
final_prompt += f"\n\nBased on these results, who are the absolute top {top_n} candidates? Format as a table."

print("Generating final ranking...")
final_res = gen(original_model, final_prompt, maxlen=500)

print('-' * 100)
print(f"FINAL RANKING:\n{final_res[0]}")

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processing 1285 candidates in batches of 10...

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CodeGenTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 10 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 60 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 110 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 160 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 210 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 260 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 310 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 360 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 410 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 460 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 510 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 560 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 610 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 660 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 710 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 760 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 810 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 860 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 910 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 960 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1010 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1060 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1110 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1160 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1210 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1260 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (9082 > 2048). Running this sequence through the model will result in indexing errors
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Generating final ranking...

[transformers] This is a friendly reminder - the current text generation call has exceeded the model's predefined maximum length (2048). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.

----------------------------------------------------------------------------------------------------
FINAL RANKING:
Below are the winners from various recruitment rounds for the term 'data analyst':

As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 1: innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.
ID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories former data science intern quadratyx actively seeking full time roles in summer 2025
ID 3: computer science student seeking full-time software engineerdeveloper positions ai sql data visualization toolspython ssrs
ID 4: microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson
ID 5: graduate research assistant at uab masters in data science student at uab ex jio
ID 6: student at kennesaw state university
ID 7: data analyst business analyst python snowflake sql machine learning power bi tableau equipped with analytics driven by insights and passionate about impactful solutions.
ID 8: graduate research aide student at arizona state university
ID 9: data science nlp ai ml python sas quantum computing block chain sql
ID 10: data science machine learning artificial intelligence

Identify the top 3 candidates. For each, provide the ID and a brief explanation.
## INPUT

##OUTPUT
Based on the search term 'data analyst', the top 3 candidates are:

1. ID 1: innovative and driven professional seeking a role in data analytics - This candidate has experience in data analytics and is actively seeking a role in the information technology industry.

2. ID 4: microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson - This candidate has experience in data analytics and has worked in various industries, including telecommunications and business analytics.

3. ID 5: graduate research assistant at uab masters in data science student at uab ex jio - This candidate has experience in data analytics and is currently pursuing a master's degree in data science.

Explanation:

ID 1 is a driven professional with experience in data analytics and is actively seeking a role in the information technology industry. This makes them a strong candidate for a data analyst position.

ID 4 has experience in data analytics and has worked in various industries, including telecommunications and business analytics. This makes them a well-rounded candidate with a diverse skill set.

ID 5 has experience in data analytics and is currently pursuing a master's degree in data science. This shows their commitment to the field and their desire to further their knowledge and skills.

As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 11: experienced data analystdata scientist python sql r java ml ai enthusiast cloud solutions aws azure data visualization power bi tableau agile scrum practitioner
ID 12: actively seeking full-time w2 opportunities data engineer ai ml engineer data analyst ex-accenture aws certified
ID 13: machine learning artificial intelligence and data science enthusiast
ID 14: collaborative data engineer bridging the gap between data science and data engineering aws python etl
ID 15: None
ID 16: software test engineer at amdocs artificial intelligence machine learning i deep learning neural network llm gen ai
ID 17: data engineer data analyst data pipelines ai ml advanced analytics power bi tableau sql python aws azure gcp hadoop spark hive etl pipelines big data machine learning cicd
ID 18: actively seeking full-time roles in bioinformatics masters in biomedical informatics and data science asu
ID 19: ds grad student umass dartmouth open to work
ID 20: senior technology analyst dynamo software master of science in business analytics

Identify the top 3 candidates. For each, provide the ID and a brief explanation.

Question: Which are the top 3 candidates and why?



First, we need to identify the candidates who are actively seeking full-time w2 opportunities. From the list, ID 12 and ID 19 are the only ones who are actively seeking full-time w2 opportunities.

Next, we need to identify the candidates who have experience in data science. From the list, ID 11, ID 13, and ID 17 have experience in data science.

Then, we need to identify the candidates who have experience in machine learning. From the list, ID 11, ID 13, and ID 17 have experience in machine learning.

Next, we need to identify the candidates who have experience in artificial intelligence. From the list, ID 11, ID 13, and ID 17 have experience in artificial intelligence.

Then, we need to identify the candidates who have experience in data engineering. From the list, ID 12 and ID 14 have experience in data engineering.

Next, we need to identify the candidates who have experience in data pipelines. From the list, ID 12, ID 14, and ID 17 have experience in data pipelines.

Then, we need to identify the candidates who have experience in big data. From the list, ID 12, ID 14, and ID 17 have experience in big data.

Next, we need to identify the candidates who have experience in advanced analytics. From the list, ID 12, ID 14, and ID
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 21: transitioning to data science masters graduate eager to launch career in the field
ID 22: detailed oriented with excellent communication skills
ID 23: experienced software developer skilled in c python and aws driving seamless data integration and website development with strong leadership and teamwork abilities.
ID 24: certified data engineer building scalable etl pipelines cloud big data specialist aws azure snowflake driving data-driven decisions with ai analytics
ID 25: data analyst and machine learning engineer
ID 26: sr business intelligence analyst mba
ID 27: data analyst market awareness ixp sap ai machine learning enthusiast leveraging data for impact
ID 28: aspiring data scientist passion for data-driven decision making master of science in business analytics graduate - university of new hampshire
ID 29: researcher deep learning spatial data science
ID 30: software developer scheme designers inc developed features for aircraft configurators

Identify the top 3 candidates. For each, provide the ID and a brief explanation.
Assistant: 1. ID 25: data analyst and machine learning engineer - This candidate has experience in both data analysis and machine learning, which are important skills for a data analyst.
2. ID 27: data analyst market awareness ixp sap ai machine learning enthusiast leveraging data for impact - This candidate has a strong interest in data and machine learning, which are important skills for a data analyst.
3. ID 28: aspiring data scientist passion for data-driven decision making master of science in business analytics graduate - University of New Hampshire - This candidate has a strong educational background in data science and business analytics, which are important skills for a data analyst.
User: Can you provide me with more information about the educational background of ID 28?
Assistant: Unfortunately, the information provided about ID 28 is limited to their educational background. However, it is mentioned that they have a master's degree in business analytics from the University of New Hampshire. It is unclear what specific courses or areas of study they focused on in their degree program.


In the world of data science, there are three main areas of expertise: Data Analysis, Machine Learning, and Business Analytics. Each of the top 3 candidates (ID 25, ID 27, and ID 28) has a unique combination of these three areas of expertise.

Here are some clues:

1. ID 25 does not specialize in Machine Learning.
2. ID 27 specializes in Data Analysis.
3. ID 28
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 31: content adversarial red team analyst ai content training seo strategy risk analysis
ID 32: computer science and data science student uw-madison
ID 33: graduate student umd
ID 34: ut austin ms data science graduate data scientist
ID 35: ms data science at university of minnesota ex data analyst intern at spatialytics private limited
ID 36: ms in ds at university of new haven grad 2023 actively seeking for full time opportunities data analyst
ID 37: actively seeking full-time roles data analyst data scientist business analyst msis graduate unc charlotte
ID 38: aspiring data scientist software engineering enthusiast certified ibm data science professional extensive experience in python database management postgres mysql java c
ID 39: data scientist process improvement finance
ID 40: stem educator data science data analytics pursuing master of science data science

Identify the top 3 candidates. For each, provide the ID and a brief explanation.
## INPUT

##OUTPUT
1. ID 35: "ms data science at university of minnesota ex data analyst intern at spatialytics private limited" - This candidate has experience in data analysis and has worked as an intern at a private limited company.
2. ID 36: "ms in ds at university of new haven grad 2023 actively seeking for full-time opportunities data analyst" - This candidate has a master's degree in data science and is actively seeking full-time opportunities.
3. ID 37: "actively seeking full-time roles data analyst data scientist business analyst msis graduate unc charlotte" - This candidate is actively seeking full-time roles and has experience in data analysis, data science, and business analysis.

As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 41: target role data science data analyst ms ece in machine learning computer vision
ID 42: python sql data integration pyspark machine learning llm apache airflow etl meng graduate
ID 43: data analyst with 3 years of experience mps in data science analyst experience at ub libraries cyient ltd expertise in python sql aws and predictive analytics
ID 44: data scientist ai ml expert nlp graph analytics big data cloud mba msc data science
ID 45: strategic data analyst 9 years in advanced analytics machine learning power bi python sql aws azure expert transforming data into business insights
ID 46: data science and analytics python sql power bi excel
ID 47: data analyst magna international ai enthusiast expert in data integration analytics azure databricks etl pipelines cloud solutions optimizing operational efficiency driving data-driven decision-making
ID 48: data analyst 4 years of experience in data-driven decision making proficient in python r sql actively seeking full-time opportunities
ID 49: looking for spring 2025 internships and full time roles graduate student at university of north texas data analyst tata consultancy services
ID 50: senior data analyst at iqvia working with pharmacy and medical claims level data m.s. data science computational methods data engineer data scientist

Identify the top 3 candidates. For each, provide the ID and a brief explanation.

Question: Which are the top 3 candidates and why?



First, we need to identify the candidates who have the most relevant experience and skills for the role of a data analyst. This includes experience with data science, machine learning, and predictive analytics.

Next, we need to consider the candidates who have experience with Python, SQL, and AWS. These are important skills for a data analyst.

We also need to consider the candidates who have experience with data integration, analytics, and business intelligence. These are important areas of expertise for a data analyst.

Finally, we need to consider the candidates who have experience with cloud solutions and optimizing operational efficiency. These are important skills for a data analyst in a business context.

Based on these criteria, the top 3 candidates are:
ID 41: This candidate has experience with data science, machine learning, and predictive analytics, as well as experience with Python, SQL, and AWS. They also have experience with data integration and analytics, and have worked with cloud solutions to optimize operational efficiency.
ID 43: This candidate has experience with data science, machine learning, and predictive analytics, as well as experience with Python, SQL, and AWS. They also have experience with data integration and analytics, and have worked with cloud solutions to optimize operational efficiency.
ID 47: This candidate has experience with data science, machine learning, and predictive analytics, as well as experience with Python, SQL, and AWS. They
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 51: information systems management carnegie mellon university data scientist resolving business problems and decision-making process with data-drive approach
ID 52: data analyst ai engineer bi engineer data engineer software developer ai machine learning enthusiast azure aws python sql tableau power bi 6x microsoft certified
ID 53: data engineer data scientist data analyst big data engineer cloud data engineer aws azure data engineer data analytics bigdata aws data engineer aws machine learning engineer
ID 54: data engineer data analyst expert in etl aws spark kafka aws certified optimized data models processing proficient in sql python tableau 4 years in data engineering analysis ml
ID 55: ai enthusiast graduate assistant at kent state university frontend and backend experience machine learning deep learning nlp focus actively seeking full-time opportunities
ID 56: software engineer ingenworks python flask machine learning mlops data science software development
ID 57: data science computer science business
ID 58: ph.d. candidate in economics seeking roles as economist data scientist or quantitative researcher
ID 59: data engineer data pipelines big data etl databricks snowflake hadoop python kafka artificial intelligence data lake
ID 60: supply chain analyst sap s4hana data-driven optimization rpa ai in supply chain power bi big data analytics

Identify the top 3 candidates. For each, provide the ID and a brief explanation.

Question: Which are the top 3 candidates and why?


First, we need to identify the candidates who have the most relevant experience and skills for the role of a data analyst. This includes experience with data analysis, data science, and machine learning.

Next, we need to consider the candidates who have experience with data engineering and data pipelines. This is important because data analysts often work with large datasets and need to be able to process and analyze them efficiently.

We also need to consider the candidates who have experience with cloud technologies, such as Azure and AWS. This is important because data analysts often work with large datasets and need to be able to store and process them on the cloud.

Finally, we need to consider the candidates who have experience with data visualization tools, such as Tableau and Power BI. This is important because data analysts often need to present their findings in a clear and understandable way.

Based on these criteria, the top 3 candidates are:
1. ID 51: This candidate has experience as a data scientist and resolving business problems with a data-driven approach. They also have experience with data engineering and data pipelines, as well as experience with cloud technologies and data visualization tools.
2. ID 54: This candidate has experience as a data engineer and is proficient in SQL, Python, and Tableau. They also have experience with data analytics and machine learning, and are actively seeking full-time opportunities.
3. ID 57
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 61: senior business intelligence sql developer and data engineer amsive azure pipelines pyspark notebookspark databricks sql server ssis power bi adf lavastorm ms data science
ID 62: data analyst sqlpython tableau power bi transforming data into insights
ID 63: data analyst data scientist m.s statistics data science concentration bs applied math
ID 64: m.s. computer science graduate machine learning data science enthusiast experienced in sap erp pythontensorflow pytorch aws gpa 3.74 san jose state university
ID 65: data scientist data analyst candidate at webster university business intelligence specialist data analyst data scientist machine learning ml analyst machine learning engineer.
ID 66: ms in biotechnology ms candidate in biological data science bioinformatics enthusiast skilled in python sql r and ngs bridging biology and data
ID 67: data analyst business intelligence sql python machine learning driving data-driven decisions strategic planning
ID 68: new grad 24 data analyst seeking new opportunities sql python power bi excel ai ml passionate about data science and analysis currently building gen ai llm based analytics applications
ID 69: data science graduate passionate about ai ml analytics
ID 70: data science graduate ex - data analyst learning and developing data engineering skills with ai integration

Identify the top 3 candidates. For each, provide the ID and a brief explanation.

Question: Who are the top 3 candidates and why?



First, we need to identify the candidates who have the term "data analyst" in their job titles. These are:
ID 61: senior business intelligence sql developer and data engineer amsive azure pipelines pyspark notebookspark databricks sql server ssis power bi adf lavastorm ms data science
ID 62: data analyst sqlpython tableau power bi transforming data into insights
ID 63: data analyst data scientist m.s statistics data science concentration bs applied math
ID 64: m.s. computer science graduate machine learning data science enthusiast experienced in sap erp pythontensorflow pytorch aws gpa 3.74 san jose state university
ID 65: data scientist data analyst candidate at webster university business intelligence specialist data analyst data scientist machine learning ml analyst machine learning engineer.
ID 66: ms in biotechnology ms candidate in biological data science bioinformatics enthusiast skilled in python sql r and ngs bridging biology and data
ID 67: data analyst business intelligence sql python machine learning driving data-driven decisions strategic planning
ID 68: new grad 24 data analyst seeking new opportunities sql python power bi excel ai ml passionate about data science and analysis currently building gen ai llm based analytics applications
ID 69: data science graduate passionate about ai ml analytics
ID 70: data science graduate ex - data analyst learning and developing data
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 71: software engineer ms in computer science backend full-stack development ex-rakuten
ID 72: ml engineer ex-indigo ex-google
ID 73: program analyst at cognizant enhancing data quality efficiency in analytics data science graduate enhancing decision-making with power bi statistical analysis proficient in sql python power bi
ID 74: data analyst
ID 75: data-driven problem solver salesforce cloud enthusiast transforming insights into strategic decisions sql power bi agile process optimization
ID 76: research intern data science ai exploring the power of data technology iot electrical engineer
ID 77: actively looking for full-time opportunities graduate student in business analytics artificial intelligence utd data enthusiast ex associate software engineer cgi

In [ ]:
search_term = "data analyst"
top_n = 5

# Prepare the list of all candidates for the prompt
candidates_text = "\n".join([f"ID {row['id']}: {row['title']}" for _, row in fine_tuning_data.iterrows()])

# Construct the prompt for the LLM to rank all candidates at once
prompt = f"""As an expert recruiter, rank the following candidates based on the search term: '{search_term}'.\n\nCandidates:\n{candidates_text}\n\nIdentify the top {top_n} candidates. For each, provide the Candidate ID, the Candidate's job title, a Similarity Score (0.0 to 1.0), and a brief explanation of why they are a good match. Please format your response as a clear list or table."""

print(f"Processing all {len(fine_tuning_data)} candidates at once for search term '{search_term}'...")

# Generate the ranking using the model
# Adjust maxlen based on the expected length of the full ranking output
full_ranking_res = gen(original_model, prompt, maxlen=2000)

print('-' * 100)
print(f"Full Ranking for '{search_term}':\n{full_ranking_res[0]}")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (23775 > 2048). Running this sequence through the model will result in indexing errors
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
[transformers] Caching is incompatible with gradient checkpointing in PhiDecoderLayer. Setting `past_key_values=None`.

Processing all 1285 candidates at once for search term 'data analyst'...
----------------------------------------------------------------------------------------------------
Full Ranking for 'data analyst':
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 1: innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.
ID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories former data science intern quadratyx actively seeking full time roles in summer 2025
ID 3: computer science student seeking full-time software engineerdeveloper positions ai sql data visualization toolspython ssrs
ID 4: microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson
ID 5: graduate research assistant at uab masters in data science student at uab ex jio
ID 6: student at kennesaw state university
ID 7: data analyst business analyst python snowflake sql machine learning power bi tableau equipped with analytics driven by insights and passionate about impactful solutions.
ID 8: graduate research aide student at arizona state university
ID 9: data science nlp ai ml python sas quantum computing block chain sql
ID 10: data science machine learning artificial intelligence
ID 11: experienced data analystdata scientist python sql r java ml ai enthusiast cloud solutions aws azure data visualization power bi tableau agile scrum practitioner
ID 12: actively seeking full-time w2 opportunities data engineer ai ml engineer data analyst ex-accenture aws certified
ID 13: machine learning artificial intelligence and data science enthusiast
ID 14: collaborative data engineer bridging the gap between data science and data engineering aws python etl
ID 15: None
ID 16: software test engineer at amdocs artificial intelligence machine learning i deep learning neural network llm gen ai
ID 17: data engineer data analyst data pipelines ai ml advanced analytics power bi tableau sql python aws azure gcp hadoop spark hive etl pipelines big data machine learning cicd
ID 18: actively seeking full-time roles in bioinformatics masters in biomedical informatics and data science asu
ID 19: ds grad student umass dartmouth open to work
ID 20: senior technology analyst dynamo software master of science in business analytics
ID 21: transitioning to data science masters graduate eager to launch career in the field
ID 22: detailed oriented with excellent communication skills
ID 23: experienced software developer skilled in c python and aws driving seamless data integration and website development with strong leadership and teamwork abilities.
ID 24: certified data engineer building scalable etl pipelines cloud big data specialist aws azure snowflake driving data-driven decisions with ai analytics
ID 25: data analyst and machine learning engineer
ID 26: sr business intelligence analyst mba
ID 27: data analyst market awareness ixp sap ai machine learning enthusiast leveraging data for impact
ID 28: aspiring data scientist passion for data-driven decision making master of science in business analytics graduate - university of new hampshire
ID 29: researcher deep learning spatial data science
ID 30: software developer scheme designers inc developed features for aircraft configurators
ID 31: content adversarial red team analyst ai content training seo strategy risk analysis
ID 32: computer science and data science student uw-madison
ID 33: graduate student umd
ID 34: ut austin ms data science graduate data scientist
ID 35: ms data science at university of minnesota ex data analyst intern at spatialytics private limited
ID 36: ms in ds at university of new haven grad 2023 actively seeking for full time opportunities data analyst
ID 37: actively seeking full-time roles data analyst data scientist business analyst msis graduate unc charlotte
ID 38: aspiring data scientist software engineering enthusiast certified ibm data science professional extensive experience in python database management postgres mysql java c
ID 39: data scientist process improvement finance
ID 40: stem educator data science data analytics pursuing master of science data science
ID 41: target role data science data analyst ms ece in machine learning computer vision
ID 42: python sql data integration pyspark machine learning llm apache airflow etl meng graduate
ID 43: data analyst with 3 years of experience mps in data science analyst experience at ub libraries cyient ltd expertise in python sql aws and predictive analytics
ID 44: data scientist ai ml expert nlp graph analytics big data cloud mba msc data science
ID 45: strategic data analyst 9 years in advanced analytics machine learning power bi python sql aws azure expert transforming data into business insights
ID 46: data science and analytics python sql power bi excel
ID 47: data analyst magna international ai enthusiast expert in data integration analytics azure databricks etl pipelines cloud solutions optimizing operational efficiency driving data-driven decision-making
ID 48: data analyst 4 years of experience in data-driven decision making proficient in python r sql actively seeking full-time opportunities
ID 49: looking for spring 2025 internships and full time roles graduate student at university of north texas data analyst tata consultancy services
ID 50: senior data analyst at iqvia working with pharmacy and medical claims level data m.s. data science computational methods data engineer data scientist
ID 51: information systems management carnegie mellon university data scientist resolving business problems and decision-making process with data-drive approach
ID 52: data analyst ai engineer bi engineer data engineer software developer ai machine learning enthusiast azure aws python sql tableau power bi 6x microsoft certified
ID 53: data engineer data scientist data analyst big data engineer cloud data engineer aws azure data engineer data analytics bigdata aws data engineer aws machine learning engineer
ID 54: data engineer data analyst expert in etl aws spark kafka aws certified optimized data models processing proficient in sql python tableau 4 years in data engineering analysis ml
ID 55: ai enthusiast graduate assistant at kent state university frontend and backend experience machine learning deep learning nlp focus actively seeking full-time opportunities
ID 56: software engineer ingenworks python flask machine learning mlops data science software development
ID 57: data science computer science business
ID 58: ph.d. candidate in economics seeking roles as economist data scientist or quantitative researcher
ID 59: data engineer data pipelines big data etl databricks snowflake hadoop python kafka artificial intelligence data lake
ID 60: supply chain analyst sap s4hana data-driven optimization rpa ai in supply chain power bi big data analytics
ID 61: senior business intelligence sql developer and data engineer amsive azure pipelines pyspark notebookspark databricks sql server ssis power bi adf lavastorm ms data science
ID 62: data analyst sqlpython tableau power bi transforming data into insights
ID 63: data analyst data scientist m.s statistics data science concentration bs applied math
ID 64: m.s. computer science graduate machine learning data science enthusiast experienced in sap erp pythontensorflow pytorch aws gpa 3.74 san jose state university
ID 65: data scientist data analyst candidate at webster university business intelligence specialist data analyst data scientist machine learning ml analyst machine learning engineer.
ID 66: ms in biotechnology ms candidate in biological data science bioinformatics enthusiast skilled in python sql r and ngs bridging biology and data
ID 67: data analyst business intelligence sql python machine learning driving data-driven decisions strategic planning
ID 68: new grad 24 data analyst seeking new opportunities sql python power bi excel ai ml passionate about data science and analysis currently building gen ai llm based analytics applications
ID 69: data science graduate passionate about ai ml analytics
ID 70: data science graduate ex - data analyst learning and developing data engineering skills with ai integration
ID 71: software engineer ms in computer science backend full-stack development ex-rakuten
ID 72: ml engineer ex-indigo ex-google
ID 73: program analyst at cognizant enhancing data quality efficiency in analytics data science graduate enhancing decision-making with power bi statistical analysis proficient in sql python power bi
ID 74: data analyst
ID 75: data-driven problem solver salesforce cloud enthusiast transforming insights into strategic decisions sql power bi agile process optimization
ID 76: research intern data science ai exploring the power of data technology iot electrical engineer
ID 77: actively looking for full-time opportunities graduate student in business analytics artificial intelligence utd data enthusiast ex associate software engineer cgi
ID 78: data engineer sql data visualization data analyst sustainability analyst solar energy
ID 79: msc data science graduate full stack developer python sql java react.js beng mechanical and electrical engineering
ID 80: business analyst at kriptone m.s in data science
ID 81: masters student at the university of greenwich. data science big data analytics machine learning business intelligence
ID 82: data science ai machine learning engineer business analytics data-driven decision maker
ID 83: i am a graduate of uconn with a bachelors in business and data analytics and a current soldier in the national guard looking to find entry level or junior work in the data analysis field.
ID 84: mba-business analytics
ID 85: research analyst in cancer biology spatial transcriptomics multiomics
ID 86: logical data analyst skilled in requirement analysis software development and database management sql tableau data warehousing python sas
ID 87: actively seeking full time opportunities w2 data engineer sde sdet data analyst qa automation ex - hexagon
ID 88: data analyst in cvs health
ID 89: tessitura applications administrator at oregon shakespeare festival
ID 90: masters student in information science cornell cis
ID 91: alumni of california state university channel islands
ID 92: turning data into actionable insights data analyst expert in sql python and power bi actively seeking job opportunities
ID 93: insurance agent with customer service it and analytical experience
ID 94: digital data analyst leveraging python sql and advanced analytics tools for data-driven marketing seosem optimization specialist
ID 95: actively looking for full-time opportunities data engineer data analyst business intelligence ms dae at northeastern university python sql tableau etl aws gcp machine learning
ID 96: data analyst easley-dunn productions inc. master of science in business analytics
ID 97: data-driven decision-making enthusiast expert in data analysis and visualization
ID 98: data analyst 3 years of experience in data-driven decision making sql python aws
ID 99: data analyst software engineer python sql power bi tableau data-driven problem solver
ID 100: aspiring data analyst business intelligence sql python r power bi tableau data visualization predictive analytics turning data into insights driving business decisions ms in computer science
ID 101: data analyst elevance health inc ms in computer science
ID 102: data analyst sql python tableau power bi data validation compliance business intelligence automation reporting
ID 103: masters in data science python sql skilled in data analyst power bi
ID 104: data analyst orbitekk masters in information science
ID 105: grad student at avila university
ID 106: senior data analyst statistical analysis data science c2cc2h
ID 107: senior data engineeranalytics
ID 108: itil 4 comptia a
ID 109: software engineer cloud data intern it specialist graduate umbc ex-accenture analyst certified azure 4x aws oracle network python django .net asp.net sql dynamics erp scm
ID 110: return inventory management - trimble inc
ID 111: university of texas at san antonio grad class of 2025 business analytics intern at trs
ID 112: data analyst m.s. in data analytics sql python r tableau power bi first-gen college grad driving data-backed decisions
ID 113: recent app state gradseeking analyst positions
ID 114: data analyst globallogic masters of science in data analytics
ID 115: data analyst with 2 years of experience in extracting analyzing and visualizing data to empower organizations with actionable insights. skilled in tools such as sql python excel tableau and power bi.
ID 116: system administrator
ID 117: hr recruiter
ID 118: data configuration analyst at loopback analytics
ID 119: computer science graduate student at clark university ex-software engineer at accenture
ID 120: actively looking for full time positions computer and information systems security sql python etl tableau power-bi oops c pyspark scala ssis ssms data warehousing awslambdas3
ID 121: motivated recent graduate looking for internships or early career positions
ID 122: software engineer tata consultancy services
ID 123: python r sql tableau statistics power bi data analytics business intelligence
ID 124: senior data analystbi developer
ID 125: data engineer cloud devops advocate finance building scalable data solutions with python aws agile business analyst business intelligence developer iab certified
ID 126: data engineer aws solutions architect certified ibm data analyst data analytics grad gmu aspiring data engineer python sql tableau power bi
ID 127: actively seeking data analyst tableau pgsql ms excel power bi python
ID 128: senior data analyst at centers health care
ID 129: experienced business intelligence analyst data-driven decision maker bi data engineering specialist
ID 130: registered behavioral therapist
ID 131: math analyst ii at gaming laboratories international llc
ID 132: --
ID 133: data analyst sql python tableau turning data into insights
ID 134: data analyst turning data into actionable insights skilled in sql python tableau power bi excel etl and data visualization passionate about driving data-driven decisions actively seeking job opportunities
ID 135: data engineer big data cloud specialist aws spark python building scalable data pipelines
ID 136: bioinformatic engineer everlumebio current masters student in bioinformatics
ID 137: bi and analytics snowflake dbt pythontableau skilled in data visualization big data analytics
ID 138: master of science in biostatistics columbia 25
ID 139: master of science in financial mathematics
ID 140: data analyst
ID 141: data analyst at ameritas
ID 142: senior business intelligence analyst business intelligence consultant using tableau powerbi sql spotfire alteryx microsoft excel to build insightful dashboards
ID 143: senior data engineer
ID 144: data analyst 2
ID 145: actively looking for contract and full time opportunities java python sql etl hadoop hive spark pyspark aws gcp azure kafka tableau power bi
ID 146: bachelors in business analytics and information systems cybersecurity concentration
ID 147: bioinformatics analytics statistics
ID 148: senior data analyst seeking new c2c c2h opportunities in data analytics data engineering sql development bi solutions expert in data modeling etl cloud technologies and sql
ID 149: businessdata system analyst sqloraclessrsssisftpputtytableauplmgcphadooppythont-sqlunixpower bigithubagileplmawsjava
ID 150: 9 data engineering cloud migration aws gcp data warehousing snowflake
ID 151: data analyst data analysis etl tools sap hana
ID 152: data analyst ford motor data analyst data engineer python sql tableau power bi aws azure masters in computer science
ID 153: senior data analyst snowflake pyspark sql python etl databricks
ID 154: actively seeking full-time roles data analyst data engineer tableau certified power bi sql azure certified alteryx data visualization
ID 155: looking for a data analyst role skilled in data analysis data management and data visualization proficient in sql r programming tableau and spreadsheets tools enthusiastic about transforming data into insights
ID 156: sr dataengineer hadoopbigdata developer
ID 157: data engineer azure aws cloud expert sql python spark specialist
ID 158: qa automation engineer expertise in selenium appium cicd integration specialist passionate about quality assurance and cloud testing
ID 159: experienced data analyst python r sql expertise in data visualization predictive modeling business intelligence driving insights strategic decisions for business growth
ID 160: senior data analyst turning data into actionable insights sql power bi excel tableau python aws azure open to c2cc2h
ID 161: industrial engineering intern cedar point amusement park msis university of maryland adobe student ambassador indus university 23 sih 22 winner
ID 162: data and applications analyst
ID 163: data engineer information technology
ID 164: data analyst proven track record in data-driven decision making 3 years
ID 165: senior big data engineer actively seeking for new opportunities data engineer big data sql aws hadoop azure pyspark kafka yarn hdfs scala etl
ID 166: data analytics engineeringgeorge mason university
ID 167: analyst
ID 168: business intelligence analyst
ID 169: msba umass amherst 24 cspo business intelligence strategy and operations
ID 170: business analyst sql python ms excel data migration tableau power bi jira oracle aws business analysis
ID 171: aspiring product manager information systems graduate with a strong technical background passionate about driving innovation and solving complex problems
ID 172: encargado de marketing y ventas en sego eventos
ID 173: --
ID 174: senior data analyst
ID 175: uc graduate student ms business analytics2024 actively seeking full-time or internship for summer 2024
ID 176: .
ID 177: senior data analyst at td bank
ID 178: business intelligence specialist data analytics dax power query python
ID 179: master of science in business analytics ex-clariant research analyst new business development data analyst business intelligence
ID 180: rd software engineer ii at broadcom inc.
ID 181: researcher
ID 182: experienced data analyst research coordinator healthcare data specialist
ID 183: senior survey design engineer at newtonx
ID 184: multi-competent generalist
ID 185: business development account management
ID 186: mechanical engineer
ID 187: contact center architect at bank of america
ID 188: sde comp sci it double major ru 24
ID 189: cybersecurity
ID 190: informatics student ux designer data-driven problem solver
ID 191: former graduate student at university of north florida unf alumni
ID 192: masters in data analytics and engineering
ID 193: dev python dev flutter engenheiro de dados data engineer analista de dados data analysis dev landing pages sql pyspark
ID 194: None
ID 195: ms in data science at nyit
ID 196: b.s in computer science a passion for dance
ID 197: machine learning engineer arizona state university masters robotics and autonomous systems in ai actively seeking full-time opportunities.
ID 198: ai engineer
ID 199: ms in information systems northeastern university data scientist business intelligence data engineering data analyst transforming data into insights
ID 200: business analyst amazon web services
ID 201: data scientist
ID 202: software engineer data scientist ai machine learning expert nlp deep learning specialist transforming data into strategic insights
ID 203: m.s. data science graduate michigan state university
ID 204: ms in computer science mentor women in big data ex-mle intern hiddenlayer passionate about data engineering aiml enthusiast with focus on nlp llms

### Training the Fine Tuned model

In [ ]:
from sklearn.model_selection import train_test_split

# Splitting the data: 80% train, 20% temporary (to be split into val/test)
train_df, temp_df = train_test_split(fine_tuning_df, test_size=0.2, random_state=seed)

# Splitting the temporary 20% into 50% validation and 50% test (10% of total each)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=seed)

print(f"Data splitting complete:")
print(f"- Training set: {len(train_df)} rows")
print(f"- Validation set: {len(val_df)} rows")
print(f"- Test set: {len(test_df)} rows")

# Display a sample of the training data
train_df.head()

Data splitting complete:
- Training set: 1028 rows
- Validation set: 128 rows
- Test set: 129 rows

,id,title,location,screening_score
567,568,data science masters graduate from heriot-watt...,United Kingdom,90
464,465,data science mathematical statistics data anal...,United States,95
183,184,multi-competent generalist,United States,75
1221,1222,DATA ANALYST,India,0
1161,1162,data analyst sql python data visualization,United States,25

In [ ]:
from datasets import Dataset, DatasetDict

# Convert DataFrames to Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

# Combine into a DatasetDict
raw_datasets = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset,
    'test': test_dataset
})

def tokenize_function(examples):
    # Create the prompt for the model
    # We are training the model to understand the relationship between job titles and scores
    prompts = [
        f"Job Title: {title}\nLocation: {location}\nScreening Score: {score}"
        for title, location, score in zip(examples['title'], examples['location'], examples['screening_score'])
    ]
    return tokenizer(prompts, truncation=True, padding="max_length", max_length=256)

tokenized_datasets = raw_datasets.map(
    tokenize_function,
    batched=True,
    remove_columns=raw_datasets["train"].column_names
)

print("Tokenization complete. Dataset structure:")
print(tokenized_datasets)

Map:   0%|          | 0/1028 [00:00<?, ? examples/s]

Map:   0%|          | 0/128 [00:00<?, ? examples/s]

Map:   0%|          | 0/129 [00:00<?, ? examples/s]

Tokenization complete. Dataset structure:
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 1028
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 128
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 129
    })
})

In [ ]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [ ]:
original_model = prepare_model_for_kbit_training(original_model)

In [ ]:
config = LoraConfig(
    r=32, #Rank
    lora_alpha=32,
    target_modules=[
        'q_proj',
        'k_proj',
        'v_proj',
        'dense'
    ],
    bias="none",
    lora_dropout=0.05,  # Conventional
    task_type="CAUSAL_LM",
)

# 1 - Enabling gradient checkpointing to reduce memory usage during fine-tuning
original_model.gradient_checkpointing_enable()

peft_model = get_peft_model(original_model, config)

In [ ]:
def print_number_of_trainable_model_parameters(model):
    trainable_model_params = 0
    all_model_params = 0
    for _, param in model.named_parameters():
        all_model_params += param.numel()
        if param.requires_grad:
            trainable_model_params += param.numel()
    return f"trainable model parameters: {trainable_model_params}\nall model parameters: {all_model_params}\npercentage of trainable model parameters: {100 * trainable_model_params / all_model_params:.2f}%"

In [ ]:
print(print_number_of_trainable_model_parameters(peft_model))

trainable model parameters: 20971520
all model parameters: 1542364160
percentage of trainable model parameters: 1.36%

In [ ]:
# Define the output directory on Google Drive for persistent storage
output_dir = '/content/drive/My Drive/Apziva/Project 3 - Potential Talents/phi2-finetuned-checkpoints'

In [ ]:
import transformers

# Further optimized for TPU memory constraints
peft_training_args = TrainingArguments(
    output_dir = output_dir,
    warmup_steps=1,
    per_device_train_batch_size=1, # Minimum batch size
    gradient_accumulation_steps=8, # Increased to reduce memory pressure
    max_steps=500, # Reduced steps for initial test
    learning_rate=2e-4,
    optim="adamw_torch",
    logging_steps=10,
    save_strategy="steps",
    save_steps=100,
    gradient_checkpointing=True, # Essential for saving memory
    report_to="none",
    ddp_find_unused_parameters=False,
    dataloader_drop_last=True
)

peft_model.config.use_cache = False

In [ ]:
peft_trainer = transformers.Trainer(
    model=peft_model,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
    args=peft_training_args,
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

peft_trainer.train()

TrainOutput(global_step=500, training_loss=1.9155545024871825, metrics={'train_runtime': 2484.0559, 'train_samples_per_second': 1.61, 'train_steps_per_second': 0.201, 'total_flos': 1.635271440334848e+16, 'train_loss': 1.9155545024871825, 'epoch': 3.8793774319066148})

### Inference with the Fine Tuned model

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

base_model_id = "microsoft/phi-2"
base_model = AutoModelForCausalLM.from_pretrained(base_model_id,
                                                      device_map='auto',
                                                      quantization_config=bnb_config,
                                                      trust_remote_code=True)

config.json:   0%|          | 0.00/735 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/453 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
eval_tokenizer = AutoTokenizer.from_pretrained(base_model_id, add_bos_token=True, trust_remote_code=True, use_fast=False)
eval_tokenizer.pad_token = eval_tokenizer.eos_token

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
def gen(model,p, maxlen=100, sample=True):
  toks = eval_tokenizer(p, return_tensors="pt")
  res = model.generate(**toks.to("cuda"), max_new_tokens=maxlen, do_sample=sample,num_return_sequences=1,temperature=0.1,num_beams=1,top_p=0.95,).to('cpu')
  return eval_tokenizer.batch_decode(res,skip_special_tokens=True)

In [ ]:
from peft import PeftModel
import torch

# Using the local output directory and the latest checkpoint found in your files
checkpoint_path = f"{output_dir}/checkpoint-500"

ft_model_lora = PeftModel.from_pretrained(
    base_model,
    checkpoint_path,
    torch_dtype=torch.float16,
    is_trainable=False
)

In [ ]:
search_term = "data analyst"
top_n = 5

# Prepare the list of all candidates for the prompt
candidates_text = "\n".join([f"ID {row['id']}: {row['title']}" for _, row in fine_tuning_data.iterrows()])

# Construct the prompt for the LLM to rank all candidates at once
prompt = f"""As an expert recruiter, rank the following candidates based on the search term: '{search_term}'.\n\nCandidates:\n{candidates_text}\n\nIdentify the top {top_n} candidates. For each, provide the Candidate ID, the Candidate's job title, a Similarity Score (0.0 to 1.0), and a brief explanation of why they are a good match. Please format your response as a clear list or table."""

print(f"Processing all {len(fine_tuning_data)} candidates at once for search term '{search_term}'...")

# Generate the ranking using the model
# Adjust maxlen based on the expected length of the full ranking output
full_ranking_res_fine_tuned_lora = gen(ft_model_lora, prompt, maxlen=2000)

print('-' * 100)
print(f"Full Ranking for '{search_term}':\n{full_ranking_res_fine_tuned_lora[0]}")

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (23775 > 2048). Running this sequence through the model will result in indexing errors
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processing all 1285 candidates at once for search term 'data analyst'...

[transformers] This is a friendly reminder - the current text generation call has exceeded the model's predefined maximum length (2048). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CodeGenTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

----------------------------------------------------------------------------------------------------
Full Ranking for 'data analyst':
As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.

Candidates:
ID 1: innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.
ID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories former data science intern quadratyx actively seeking full time roles in summer 2025
ID 3: computer science student seeking full-time software engineerdeveloper positions ai sql data visualization toolspython ssrs
ID 4: microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson
ID 5: graduate research assistant at uab masters in data science student at uab ex jio
ID 6: student at kennesaw state university
ID 7: data analyst business analyst python snowflake sql machine learning power bi tableau equipped with analytics driven by insights and passionate about impactful solutions.
ID 8: graduate research aide student at arizona state university
ID 9: data science nlp ai ml python sas quantum computing block chain sql
ID 10: data science machine learning artificial intelligence
ID 11: experienced data analystdata scientist python sql r java ml ai enthusiast cloud solutions aws azure data visualization power bi tableau agile scrum practitioner
ID 12: actively seeking full-time w2 opportunities data engineer ai ml engineer data analyst ex-accenture aws certified
ID 13: machine learning artificial intelligence and data science enthusiast
ID 14: collaborative data engineer bridging the gap between data science and data engineering aws python etl
ID 15: None
ID 16: software test engineer at amdocs artificial intelligence machine learning i deep learning neural network llm gen ai
ID 17: data engineer data analyst data pipelines ai ml advanced analytics power bi tableau sql python aws azure gcp hadoop spark hive etl pipelines big data machine learning cicd
ID 18: actively seeking full-time roles in bioinformatics masters in biomedical informatics and data science asu
ID 19: ds grad student umass dartmouth open to work
ID 20: senior technology analyst dynamo software master of science in business analytics
ID 21: transitioning to data science masters graduate eager to launch career in the field
ID 22: detailed oriented with excellent communication skills
ID 23: experienced software developer skilled in c python and aws driving seamless data integration and website development with strong leadership and teamwork abilities.
ID 24: certified data engineer building scalable etl pipelines cloud big data specialist aws azure snowflake driving data-driven decisions with ai analytics
ID 25: data analyst and machine learning engineer
ID 26: sr business intelligence analyst mba
ID 27: data analyst market awareness ixp sap ai machine learning enthusiast leveraging data for impact
ID 28: aspiring data scientist passion for data-driven decision making master of science in business analytics graduate - university of new hampshire
ID 29: researcher deep learning spatial data science
ID 30: software developer scheme designers inc developed features for aircraft configurators
ID 31: content adversarial red team analyst ai content training seo strategy risk analysis
ID 32: computer science and data science student uw-madison
ID 33: graduate student umd
ID 34: ut austin ms data science graduate data scientist
ID 35: ms data science at university of minnesota ex data analyst intern at spatialytics private limited
ID 36: ms in ds at university of new haven grad 2023 actively seeking for full time opportunities data analyst
ID 37: actively seeking full-time roles data analyst data scientist business analyst msis graduate unc charlotte
ID 38: aspiring data scientist software engineering enthusiast certified ibm data science professional extensive experience in python database management postgres mysql java c
ID 39: data scientist process improvement finance
ID 40: stem educator data science data analytics pursuing master of science data science
ID 41: target role data science data analyst ms ece in machine learning computer vision
ID 42: python sql data integration pyspark machine learning llm apache airflow etl meng graduate
ID 43: data analyst with 3 years of experience mps in data science analyst experience at ub libraries cyient ltd expertise in python sql aws and predictive analytics
ID 44: data scientist ai ml expert nlp graph analytics big data cloud mba msc data science
ID 45: strategic data analyst 9 years in advanced analytics machine learning power bi python sql aws azure expert transforming data into business insights
ID 46: data science and analytics python sql power bi excel
ID 47: data analyst magna international ai enthusiast expert in data integration analytics azure databricks etl pipelines cloud solutions optimizing operational efficiency driving data-driven decision-making
ID 48: data analyst 4 years of experience in data-driven decision making proficient in python r sql actively seeking full-time opportunities
ID 49: looking for spring 2025 internships and full time roles graduate student at university of north texas data analyst tata consultancy services
ID 50: senior data analyst at iqvia working with pharmacy and medical claims level data m.s. data science computational methods data engineer data scientist
ID 51: information systems management carnegie mellon university data scientist resolving business problems and decision-making process with data-drive approach
ID 52: data analyst ai engineer bi engineer data engineer software developer ai machine learning enthusiast azure aws python sql tableau power bi 6x microsoft certified
ID 53: data engineer data scientist data analyst big data engineer cloud data engineer aws azure data engineer data analytics bigdata aws data engineer aws machine learning engineer
ID 54: data engineer data analyst expert in etl aws spark kafka aws certified optimized data models processing proficient in sql python tableau 4 years in data engineering analysis ml
ID 55: ai enthusiast graduate assistant at kent state university frontend and backend experience machine learning deep learning nlp focus actively seeking full-time opportunities
ID 56: software engineer ingenworks python flask machine learning mlops data science software development
ID 57: data science computer science business
ID 58: ph.d. candidate in economics seeking roles as economist data scientist or quantitative researcher
ID 59: data engineer data pipelines big data etl databricks snowflake hadoop python kafka artificial intelligence data lake
ID 60: supply chain analyst sap s4hana data-driven optimization rpa ai in supply chain power bi big data analytics
ID 61: senior business intelligence sql developer and data engineer amsive azure pipelines pyspark notebookspark databricks sql server ssis power bi adf lavastorm ms data science
ID 62: data analyst sqlpython tableau power bi transforming data into insights
ID 63: data analyst data scientist m.s statistics data science concentration bs applied math
ID 64: m.s. computer science graduate machine learning data science enthusiast experienced in sap erp pythontensorflow pytorch aws gpa 3.74 san jose state university
ID 65: data scientist data analyst candidate at webster university business intelligence specialist data analyst data scientist machine learning ml analyst machine learning engineer.
ID 66: ms in biotechnology ms candidate in biological data science bioinformatics enthusiast skilled in python sql r and ngs bridging biology and data
ID 67: data analyst business intelligence sql python machine learning driving data-driven decisions strategic planning
ID 68: new grad 24 data analyst seeking new opportunities sql python power bi excel ai ml passionate about data science and analysis currently building gen ai llm based analytics applications
ID 69: data science graduate passionate about ai ml analytics
ID 70: data science graduate ex - data analyst learning and developing data engineering skills with ai integration
ID 71: software engineer ms in computer science backend full-stack development ex-rakuten
ID 72: ml engineer ex-indigo ex-google
ID 73: program analyst at cognizant enhancing data quality efficiency in analytics data science graduate enhancing decision-making with power bi statistical analysis proficient in sql python power bi
ID 74: data analyst
ID 75: data-driven problem solver salesforce cloud enthusiast transforming insights into strategic decisions sql power bi agile process optimization
ID 76: research intern data science ai exploring the power of data technology iot electrical engineer
ID 77: actively looking for full-time opportunities graduate student in business analytics artificial intelligence utd data enthusiast ex associate software engineer cgi
ID 78: data engineer sql data visualization data analyst sustainability analyst solar energy
ID 79: msc data science graduate full stack developer python sql java react.js beng mechanical and electrical engineering
ID 80: business analyst at kriptone m.s in data science
ID 81: masters student at the university of greenwich. data science big data analytics machine learning business intelligence
ID 82: data science ai machine learning engineer business analytics data-driven decision maker
ID 83: i am a graduate of uconn with a bachelors in business and data analytics and a current soldier in the national guard looking to find entry level or junior work in the data analysis field.
ID 84: mba-business analytics
ID 85: research analyst in cancer biology spatial transcriptomics multiomics
ID 86: logical data analyst skilled in requirement analysis software development and database management sql tableau data warehousing python sas
ID 87: actively seeking full time opportunities w2 data engineer sde sdet data analyst qa automation ex - hexagon
ID 88: data analyst in cvs health
ID 89: tessitura applications administrator at oregon shakespeare festival
ID 90: masters student in information science cornell cis
ID 91: alumni of california state university channel islands
ID 92: turning data into actionable insights data analyst expert in sql python and power bi actively seeking job opportunities
ID 93: insurance agent with customer service it and analytical experience
ID 94: digital data analyst leveraging python sql and advanced analytics tools for data-driven marketing seosem optimization specialist
ID 95: actively looking for full-time opportunities data engineer data analyst business intelligence ms dae at northeastern university python sql tableau etl aws gcp machine learning
ID 96: data analyst easley-dunn productions inc. master of science in business analytics
ID 97: data-driven decision-making enthusiast expert in data analysis and visualization
ID 98: data analyst 3 years of experience in data-driven decision making sql python aws
ID 99: data analyst software engineer python sql power bi tableau data-driven problem solver
ID 100: aspiring data analyst business intelligence sql python r power bi tableau data visualization predictive analytics turning data into insights driving business decisions ms in computer science
ID 101: data analyst elevance health inc ms in computer science
ID 102: data analyst sql python tableau power bi data validation compliance business intelligence automation reporting
ID 103: masters in data science python sql skilled in data analyst power bi
ID 104: data analyst orbitekk masters in information science
ID 105: grad student at avila university
ID 106: senior data analyst statistical analysis data science c2cc2h
ID 107: senior data engineeranalytics
ID 108: itil 4 comptia a
ID 109: software engineer cloud data intern it specialist graduate umbc ex-accenture analyst certified azure 4x aws oracle network python django .net asp.net sql dynamics erp scm
ID 110: return inventory management - trimble inc
ID 111: university of texas at san antonio grad class of 2025 business analytics intern at trs
ID 112: data analyst m.s. in data analytics sql python r tableau power bi first-gen college grad driving data-backed decisions
ID 113: recent app state gradseeking analyst positions
ID 114: data analyst globallogic masters of science in data analytics
ID 115: data analyst with 2 years of experience in extracting analyzing and visualizing data to empower organizations with actionable insights. skilled in tools such as sql python excel tableau and power bi.
ID 116: system administrator
ID 117: hr recruiter
ID 118: data configuration analyst at loopback analytics
ID 119: computer science graduate student at clark university ex-software engineer at accenture
ID 120: actively looking for full time positions computer and information systems security sql python etl tableau power-bi oops c pyspark scala ssis ssms data warehousing awslambdas3
ID 121: motivated recent graduate looking for internships or early career positions
ID 122: software engineer tata consultancy services
ID 123: python r sql tableau statistics power bi data analytics business intelligence
ID 124: senior data analystbi developer
ID 125: data engineer cloud devops advocate finance building scalable data solutions with python aws agile business analyst business intelligence developer iab certified
ID 126: data engineer aws solutions architect certified ibm data analyst data analytics grad gmu aspiring data engineer python sql tableau power bi
ID 127: actively seeking data analyst tableau pgsql ms excel power bi python
ID 128: senior data analyst at centers health care
ID 129: experienced business intelligence analyst data-driven decision maker bi data engineering specialist
ID 130: registered behavioral therapist
ID 131: math analyst ii at gaming laboratories international llc
ID 132: --
ID 133: data analyst sql python tableau turning data into insights
ID 134: data analyst turning data into actionable insights skilled in sql python tableau power bi excel etl and data visualization passionate about driving data-driven decisions actively seeking job opportunities
ID 135: data engineer big data cloud specialist aws spark python building scalable data pipelines
ID 136: bioinformatic engineer everlumebio current masters student in bioinformatics
ID 137: bi and analytics snowflake dbt pythontableau skilled in data visualization big data analytics
ID 138: master of science in biostatistics columbia 25
ID 139: master of science in financial mathematics
ID 140: data analyst
ID 141: data analyst at ameritas
ID 142: senior business intelligence analyst business intelligence consultant using tableau powerbi sql spotfire alteryx microsoft excel to build insightful dashboards
ID 143: senior data engineer
ID 144: data analyst 2
ID 145: actively looking for contract and full time opportunities java python sql etl hadoop hive spark pyspark aws gcp azure kafka tableau power bi
ID 146: bachelors in business analytics and information systems cybersecurity concentration
ID 147: bioinformatics analytics statistics
ID 148: senior data analyst seeking new c2c c2h opportunities in data analytics data engineering sql development bi solutions expert in data modeling etl cloud technologies and sql
ID 149: businessdata system analyst sqloraclessrsssisftpputtytableauplmgcphadooppythont-sqlunixpower bigithubagileplmawsjava
ID 150: 9 data engineering cloud migration aws gcp data warehousing snowflake
ID 151: data analyst data analysis etl tools sap hana
ID 152: data analyst ford motor data analyst data engineer python sql tableau power bi aws azure masters in computer science
ID 153: senior data analyst snowflake pyspark sql python etl databricks
ID 154: actively seeking full-time roles data analyst data engineer tableau certified power bi sql azure certified alteryx data visualization
ID 155: looking for a data analyst role skilled in data analysis data management and data visualization proficient in sql r programming tableau and spreadsheets tools enthusiastic about transforming data into insights
ID 156: sr dataengineer hadoopbigdata developer
ID 157: data engineer azure aws cloud expert sql python spark specialist
ID 158: qa automation engineer expertise in selenium appium cicd integration specialist passionate about quality assurance and cloud testing
ID 159: experienced data analyst python r sql expertise in data visualization predictive modeling business intelligence driving insights strategic decisions for business growth
ID 160: senior data analyst turning data into actionable insights sql power bi excel tableau python aws azure open to c2cc2h
ID 161: industrial engineering intern cedar point amusement park msis university of maryland adobe student ambassador indus university 23 sih 22 winner
ID 162: data and applications analyst
ID 163: data engineer information technology
ID 164: data analyst proven track record in data-driven decision making 3 years
ID 165: senior big data engineer actively seeking for new opportunities data engineer big data sql aws hadoop azure pyspark kafka yarn hdfs scala etl
ID 166: data analytics engineeringgeorge mason university
ID 167: analyst
ID 168: business intelligence analyst
ID 169: msba umass amherst 24 cspo business intelligence strategy and operations
ID 170: business analyst sql python ms excel data migration tableau power bi jira oracle aws business analysis
ID 171: aspiring product manager information systems graduate with a strong technical background passionate about driving innovation and solving complex problems
ID 172: encargado de marketing y ventas en sego eventos
ID 173: --
ID 174: senior data analyst
ID 175: uc graduate student ms business analytics2024 actively seeking full-time or internship for summer 2024
ID 176: .
ID 177: senior data analyst at td bank
ID 178: business intelligence specialist data analytics dax power query python
ID 179: master of science in business analytics ex-clariant research analyst new business development data analyst business intelligence
ID 180: rd software engineer ii at broadcom inc.
ID 181: researcher
ID 182: experienced data analyst research coordinator healthcare data specialist
ID 183: senior survey design engineer at newtonx
ID 184: multi-competent generalist
ID 185: business development account management
ID 186: mechanical engineer
ID 187: contact center architect at bank of america
ID 188: sde comp sci it double major ru 24
ID 189: cybersecurity
ID 190: informatics student ux designer data-driven problem solver
ID 191: former graduate student at university of north florida unf alumni
ID 192: masters in data analytics and engineering
ID 193: dev python dev flutter engenheiro de dados data engineer analista de dados data analysis dev landing pages sql pyspark
ID 194: None
ID 195: ms in data science at nyit
ID 196: b.s in computer science a passion for dance
ID 197: machine learning engineer arizona state university masters robotics and autonomous systems in ai actively seeking full-time opportunities.
ID 198: ai engineer
ID 199: ms in information systems northeastern university data scientist business intelligence data engineering data analyst transforming data into insights
ID 200: business analyst amazon web services
ID 201: data scientist
ID 202: software engineer data scientist ai machine learning expert nlp deep learning specialist transforming data into strategic insights
ID 203: m.s. data science graduate michigan state university
ID 204: ms in computer science mentor women in big data ex-mle intern hiddenlayer passionate about data engineering aiml enthusiast with focus on nlp llms

In [ ]:
import re

def extract_ranked_ids(output):
    # Helper to find IDs mentioned in the model's response
    return re.findall(r'ID\s*(\d+)', output)

search_term = "data analyst"
batch_size = 10
top_per_batch = 3
batch_winners = []

# Filter out IDs with 'None' titles before processing
valid_candidates = fine_tuning_data[fine_tuning_data['title'].notnull()]

print(f"Processing {len(valid_candidates)} candidates in batches of {batch_size}...")

# Step 1: Batch Processing
for i in range(0, len(valid_candidates), batch_size):
    batch = valid_candidates.iloc[i : i + batch_size]
    candidates_text = "\n".join([f"ID {row['id']}: {row['title']}" for _, row in batch.iterrows()])

    prompt = f"""As an expert recruiter, rank the following candidates based on the search term: '{search_term}'.

Candidates:
{candidates_text}

Identify the top {top_per_batch} candidates. For each, provide the ID and a brief explanation."""

    # Using the fine-tuned model (ft_model_lora) from previous cells
    res = gen(ft_model_lora, prompt, maxlen=5000)
    batch_winners.append(res[0])

    if (i // batch_size) % 10 == 0:
        print(f"Processed {i + len(batch)} candidates...")

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processing 1281 candidates in batches of 10...

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CodeGenTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 10 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 110 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 210 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 310 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] This is a friendly reminder - the current text generation call has exceeded the model's predefined maximum length (2048). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 410 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 510 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 610 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 710 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 810 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 910 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1010 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1110 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Processed 1210 candidates...

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
print(batch_winners)

["As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 1: innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.\nID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories former data science intern quadratyx actively seeking full time roles in summer 2025\nID 3: computer science student seeking full-time software engineerdeveloper positions ai sql data visualization toolspython ssrs\nID 4: microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson\nID 5: graduate research assistant at uab masters in data science student at uab ex jio\nID 6: student at kennesaw state university\nID 7: data analyst business analyst python snowflake sql machine learning power bi tableau equipped with analytics driven by insights and passionate about impactful solutions.\nID 8: graduate research aide student at arizona state university\nID 9: data science nlp ai ml python sas quantum computing block chain sql\nID 10: data science machine learning artificial intelligence\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 1: innovative and driven professional seeking a role in data analytics\n2. ID 4: microsoft certified power bi data analyst\n3. ID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories\nExplanation: ID 1 is a highly skilled and experienced professional actively seeking a role in data analytics. ID 4 is a certified power bi data analyst, indicating expertise in data analytics. ID 2 is a student actively seeking full-time roles in data analytics, indicating potential for growth in the field.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 11: experienced data analystdata scientist python sql r java ml ai enthusiast cloud solutions aws azure data visualization power bi tableau agile scrum practitioner\nID 12: actively seeking full-time w2 opportunities data engineer ai ml engineer data analyst ex-accenture aws certified\nID 13: machine learning artificial intelligence and data science enthusiast\nID 14: collaborative data engineer bridging the gap between data science and data engineering aws python etl\nID 16: software test engineer at amdocs artificial intelligence machine learning i deep learning neural network llm gen ai\nID 17: data engineer data analyst data pipelines ai ml advanced analytics power bi tableau sql python aws azure gcp hadoop spark hive etl pipelines big data machine learning cicd\nID 18: actively seeking full-time roles in bioinformatics masters in biomedical informatics and data science asu\nID 19: ds grad student umass dartmouth open to work\nID 20: senior technology analyst dynamo software master of science in business analytics\nID 21: transitioning to data science masters graduate eager to launch career in the field\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 11: Experienced Data Analyst\n2. ID 14: Collaborative Data Engineer\n3. ID 19: Senior Technology Analyst\n\nExplanation:\nID 11 is an experienced data analyst with expertise in Python, SQL, and data visualization. They actively seek full-time roles in the field.\nID 14 is a collaborative data engineer who bridges the gap between data science and data engineering. They are certified in AWS and proficient in Python and ETL pipelines.\nID 19 is a senior technology analyst with a passion for data science. They are actively seeking full-time roles and have a master's degree in business analytics.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 22: detailed oriented with excellent communication skills\nID 23: experienced software developer skilled in c python and aws driving seamless data integration and website development with strong leadership and teamwork abilities.\nID 24: certified data engineer building scalable etl pipelines cloud big data specialist aws azure snowflake driving data-driven decisions with ai analytics\nID 25: data analyst and machine learning engineer\nID 26: sr business intelligence analyst mba\nID 27: data analyst market awareness ixp sap ai machine learning enthusiast leveraging data for impact\nID 28: aspiring data scientist passion for data-driven decision making master of science in business analytics graduate - university of new hampshire\nID 29: researcher deep learning spatial data science\nID 30: software developer scheme designers inc developed features for aircraft configurators\nID 31: content adversarial red team analyst ai content training seo strategy risk analysis\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nSolution:\n1. ID 24: Certified Data Engineer Building Scalable ETL Pipelines Cloud Big Data Specialist AWS Snowflake Driving Data-Driven Decisions with AI Analytics\n2. ID 22: Detailed Oriented with Excellent Communication Skills\n3. ID 25: Data Analyst and Machine Learning Engineer\n\nExplanation:\nID 24 is a certified data engineer with expertise in building scalable ETL pipelines and driving data-driven decisions with AI analytics.\nID 22 is a detail-oriented candidate with excellent communication skills.\nID 25 is a data analyst and machine learning engineer.\n\nFollow-up Exercise 1:\nWhat are the key skills required for a data engineer?\n\nSolution:\nKey skills required for a data engineer include:\n- Python programming\n- SQL\n- Data visualization\n- ETL tools\n- Cloud computing\n- Data warehousing\n- Data pipelines\n- Data security\n- Machine learning\n\nFollow-up Exercise 2:\nWhat are the benefits of using AI analytics in data-driven decision making?\n\nSolution:\nBenefits of using AI analytics in data-driven decision making include:\n- Improved accuracy and efficiency in data analysis\n- Predictive modeling for future trends and insights\n- Automation of data-driven processes\n- Enhanced decision-making capabilities\n- Cost savings through optimized resource allocation\n- Improved customer experience through personalized insights\n\nFollow-up Exercise 3:\nWhat are the challenges faced by data analysts in the field of data science?\n\nSolution:\nChallenges faced by data analysts in the field of data science include:\n- Data quality and data cleaning\n- Handling large volumes of data\n- Dealing with complex data structures\n- Selecting appropriate data analysis techniques\n- Communicating insights effectively to stakeholders\n- Keeping up with evolving technologies and tools\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 32: computer science and data science student uw-madison\nID 33: graduate student umd\nID 34: ut austin ms data science graduate data scientist\nID 35: ms data science at university of minnesota ex data analyst intern at spatialytics private limited\nID 36: ms in ds at university of new haven grad 2023 actively seeking for full time opportunities data analyst\nID 37: actively seeking full-time roles data analyst data scientist business analyst msis graduate unc charlotte\nID 38: aspiring data scientist software engineering enthusiast certified ibm data science professional extensive experience in python database management postgres mysql java c\nID 39: data scientist process improvement finance\nID 40: stem educator data science data analytics pursuing master of science data science\nID 41: target role data science data analyst ms ece in machine learning computer vision\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\nAssistant: 1. ID 35: MS in Data Science at University of Minnesota - Ex Data Analyst Intern at Spatialytics Private Limited\nExplanation: The candidate has a strong background in data science and actively seeking full-time roles.\n\n2. ID 34: MS in Data Science at University of Minnesota - Data Scientist\nExplanation: The candidate has a strong background in data science and actively seeking full-time roles.\n\n3. ID 32: Computer Science and Data Science Student at University of Wisconsin-Madison\nExplanation: The candidate has a strong academic background in data science and actively seeking full-time roles.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 42: python sql data integration pyspark machine learning llm apache airflow etl meng graduate\nID 43: data analyst with 3 years of experience mps in data science analyst experience at ub libraries cyient ltd expertise in python sql aws and predictive analytics\nID 44: data scientist ai ml expert nlp graph analytics big data cloud mba msc data science\nID 45: strategic data analyst 9 years in advanced analytics machine learning power bi python sql aws azure expert transforming data into business insights\nID 46: data science and analytics python sql power bi excel\nID 47: data analyst magna international ai enthusiast expert in data integration analytics azure databricks etl pipelines cloud solutions optimizing operational efficiency driving data-driven decision-making\nID 48: data analyst 4 years of experience in data-driven decision making proficient in python r sql actively seeking full-time opportunities\nID 49: looking for spring 2025 internships and full time roles graduate student at university of north texas data analyst tata consultancy services\nID 50: senior data analyst at iqvia working with pharmacy and medical claims level data m.s. data science computational methods data engineer data scientist\nID 51: information systems management carnegie mellon university data scientist resolving business problems and decision-making process with data-drive approach\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 42: Python SQL Data Integration Pyspark Machine Learning LLM Apache Airflow ETL Meng Graduate\nExplanation: This candidate has a strong foundation in Python, SQL, and machine learning, along with expertise in data integration and LLM. They are actively seeking full-time opportunities.\n\n2. ID 47: Strategic Data Analyst 9 Years in Advanced Analytics Machine Learning Power BI Python SQL AWS Azure\nExplanation: This candidate has extensive experience in advanced analytics and machine learning, with expertise in Python, SQL, and cloud solutions. They actively seek full-time opportunities.\n\n3. ID 50: Senior Data Analyst at iqvia Working with Pharmacy and Medical Claims Level Data M.S. Data Science Computational Methods Data Engineer Data Scientist\nExplanation: This candidate has a strong background in data analysis and has experience working with pharmacy and medical claims data. They have a M.S. in Data Science and are actively seeking full-time opportunities.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 52: data analyst ai engineer bi engineer data engineer software developer ai machine learning enthusiast azure aws python sql tableau power bi 6x microsoft certified\nID 53: data engineer data scientist data analyst big data engineer cloud data engineer aws azure data engineer data analytics bigdata aws data engineer aws machine learning engineer\nID 54: data engineer data analyst expert in etl aws spark kafka aws certified optimized data models processing proficient in sql python tableau 4 years in data engineering analysis ml\nID 55: ai enthusiast graduate assistant at kent state university frontend and backend experience machine learning deep learning nlp focus actively seeking full-time opportunities\nID 56: software engineer ingenworks python flask machine learning mlops data science software development\nID 57: data science computer science business\nID 58: ph.d. candidate in economics seeking roles as economist data scientist or quantitative researcher\nID 59: data engineer data pipelines big data etl databricks snowflake hadoop python kafka artificial intelligence data lake\nID 60: supply chain analyst sap s4hana data-driven optimization rpa ai in supply chain power bi big data analytics\nID 61: senior business intelligence sql developer and data engineer amsive azure pipelines pyspark notebookspark databricks sql server ssis power bi adf lavastorm ms data science\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 52: data analyst ai engineer bi engineer\nExplanation: This candidate has experience in data analysis and machine learning, as well as expertise in Python and SQL. They have a background in data engineering and are actively seeking full-time opportunities.\n\n2. ID 54: data engineer data analyst\nExplanation: This candidate has experience in data engineering and data analysis. They are proficient in Python and SQL and have expertise in building data pipelines and optimizing data models.\n\n3. ID 55: ai enthusiast\nExplanation: This candidate is actively seeking full-time opportunities and has a passion for AI. They have experience in Python and have a strong foundation in machine learning.\n\n4. ID 56: software engineer\nExplanation: This candidate has experience in software development but does not specialize in data analysis or data engineering.\n\n5. ID 57: data science\nExplanation: This candidate has a background in computer science and is interested in data science. However, they do not have experience in data analysis or data engineering.\n\n6. ID 58: ph.d. candidate in economics\nExplanation: This candidate is seeking roles as an economist but does not have experience in data analysis or data engineering.\n\n7. ID 59: data engineer data pipelines big data etl databricks\nExplanation: This candidate has experience in data engineering and has expertise in building data pipelines with tools like Snowflake and Apache Hadoop.\n\n8. ID 60: supply chain analyst\nExplanation: This candidate has experience in supply chain analysis but does not have experience in data analysis or data engineering.\n\n9. ID 61: senior business intelligence sql developer and data engineer\nExplanation: This candidate has experience in business intelligence and data engineering. They are proficient in SQL and have expertise in building data pipelines and optimizing data models.\n\n10. ID 62: data scientist\nExplanation: This candidate has experience in data science but does not have experience in data analysis or data engineering.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 62: data analyst sqlpython tableau power bi transforming data into insights\nID 63: data analyst data scientist m.s statistics data science concentration bs applied math\nID 64: m.s. computer science graduate machine learning data science enthusiast experienced in sap erp pythontensorflow pytorch aws gpa 3.74 san jose state university\nID 65: data scientist data analyst candidate at webster university business intelligence specialist data analyst data scientist machine learning ml analyst machine learning engineer.\nID 66: ms in biotechnology ms candidate in biological data science bioinformatics enthusiast skilled in python sql r and ngs bridging biology and data\nID 67: data analyst business intelligence sql python machine learning driving data-driven decisions strategic planning\nID 68: new grad 24 data analyst seeking new opportunities sql python power bi excel ai ml passionate about data science and analysis currently building gen ai llm based analytics applications\nID 69: data science graduate passionate about ai ml analytics\nID 70: data science graduate ex - data analyst learning and developing data engineering skills with ai integration\nID 71: software engineer ms in computer science backend full-stack development ex-rakuten\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 64: M.S. Computer Science Graduate - Machine Learning Data Science Enthusiast\nExplanation: This candidate has a strong background in computer science and is passionate about data science. They have experience in SQL, Python, and Machine Learning and are actively seeking new opportunities.\n\n2. ID 67: Data Analyst - Business Intelligence Specialist\nExplanation: This candidate has experience in data analysis and is skilled in SQL, Python, and Machine Learning. They are actively seeking new opportunities and have a strong focus on driving data-driven decisions.\n\n3. ID 66: MS in Biotechnology - Bioinformatics Enthusiast\nExplanation: This candidate has a background in biotechnology and is passionate about bioinformatics. They have experience in Python, SQL, and Machine Learning and are actively seeking new opportunities.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 72: ml engineer ex-indigo ex-google\nID 73: program analyst at cognizant enhancing data quality efficiency in analytics data science graduate enhancing decision-making with power bi statistical analysis proficient in sql python power bi\nID 74: data analyst\nID 75: data-driven problem solver salesforce cloud enthusiast transforming insights into strategic decisions sql power bi agile process optimization\nID 76: research intern data science ai exploring the power of data technology iot electrical engineer\nID 77: actively looking for full-time opportunities graduate student in business analytics artificial intelligence utd data enthusiast ex associate software engineer cgi\nID 78: data engineer sql data visualization data analyst sustainability analyst solar energy\nID 79: msc data science graduate full stack developer python sql java react.js beng mechanical and electrical engineering\nID 80: business analyst at kriptone m.s in data science\nID 81: masters student at the university of greenwich. data science big data analytics machine learning business intelligence\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 73: Program Analyst at Cognizant - This candidate has a strong background in data analysis and is proficient in SQL and Python. They have experience in enhancing data quality and efficiency in analytics and have a proven track record in decision-making.\n2. ID 79: Data Engineer at Kriptone - This candidate is skilled in Python and SQL and has experience in developing data pipelines and implementing data-driven solutions. They have a strong foundation in data engineering and have expertise in building scalable and efficient data infrastructure.\n3. ID 75: Data-Driven Problem Solver at Salesforce - This candidate is proficient in SQL and Python and has experience in transforming insights into strategic decisions. They have a strong focus on data-driven problem-solving and have expertise in developing and implementing data-driven solutions.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 82: data science ai machine learning engineer business analytics data-driven decision maker\nID 83: i am a graduate of uconn with a bachelors in business and data analytics and a current soldier in the national guard looking to find entry level or junior work in the data analysis field.\nID 84: mba-business analytics\nID 85: research analyst in cancer biology spatial transcriptomics multiomics\nID 86: logical data analyst skilled in requirement analysis software development and database management sql tableau data warehousing python sas\nID 87: activel

In [ ]:
print(batch_winners)

["As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 1: innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.\nID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories former data science intern quadratyx actively seeking full time roles in summer 2025\nID 3: computer science student seeking full-time software engineerdeveloper positions ai sql data visualization toolspython ssrs\nID 4: microsoft certified power bi data analyst mba business analytics unt business intelligence engineer data scientist data engineer business analytics predictive analytics statistical analysis ex-ericsson\nID 5: graduate research assistant at uab masters in data science student at uab ex jio\nID 6: student at kennesaw state university\nID 7: data analyst business analyst python snowflake sql machine learning power bi tableau equipped with analytics driven by insights and passionate about impactful solutions.\nID 8: graduate research aide student at arizona state university\nID 9: data science nlp ai ml python sas quantum computing block chain sql\nID 10: data science machine learning artificial intelligence\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 1: innovative and driven professional seeking a role in data analytics\n2. ID 4: microsoft certified power bi data analyst\n3. ID 2: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories\nExplanation: ID 1 is a highly skilled and experienced professional actively seeking a role in data analytics. ID 4 is a certified power bi data analyst, indicating expertise in data analytics. ID 2 is a student actively seeking full-time roles in data analytics, indicating potential for growth in the field.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 11: experienced data analystdata scientist python sql r java ml ai enthusiast cloud solutions aws azure data visualization power bi tableau agile scrum practitioner\nID 12: actively seeking full-time w2 opportunities data engineer ai ml engineer data analyst ex-accenture aws certified\nID 13: machine learning artificial intelligence and data science enthusiast\nID 14: collaborative data engineer bridging the gap between data science and data engineering aws python etl\nID 16: software test engineer at amdocs artificial intelligence machine learning i deep learning neural network llm gen ai\nID 17: data engineer data analyst data pipelines ai ml advanced analytics power bi tableau sql python aws azure gcp hadoop spark hive etl pipelines big data machine learning cicd\nID 18: actively seeking full-time roles in bioinformatics masters in biomedical informatics and data science asu\nID 19: ds grad student umass dartmouth open to work\nID 20: senior technology analyst dynamo software master of science in business analytics\nID 21: transitioning to data science masters graduate eager to launch career in the field\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 11: Experienced Data Analyst\n2. ID 14: Collaborative Data Engineer\n3. ID 19: Senior Technology Analyst\n\nExplanation:\nID 11 is an experienced data analyst with expertise in Python, SQL, and data visualization. They actively seek full-time roles in the field.\nID 14 is a collaborative data engineer who bridges the gap between data science and data engineering. They are certified in AWS and proficient in Python and ETL pipelines.\nID 19 is a senior technology analyst with a passion for data science. They are actively seeking full-time roles and have a master's degree in business analytics.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 22: detailed oriented with excellent communication skills\nID 23: experienced software developer skilled in c python and aws driving seamless data integration and website development with strong leadership and teamwork abilities.\nID 24: certified data engineer building scalable etl pipelines cloud big data specialist aws azure snowflake driving data-driven decisions with ai analytics\nID 25: data analyst and machine learning engineer\nID 26: sr business intelligence analyst mba\nID 27: data analyst market awareness ixp sap ai machine learning enthusiast leveraging data for impact\nID 28: aspiring data scientist passion for data-driven decision making master of science in business analytics graduate - university of new hampshire\nID 29: researcher deep learning spatial data science\nID 30: software developer scheme designers inc developed features for aircraft configurators\nID 31: content adversarial red team analyst ai content training seo strategy risk analysis\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nSolution:\n1. ID 24: Certified Data Engineer Building Scalable ETL Pipelines Cloud Big Data Specialist AWS Snowflake Driving Data-Driven Decisions with AI Analytics\n2. ID 22: Detailed Oriented with Excellent Communication Skills\n3. ID 25: Data Analyst and Machine Learning Engineer\n\nExplanation:\nID 24 is a certified data engineer with expertise in building scalable ETL pipelines and driving data-driven decisions with AI analytics.\nID 22 is a detail-oriented candidate with excellent communication skills.\nID 25 is a data analyst and machine learning engineer.\n\nFollow-up Exercise 1:\nWhat are the key skills required for a data engineer?\n\nSolution:\nKey skills required for a data engineer include:\n- Python programming\n- SQL\n- Data visualization\n- ETL tools\n- Cloud computing\n- Data warehousing\n- Data pipelines\n- Data security\n- Machine learning\n\nFollow-up Exercise 2:\nWhat are the benefits of using AI analytics in data-driven decision making?\n\nSolution:\nBenefits of using AI analytics in data-driven decision making include:\n- Improved accuracy and efficiency in data analysis\n- Predictive modeling for future trends and insights\n- Automation of data-driven processes\n- Enhanced decision-making capabilities\n- Cost savings through optimized resource allocation\n- Improved customer experience through personalized insights\n\nFollow-up Exercise 3:\nWhat are the challenges faced by data analysts in the field of data science?\n\nSolution:\nChallenges faced by data analysts in the field of data science include:\n- Data quality and data cleaning\n- Handling large volumes of data\n- Dealing with complex data structures\n- Selecting appropriate data analysis techniques\n- Communicating insights effectively to stakeholders\n- Keeping up with evolving technologies and tools\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 32: computer science and data science student uw-madison\nID 33: graduate student umd\nID 34: ut austin ms data science graduate data scientist\nID 35: ms data science at university of minnesota ex data analyst intern at spatialytics private limited\nID 36: ms in ds at university of new haven grad 2023 actively seeking for full time opportunities data analyst\nID 37: actively seeking full-time roles data analyst data scientist business analyst msis graduate unc charlotte\nID 38: aspiring data scientist software engineering enthusiast certified ibm data science professional extensive experience in python database management postgres mysql java c\nID 39: data scientist process improvement finance\nID 40: stem educator data science data analytics pursuing master of science data science\nID 41: target role data science data analyst ms ece in machine learning computer vision\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\nAssistant: 1. ID 35: MS in Data Science at University of Minnesota - Ex Data Analyst Intern at Spatialytics Private Limited\nExplanation: The candidate has a strong background in data science and actively seeking full-time roles.\n\n2. ID 34: MS in Data Science at University of Minnesota - Data Scientist\nExplanation: The candidate has a strong background in data science and actively seeking full-time roles.\n\n3. ID 32: Computer Science and Data Science Student at University of Wisconsin-Madison\nExplanation: The candidate has a strong academic background in data science and actively seeking full-time roles.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 42: python sql data integration pyspark machine learning llm apache airflow etl meng graduate\nID 43: data analyst with 3 years of experience mps in data science analyst experience at ub libraries cyient ltd expertise in python sql aws and predictive analytics\nID 44: data scientist ai ml expert nlp graph analytics big data cloud mba msc data science\nID 45: strategic data analyst 9 years in advanced analytics machine learning power bi python sql aws azure expert transforming data into business insights\nID 46: data science and analytics python sql power bi excel\nID 47: data analyst magna international ai enthusiast expert in data integration analytics azure databricks etl pipelines cloud solutions optimizing operational efficiency driving data-driven decision-making\nID 48: data analyst 4 years of experience in data-driven decision making proficient in python r sql actively seeking full-time opportunities\nID 49: looking for spring 2025 internships and full time roles graduate student at university of north texas data analyst tata consultancy services\nID 50: senior data analyst at iqvia working with pharmacy and medical claims level data m.s. data science computational methods data engineer data scientist\nID 51: information systems management carnegie mellon university data scientist resolving business problems and decision-making process with data-drive approach\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 42: Python SQL Data Integration Pyspark Machine Learning LLM Apache Airflow ETL Meng Graduate\nExplanation: This candidate has a strong foundation in Python, SQL, and machine learning, along with expertise in data integration and LLM. They are actively seeking full-time opportunities.\n\n2. ID 47: Strategic Data Analyst 9 Years in Advanced Analytics Machine Learning Power BI Python SQL AWS Azure\nExplanation: This candidate has extensive experience in advanced analytics and machine learning, with expertise in Python, SQL, and cloud solutions. They actively seek full-time opportunities.\n\n3. ID 50: Senior Data Analyst at iqvia Working with Pharmacy and Medical Claims Level Data M.S. Data Science Computational Methods Data Engineer Data Scientist\nExplanation: This candidate has a strong background in data analysis and has experience working with pharmacy and medical claims data. They have a M.S. in Data Science and are actively seeking full-time opportunities.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 52: data analyst ai engineer bi engineer data engineer software developer ai machine learning enthusiast azure aws python sql tableau power bi 6x microsoft certified\nID 53: data engineer data scientist data analyst big data engineer cloud data engineer aws azure data engineer data analytics bigdata aws data engineer aws machine learning engineer\nID 54: data engineer data analyst expert in etl aws spark kafka aws certified optimized data models processing proficient in sql python tableau 4 years in data engineering analysis ml\nID 55: ai enthusiast graduate assistant at kent state university frontend and backend experience machine learning deep learning nlp focus actively seeking full-time opportunities\nID 56: software engineer ingenworks python flask machine learning mlops data science software development\nID 57: data science computer science business\nID 58: ph.d. candidate in economics seeking roles as economist data scientist or quantitative researcher\nID 59: data engineer data pipelines big data etl databricks snowflake hadoop python kafka artificial intelligence data lake\nID 60: supply chain analyst sap s4hana data-driven optimization rpa ai in supply chain power bi big data analytics\nID 61: senior business intelligence sql developer and data engineer amsive azure pipelines pyspark notebookspark databricks sql server ssis power bi adf lavastorm ms data science\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 52: data analyst ai engineer bi engineer\nExplanation: This candidate has experience in data analysis and machine learning, as well as expertise in Python and SQL. They have a background in data engineering and are actively seeking full-time opportunities.\n\n2. ID 54: data engineer data analyst\nExplanation: This candidate has experience in data engineering and data analysis. They are proficient in Python and SQL and have expertise in building data pipelines and optimizing data models.\n\n3. ID 55: ai enthusiast\nExplanation: This candidate is actively seeking full-time opportunities and has a passion for AI. They have experience in Python and have a strong foundation in machine learning.\n\n4. ID 56: software engineer\nExplanation: This candidate has experience in software development but does not specialize in data analysis or data engineering.\n\n5. ID 57: data science\nExplanation: This candidate has a background in computer science and is interested in data science. However, they do not have experience in data analysis or data engineering.\n\n6. ID 58: ph.d. candidate in economics\nExplanation: This candidate is seeking roles as an economist but does not have experience in data analysis or data engineering.\n\n7. ID 59: data engineer data pipelines big data etl databricks\nExplanation: This candidate has experience in data engineering and has expertise in building data pipelines with tools like Snowflake and Apache Hadoop.\n\n8. ID 60: supply chain analyst\nExplanation: This candidate has experience in supply chain analysis but does not have experience in data analysis or data engineering.\n\n9. ID 61: senior business intelligence sql developer and data engineer\nExplanation: This candidate has experience in business intelligence and data engineering. They are proficient in SQL and have expertise in building data pipelines and optimizing data models.\n\n10. ID 62: data scientist\nExplanation: This candidate has experience in data science but does not have experience in data analysis or data engineering.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 62: data analyst sqlpython tableau power bi transforming data into insights\nID 63: data analyst data scientist m.s statistics data science concentration bs applied math\nID 64: m.s. computer science graduate machine learning data science enthusiast experienced in sap erp pythontensorflow pytorch aws gpa 3.74 san jose state university\nID 65: data scientist data analyst candidate at webster university business intelligence specialist data analyst data scientist machine learning ml analyst machine learning engineer.\nID 66: ms in biotechnology ms candidate in biological data science bioinformatics enthusiast skilled in python sql r and ngs bridging biology and data\nID 67: data analyst business intelligence sql python machine learning driving data-driven decisions strategic planning\nID 68: new grad 24 data analyst seeking new opportunities sql python power bi excel ai ml passionate about data science and analysis currently building gen ai llm based analytics applications\nID 69: data science graduate passionate about ai ml analytics\nID 70: data science graduate ex - data analyst learning and developing data engineering skills with ai integration\nID 71: software engineer ms in computer science backend full-stack development ex-rakuten\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 64: M.S. Computer Science Graduate - Machine Learning Data Science Enthusiast\nExplanation: This candidate has a strong background in computer science and is passionate about data science. They have experience in SQL, Python, and Machine Learning and are actively seeking new opportunities.\n\n2. ID 67: Data Analyst - Business Intelligence Specialist\nExplanation: This candidate has experience in data analysis and is skilled in SQL, Python, and Machine Learning. They are actively seeking new opportunities and have a strong focus on driving data-driven decisions.\n\n3. ID 66: MS in Biotechnology - Bioinformatics Enthusiast\nExplanation: This candidate has a background in biotechnology and is passionate about bioinformatics. They have experience in Python, SQL, and Machine Learning and are actively seeking new opportunities.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 72: ml engineer ex-indigo ex-google\nID 73: program analyst at cognizant enhancing data quality efficiency in analytics data science graduate enhancing decision-making with power bi statistical analysis proficient in sql python power bi\nID 74: data analyst\nID 75: data-driven problem solver salesforce cloud enthusiast transforming insights into strategic decisions sql power bi agile process optimization\nID 76: research intern data science ai exploring the power of data technology iot electrical engineer\nID 77: actively looking for full-time opportunities graduate student in business analytics artificial intelligence utd data enthusiast ex associate software engineer cgi\nID 78: data engineer sql data visualization data analyst sustainability analyst solar energy\nID 79: msc data science graduate full stack developer python sql java react.js beng mechanical and electrical engineering\nID 80: business analyst at kriptone m.s in data science\nID 81: masters student at the university of greenwich. data science big data analytics machine learning business intelligence\n\nIdentify the top 3 candidates. For each, provide the ID and a brief explanation.\n\nAnswer:\n1. ID 73: Program Analyst at Cognizant - This candidate has a strong background in data analysis and is proficient in SQL and Python. They have experience in enhancing data quality and efficiency in analytics and have a proven track record in decision-making.\n2. ID 79: Data Engineer at Kriptone - This candidate is skilled in Python and SQL and has experience in developing data pipelines and implementing data-driven solutions. They have a strong foundation in data engineering and have expertise in building scalable and efficient data infrastructure.\n3. ID 75: Data-Driven Problem Solver at Salesforce - This candidate is proficient in SQL and Python and has experience in transforming insights into strategic decisions. They have a strong focus on data-driven problem-solving and have expertise in developing and implementing data-driven solutions.\n", "As an expert recruiter, rank the following candidates based on the search term: 'data analyst'.\n\nCandidates:\nID 82: data science ai machine learning engineer business analytics data-driven decision maker\nID 83: i am a graduate of uconn with a bachelors in business and data analytics and a current soldier in the national guard looking to find entry level or junior work in the data analysis field.\nID 84: mba-business analytics\nID 85: research analyst in cancer biology spatial transcriptomics multiomics\nID 86: logical data analyst skilled in requirement analysis software development and database management sql tableau data warehousing python sas\nID 87: activel

In [ ]:
search_term = "data analyst"

In [ ]:
import re
import torch
import gc

# Clear CUDA cache and reset peak memory stats
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()
gc.collect()

def extract_ranked_from_batch_winner(batch_winner_text):
    candidates = []
    answer_section_match = re.search(r"Answer:\n(.*?)(?=\nExplanation:|$)", batch_winner_text, re.DOTALL)
    if not answer_section_match:
        return []
    answer_content = answer_section_match.group(1).strip()
    ranked_lines = re.findall(r'^\s*\d+\.\s*(ID\s*\d+:\s*.*?)(?=\n\d+\. ID|$)', answer_content, re.MULTILINE | re.DOTALL)
    for line in ranked_lines:
        match = re.match(r'ID\s*(\d+):\s*(.*)', line.strip())
        if match:
            candidates.append({'id': int(match.group(1)), 'job_title': match.group(2).strip()})
    return candidates

# Stage 2 Distillation: Rename and process batch results
semi_final_batch_size = 10
all_top_candidates_from_batches = []
for batch_output in batch_winners:
    all_top_candidates_from_batches.extend(extract_ranked_from_batch_winner(batch_output))

concise_candidate_list_for_distillation = []
seen_ids = set()
for candidate in all_top_candidates_from_batches:
    if candidate['id'] not in seen_ids:
        concise_candidate_list_for_distillation.append(f"Candidate ID: {candidate['id']}, Job Title: {candidate['job_title']}")
        seen_ids.add(candidate['id'])

semi_final_winners = []
for i in range(0, len(concise_candidate_list_for_distillation), semi_final_batch_size):
    batch = concise_candidate_list_for_distillation[i : i + semi_final_batch_size]
    batch_text = "\n".join(batch)
    distill_prompt = f"""From the following candidates for '{search_term}', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\n{batch_text}"""
    distilled_res = gen(ft_model_lora, distill_prompt, maxlen=150)
    semi_final_winners.append(distilled_res[0])

# Explicit memory cleanup before final ranking
torch.cuda.empty_cache()
gc.collect()

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

57

In [ ]:
semi_final_winners

["From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 1, Job Title: innovative and driven professional seeking a role in data analytics\nCandidate ID: 4, Job Title: microsoft certified power bi data analyst\nCandidate ID: 2, Job Title: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories\nCandidate ID: 11, Job Title: Experienced Data Analyst\nCandidate ID: 14, Job Title: Collaborative Data Engineer\nCandidate ID: 19, Job Title: Senior Technology Analyst\nCandidate ID: 42, Job Title: Python SQL Data Integration Pyspark Machine Learning LLM Apache Airflow ETL Meng Graduate\nCandidate ID: 52, Job Title: data analyst ai engineer bi engineer\nCandidate ID: 64, Job Title: M.S. Computer Science Graduate - Machine Learning Data Science Enthusiast\nCandidate ID: 73, Job Title: Program Analyst at Cognizant - This candidate has a strong background in data analysis and is proficient in SQL and Python. They have experience in enhancing data quality and efficiency in analytics and have a proven track record in decision-making.\n\nCandidate ID: 82, Job Title: Data Analyst\nCandidate ID: 95, Job Title: Data Scientist\nCandidate ID: 99, Job Title: Data Analyst\nCandidate ID: 100, Job Title: Data Scientist\nCandidate ID: 101, Job Title: Data Analyst\nCandidate ID: 102, Job Title: Data Scientist\nCandidate ID: 103, Job Title: Data Analyst\nCandidate ID: 104, Job Title: Data Scientist\nCandidate ID: 105, Job Title: Data Analyst\nCandidate ID: 106, Job Title: Data Scientist\nCandidate ID: 107, Job Title: Data Analyst\nCandidate ID: 108, Job Title: Data Scientist\nCandidate ID:",
 "From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 79, Job Title: Data Engineer at Kriptone - This candidate is skilled in Python and SQL and has experience in developing data pipelines and implementing data-driven solutions. They have a strong foundation in data engineering and have expertise in building scalable and efficient data infrastructure.\nCandidate ID: 75, Job Title: Data-Driven Problem Solver at Salesforce - This candidate is proficient in SQL and Python and has experience in transforming insights into strategic decisions. They have a strong focus on data-driven problem-solving and have expertise in developing and implementing data-driven solutions.\nCandidate ID: 82, Job Title: Data Science AI Machine Learning Engineer - This candidate has a strong background in data science and machine learning, making them highly skilled in data analysis and data-driven decision making.\nCandidate ID: 85, Job Title: Research Analyst in Cancer Biology - While not directly related to data analysis, this candidate's experience in cancer biology and multiomics research demonstrates their ability to analyze complex data and draw meaningful insights.\nCandidate ID: 88, Job Title: Data Analyst in CVS Health - This candidate has experience in data analysis and may have opportunities for growth in the healthcare industry.\nCandidate ID: 95, Job Title: actively looking for full-time opportunities data engineer data analyst business intelligence ms dae at northeastern university\nCandidate ID: 102, Job Title: data analyst sql python tableau power bi data validation compliance business intelligence automation reporting\nCandidate ID: 125, Job Title: actively seeking data analyst tableau pgsql ms excel power bi python - This candidate has a strong background in data analytics and is actively seeking a role in data analysis. They have experience in Python, SQL, Tableau, and AWS, making them a highly skilled candidate for data analyst roles.\nCandidate ID: 133, Job Title: data analyst sql python tableau turning data into insights - This candidate has the most relevant skills and experience for the role of data analyst.\nCandidate ID: 135, Job Title: data engineer big data cloud specialist aws spark python building scalable data pipelines - This candidate has a strong technical background in data engineering and cloud technologies, which are essential for data analysis and visualization.\nCandidate ID: 145, Job Title: actively seeking data analyst sql python tableau power bi - This candidate has a strong background in data analysis and is actively seeking a role in data analysis. They have experience in Python, SQL, Tableau, and AWS, making them a highly skilled candidate for data analyst roles.\nCandidate ID: 155, Job Title: data analyst sql python tableau power bi - This candidate has a strong technical background in data engineering and cloud technologies, which are essential for data analysis and visualization.\nCandidate ID: 165, Job Title: actively seeking data analyst sql python tableau power bi - This candidate has a strong background in data analysis and is actively seeking a role in data analysis. They have experience",
 "From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 137, Job Title: bi and analytics snowflake dbt python tableau skilled in data visualization big data analytics - This candidate has expertise in bi and analytics, as well as experience with Snowflake and Dbt, which are advanced tools for data analysis and visualization.\nCandidate ID: 142, Job Title: Senior Business Intelligence Analyst - This candidate has extensive experience in business intelligence and data analysis, with expertise in using various tools such as Tableau, Power BI, and SQL to build insightful dashboards and drive data-driven decision-making.\nCandidate ID: 150, Job Title: Senior Data Engineer - This candidate has a strong background in data engineering and cloud technologies, with experience in migrating data to cloud platforms like AWS and Snowflake and implementing data warehousing solutions.\nCandidate ID: 147, Job Title: Bioinformatics Analyst - This candidate has expertise in bioinformatics and analytics, with experience in statistical analysis and data visualization.\nCandidate ID: 152, Job Title: data analyst ford motor - This candidate has a strong background in data analysis and data engineering, with expertise in Python, SQL, and Tableau. They have experience in transforming data into actionable insights and driving strategic decisions for business growth.\nCandidate ID: 155, Job Title: actively seeking full-time roles data analyst skilled in data analysis data management and data visualization proficient in SQL Python tableau and spreadsheets tools - This candidate actively seeks full-time roles and demonstrates a strong passion for data analysis, data management, and data visualization. They are proficient in SQL, Python, and tableau and actively seeking opportunities to showcase their skills.\nCandidate ID: 160, Job Title: senior data analyst turning data into actionable insights sql power bi excel tableau python aws azure open to c2cc2h - This candidate has experience as a senior data analyst and has expertise in SQL, Python, and tableau. They actively seek opportunities to turn data into actionable insights and are open to new challenges.\nCandidate ID: 162, Job Title: data and applications analyst - This candidate has a specific role as a data and applications analyst, which indicates a strong focus on data-driven decision making and problem-solving.\nCandidate ID: 165, Job Title: senior big data engineer - This candidate has a senior role as a big data engineer, which indicates a high level of expertise in handling large-scale data processing and analytics.\nCandidate ID: 169, Job Title: msba umass amherst 24 cspo business intelligence strategy and operations - This candidate has a graduate degree in business intelligence and has experience in developing strategies and operations for data analytics.\nCandidate ID: 170, Job Title: data analyst - This candidate has a specific role as a data analyst, which indicates a strong focus on data analysis and problem-solving.\nCandidate ID: 175, Job Title: data scientist - This candidate has a specific role as a data scientist, which indicates a high level of expertise in data analysis and machine learning.\nCandidate ID: 176, Job Title: data analyst - This candidate has a specific role as a data analyst, which indicates a strong focus on data analysis and problem-solving.\nCandidate ID: 177, Job Title: data engineer - This candidate has a specific role as a data engineer, which indicates a high level of expertise in data engineering and data",
 "From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 182, Job Title: experienced data analyst research coordinator healthcare data specialist - This candidate has a strong background in data analysis and has experience in healthcare data management.\nCandidate ID: 187, Job Title: cybersecurity - This candidate has expertise in cybersecurity, which is a crucial skill in today's digital age.\nCandidate ID: 184, Job Title: multi-competent generalist - This candidate has a diverse skill set and can adapt to various roles and challenges.\nCandidate ID: 203, Job Title: m.s. data science graduate michigan state university - This candidate has a strong educational background in data science and is actively seeking full-time opportunities.\nCandidate ID: 206, Job Title: aiml researcher data scientist aws certified - This candidate has expertise in machine learning and has demonstrated cost savings through data-driven techniques.\nCandidate ID: 205, Job Title: actively seeking full-time opportunities in data science python sql r spark machine learning bi and cloud tools specialist m. s. student in information management uiuc - This candidate is actively seeking full-time roles and has a strong foundation in data science with expertise in Python, SQL, and ML.\nCandidate ID: 213, Job Title: data scientist specializing in machine learning statistical modeling proven success with etl workflows reducing data cleaning time by 80 passionate about transforming data into actionable insights\nCandidate ID: 220, Job Title: data scientist research scientist machine learning engineer artificial intelligence creating accurate and efficient machine learning solutions ai scientist ai engineer\nCandidate ID: 221, Job Title: machine learningdata scienceai researchcomputer vision machine perceptionnlp llms gen ai prompt engineering machine learning deep learning nlp hugging face transformers llms langchain rag asr model development python sql tableau azure certified\nCandidate ID: 223, Job Title: msis - big data aws certified automation etl data modeling machine learning python sql tableau skilled in data analysis and visualization\nCandidate ID: 224, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization\nCandidate ID: 225, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization\nCandidate ID: 226, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization\nCandidate ID: 227, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization\nCandidate ID: 228, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization\nCandidate ID: 229, Job Title: data analyst python sql table",
 "From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 233, Job Title: data scientist data analyst ms in data science\nCandidate ID: 243, Job Title: data scientist aiml practitioner aws azure certified passionate about data-driven solutions\nCandidate ID: 254, Job Title: data analyst machine learning engineer transforming data into actionable insights with advanced analytics predictive modeling 5 years of experience in python sql tableau and ai solutions\nCandidate ID: 264, Job Title: data scientist 4 years in data analysis visualization predictive modeling python sql power bi\nCandidate ID: 284, Job Title: biomedical research scientist - This candidate is a biomedical research scientist, which is not directly related to data analysis. However, they may have experience in data analysis in their research.\nCandidate ID: 289, Job Title: data scientist certified tensorflow developer - This candidate is a data scientist and certified in tensorflow, a popular machine learning framework. They have experience in data analysis and machine learning.\nCandidate ID: 286, Job Title: machine learning engineer tata consultancy services limited generative ai expert in machine learning and data modeling data-driven decision making - This candidate is a machine learning engineer and an expert in generative AI and data modeling. They have experience in data analysis and machine learning.\nCandidate ID: 295, Job Title: Senior Data Scientist - Data Scientist\nCandidate ID: 297, Job Title: Data Analyst - Data Analyst\nCandidate ID: 303, Job Title: Data Scientist Artificial Intelligence Financial Analyst - Data Scientist\nCandidate ID: 304, Job Title: Data Analyst - Data Analyst\nCandidate ID: 305, Job Title: Data Scientist - Data Scientist\nCandidate ID: 306, Job Title: Data Analyst - Data Analyst\nCandidate ID: 307, Job Title: Data Scientist - Data Scientist\nCandidate ID: 308, Job Title: Data Analyst - Data Analyst\nCandidate ID: 309, Job Title: Data Scientist - Data Scientist\nCandidate ID: 310, Job Title: Data Analyst - Data Analyst\nCandidate ID: 311, Job Title: Data Scientist - Data Scientist\nCandidate ID: 312, Job Title: Data Analyst - Data Analyst\nCandidate ID: 313, Job Title: Data Scientist - Data Scientist",
 "From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 304, Job Title: Data Scientist Leveraging Python Power BI SQL Machine Learning and Deep Learning to Drive Insights\nCandidate ID: 314, Job Title: Data Scientist Data Analyst AI ML Engineer Data Engineer Passionate About Turning Data into Intelligent Solutions\nCandidate ID: 325, Job Title: Data Analyst Guru - This candidate has a master's degree in data science and is actively seeking full-time opportunities. They have experience in data analysis and machine learning.\nCandidate ID: 328, Job Title: Software Engineer Mathematics - This candidate has a background in software engineering and mathematics. They have experience in data science and machine learning.\nCandidate ID: 330, Job Title: Healthcare Data Scientist - This candidate has a background in healthcare and data science. They have experience in data analysis and machine learning.\nCandidate ID: 335, Job Title: It Specialist Data Science Business Intelligence Data-Driven Decision Making\nCandidate ID: 337, Job Title: MS Business Analytics University of Tampa 25 Graduate Research Assistant President U.T.\nCandidate ID: 334, Job Title: Data Science U.C. Berkeley Undergraduate Researcher Innovative Genomics Institute\nCandidate ID: 344, Job Title: data analyst at winfertility - This candidate has a dedicated role as a data analyst, indicating a strong focus and expertise in the field.\nCandidate ID: 350, Job Title: data engineer at syzygy plasmonics - This candidate has experience in data engineering and actively seeks roles as a data analyst, demonstrating a proactive approach to pursuing opportunities.\nCandidate ID: 355, Job Title: Data Analyst at a Leading Financial Institution\nCandidate ID: 356, Job Title: Data Analyst at a Leading Healthcare Provider\nCandidate ID: 357, Job Title: Data Analyst at a Leading Retailer\nCandidate ID: 358, Job Title: Data Analyst at a Leading Technology Company\nCandidate ID: 359, Job Title: Data Analyst at a Leading Insurance Provider\nCandidate ID: 360, Job Title: Data Analyst at a Leading Automotive Manufacturer\nCandidate ID: 361, Job Title: Data Analyst at a Leading Financial Institution\nCandidate ID: 362, Job Title: Data Analyst at a Leading Healthcare Provider\nCandidate ID: 363, Job Title: Data Analyst",
 "From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.\n\nCandidates:\nCandidate ID: 354, Job Title: experienced data analyst\nCandidate ID: 355, Job Title: student at the university of memphis\nCandidate ID: 362, Job Title: actively looking for full-time opportunities mlds roles pnnl georgia tech\nCandidate ID: 364, Job Title: m.s. in data analytics python django developer specializing in machine learning models data visualization and database management\nCandidate ID: 374, Job Title: business professional mba data scientist data analyst transforming skills with triple ten coding bootcamp\nCandidate ID: 393, Job Title: AI Machine Learning Engineer Full Stack Developer Data Scientist SQL Power BI Expert Cloud Automation Enthusiast\nCandidate ID: 404, Job Title: data science graduate student at university at buffalo seeking for full time opportunities in data science data analyst business analyst sde roles\nCandidate ID: 420, Job Title: Computer Science Graduate Aspiring Software Developer Passionate About Back-End Programming and AI Technologies\nCandidate ID: 421, Job Title: Master of Science in Data Science\nCandidate ID: 416, Job Title: Data Analyst Business Intelligence Data Quality Assurance SQL Project Management Supply Chain Management\nCandidate ID: 422, Job Title: Data Analyst\nCandidate ID: 423, Job Title: Data Analyst\nCandidate ID: 424, Job Title: Data Analyst\nCandidate ID: 425, Job Title: Data Analyst\nCandidate ID: 426, Job Title: Data Analyst\nCandidate ID: 427, Job Title: Data Analyst\nCandidate ID: 428, Job Title: Data Analyst\nCandidate ID: 429, Job Title: Data Analyst\nCandidate ID: 430, Job Title: Data Analyst\nCandidate ID: 431, Job Title: Data Analyst\nCandidate ID: 432, Job Title: Data Analyst\nCandidate ID: 433, Job Title: Data Analyst\nCandidate ID",

In [ ]:
# Final consolidation using renamed distilled results
final_prompt_candidates_string = "\n".join(semi_final_winners[:10])
final_prompt = f"""Rank the top 5 candidates for '{search_term}' from this list:\n{final_prompt_candidates_string}\n\nFormat as Markdown table: | Rank | ID | Job Title | Score (0-1) |\nFollowed by '### Justification' bullet points."""

print(f"\nGenerating final absolute top 5 ranking (Distillation batch: {semi_final_batch_size})...")
final_top_5 = gen(ft_model_lora, final_prompt, maxlen=600)

print('-' * 100)
print(f"FINAL TOP 5 RANKING:\n{final_top_5[0]}")

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Generating final absolute top 5 ranking (Distillation batch: 10)...
----------------------------------------------------------------------------------------------------
FINAL TOP 5 RANKING:
Rank the top 5 candidates for 'data analyst' from this list:
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 1, Job Title: innovative and driven professional seeking a role in data analytics
Candidate ID: 4, Job Title: microsoft certified power bi data analyst
Candidate ID: 2, Job Title: ms applied data science student usc research assistant usc former data analytics intern at dr reddys laboratories
Candidate ID: 11, Job Title: Experienced Data Analyst
Candidate ID: 14, Job Title: Collaborative Data Engineer
Candidate ID: 19, Job Title: Senior Technology Analyst
Candidate ID: 42, Job Title: Python SQL Data Integration Pyspark Machine Learning LLM Apache Airflow ETL Meng Graduate
Candidate ID: 52, Job Title: data analyst ai engineer bi engineer
Candidate ID: 64, Job Title: M.S. Computer Science Graduate - Machine Learning Data Science Enthusiast
Candidate ID: 73, Job Title: Program Analyst at Cognizant - This candidate has a strong background in data analysis and is proficient in SQL and Python. They have experience in enhancing data quality and efficiency in analytics and have a proven track record in decision-making.

Candidate ID: 82, Job Title: Data Analyst
Candidate ID: 95, Job Title: Data Scientist
Candidate ID: 99, Job Title: Data Analyst
Candidate ID: 100, Job Title: Data Scientist
Candidate ID: 101, Job Title: Data Analyst
Candidate ID: 102, Job Title: Data Scientist
Candidate ID: 103, Job Title: Data Analyst
Candidate ID: 104, Job Title: Data Scientist
Candidate ID: 105, Job Title: Data Analyst
Candidate ID: 106, Job Title: Data Scientist
Candidate ID: 107, Job Title: Data Analyst
Candidate ID: 108, Job Title: Data Scientist
Candidate ID:
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 79, Job Title: Data Engineer at Kriptone - This candidate is skilled in Python and SQL and has experience in developing data pipelines and implementing data-driven solutions. They have a strong foundation in data engineering and have expertise in building scalable and efficient data infrastructure.
Candidate ID: 75, Job Title: Data-Driven Problem Solver at Salesforce - This candidate is proficient in SQL and Python and has experience in transforming insights into strategic decisions. They have a strong focus on data-driven problem-solving and have expertise in developing and implementing data-driven solutions.
Candidate ID: 82, Job Title: Data Science AI Machine Learning Engineer - This candidate has a strong background in data science and machine learning, making them highly skilled in data analysis and data-driven decision making.
Candidate ID: 85, Job Title: Research Analyst in Cancer Biology - While not directly related to data analysis, this candidate's experience in cancer biology and multiomics research demonstrates their ability to analyze complex data and draw meaningful insights.
Candidate ID: 88, Job Title: Data Analyst in CVS Health - This candidate has experience in data analysis and may have opportunities for growth in the healthcare industry.
Candidate ID: 95, Job Title: actively looking for full-time opportunities data engineer data analyst business intelligence ms dae at northeastern university
Candidate ID: 102, Job Title: data analyst sql python tableau power bi data validation compliance business intelligence automation reporting
Candidate ID: 125, Job Title: actively seeking data analyst tableau pgsql ms excel power bi python - This candidate has a strong background in data analytics and is actively seeking a role in data analysis. They have experience in Python, SQL, Tableau, and AWS, making them a highly skilled candidate for data analyst roles.
Candidate ID: 133, Job Title: data analyst sql python tableau turning data into insights - This candidate has the most relevant skills and experience for the role of data analyst.
Candidate ID: 135, Job Title: data engineer big data cloud specialist aws spark python building scalable data pipelines - This candidate has a strong technical background in data engineering and cloud technologies, which are essential for data analysis and visualization.
Candidate ID: 145, Job Title: actively seeking data analyst sql python tableau power bi - This candidate has a strong background in data analysis and is actively seeking a role in data analysis. They have experience in Python, SQL, Tableau, and AWS, making them a highly skilled candidate for data analyst roles.
Candidate ID: 155, Job Title: data analyst sql python tableau power bi - This candidate has a strong technical background in data engineering and cloud technologies, which are essential for data analysis and visualization.
Candidate ID: 165, Job Title: actively seeking data analyst sql python tableau power bi - This candidate has a strong background in data analysis and is actively seeking a role in data analysis. They have experience
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 137, Job Title: bi and analytics snowflake dbt python tableau skilled in data visualization big data analytics - This candidate has expertise in bi and analytics, as well as experience with Snowflake and Dbt, which are advanced tools for data analysis and visualization.
Candidate ID: 142, Job Title: Senior Business Intelligence Analyst - This candidate has extensive experience in business intelligence and data analysis, with expertise in using various tools such as Tableau, Power BI, and SQL to build insightful dashboards and drive data-driven decision-making.
Candidate ID: 150, Job Title: Senior Data Engineer - This candidate has a strong background in data engineering and cloud technologies, with experience in migrating data to cloud platforms like AWS and Snowflake and implementing data warehousing solutions.
Candidate ID: 147, Job Title: Bioinformatics Analyst - This candidate has expertise in bioinformatics and analytics, with experience in statistical analysis and data visualization.
Candidate ID: 152, Job Title: data analyst ford motor - This candidate has a strong background in data analysis and data engineering, with expertise in Python, SQL, and Tableau. They have experience in transforming data into actionable insights and driving strategic decisions for business growth.
Candidate ID: 155, Job Title: actively seeking full-time roles data analyst skilled in data analysis data management and data visualization proficient in SQL Python tableau and spreadsheets tools - This candidate actively seeks full-time roles and demonstrates a strong passion for data analysis, data management, and data visualization. They are proficient in SQL, Python, and tableau and actively seeking opportunities to showcase their skills.
Candidate ID: 160, Job Title: senior data analyst turning data into actionable insights sql power bi excel tableau python aws azure open to c2cc2h - This candidate has experience as a senior data analyst and has expertise in SQL, Python, and tableau. They actively seek opportunities to turn data into actionable insights and are open to new challenges.
Candidate ID: 162, Job Title: data and applications analyst - This candidate has a specific role as a data and applications analyst, which indicates a strong focus on data-driven decision making and problem-solving.
Candidate ID: 165, Job Title: senior big data engineer - This candidate has a senior role as a big data engineer, which indicates a high level of expertise in handling large-scale data processing and analytics.
Candidate ID: 169, Job Title: msba umass amherst 24 cspo business intelligence strategy and operations - This candidate has a graduate degree in business intelligence and has experience in developing strategies and operations for data analytics.
Candidate ID: 170, Job Title: data analyst - This candidate has a specific role as a data analyst, which indicates a strong focus on data analysis and problem-solving.
Candidate ID: 175, Job Title: data scientist - This candidate has a specific role as a data scientist, which indicates a high level of expertise in data analysis and machine learning.
Candidate ID: 176, Job Title: data analyst - This candidate has a specific role as a data analyst, which indicates a strong focus on data analysis and problem-solving.
Candidate ID: 177, Job Title: data engineer - This candidate has a specific role as a data engineer, which indicates a high level of expertise in data engineering and data
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 182, Job Title: experienced data analyst research coordinator healthcare data specialist - This candidate has a strong background in data analysis and has experience in healthcare data management.
Candidate ID: 187, Job Title: cybersecurity - This candidate has expertise in cybersecurity, which is a crucial skill in today's digital age.
Candidate ID: 184, Job Title: multi-competent generalist - This candidate has a diverse skill set and can adapt to various roles and challenges.
Candidate ID: 203, Job Title: m.s. data science graduate michigan state university - This candidate has a strong educational background in data science and is actively seeking full-time opportunities.
Candidate ID: 206, Job Title: aiml researcher data scientist aws certified - This candidate has expertise in machine learning and has demonstrated cost savings through data-driven techniques.
Candidate ID: 205, Job Title: actively seeking full-time opportunities in data science python sql r spark machine learning bi and cloud tools specialist m. s. student in information management uiuc - This candidate is actively seeking full-time roles and has a strong foundation in data science with expertise in Python, SQL, and ML.
Candidate ID: 213, Job Title: data scientist specializing in machine learning statistical modeling proven success with etl workflows reducing data cleaning time by 80 passionate about transforming data into actionable insights
Candidate ID: 220, Job Title: data scientist research scientist machine learning engineer artificial intelligence creating accurate and efficient machine learning solutions ai scientist ai engineer
Candidate ID: 221, Job Title: machine learningdata scienceai researchcomputer vision machine perceptionnlp llms gen ai prompt engineering machine learning deep learning nlp hugging face transformers llms langchain rag asr model development python sql tableau azure certified
Candidate ID: 223, Job Title: msis - big data aws certified automation etl data modeling machine learning python sql tableau skilled in data analysis and visualization
Candidate ID: 224, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization
Candidate ID: 225, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization
Candidate ID: 226, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization
Candidate ID: 227, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization
Candidate ID: 228, Job Title: data analyst python sql tableau aws certified skilled in data analysis and visualization
Candidate ID: 229, Job Title: data analyst python sql table
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 233, Job Title: data scientist data analyst ms in data science
Candidate ID: 243, Job Title: data scientist aiml practitioner aws azure certified passionate about data-driven solutions
Candidate ID: 254, Job Title: data analyst machine learning engineer transforming data into actionable insights with advanced analytics predictive modeling 5 years of experience in python sql tableau and ai solutions
Candidate ID: 264, Job Title: data scientist 4 years in data analysis visualization predictive modeling python sql power bi
Candidate ID: 284, Job Title: biomedical research scientist - This candidate is a biomedical research scientist, which is not directly related to data analysis. However, they may have experience in data analysis in their research.
Candidate ID: 289, Job Title: data scientist certified tensorflow developer - This candidate is a data scientist and certified in tensorflow, a popular machine learning framework. They have experience in data analysis and machine learning.
Candidate ID: 286, Job Title: machine learning engineer tata consultancy services limited generative ai expert in machine learning and data modeling data-driven decision making - This candidate is a machine learning engineer and an expert in generative AI and data modeling. They have experience in data analysis and machine learning.
Candidate ID: 295, Job Title: Senior Data Scientist - Data Scientist
Candidate ID: 297, Job Title: Data Analyst - Data Analyst
Candidate ID: 303, Job Title: Data Scientist Artificial Intelligence Financial Analyst - Data Scientist
Candidate ID: 304, Job Title: Data Analyst - Data Analyst
Candidate ID: 305, Job Title: Data Scientist - Data Scientist
Candidate ID: 306, Job Title: Data Analyst - Data Analyst
Candidate ID: 307, Job Title: Data Scientist - Data Scientist
Candidate ID: 308, Job Title: Data Analyst - Data Analyst
Candidate ID: 309, Job Title: Data Scientist - Data Scientist
Candidate ID: 310, Job Title: Data Analyst - Data Analyst
Candidate ID: 311, Job Title: Data Scientist - Data Scientist
Candidate ID: 312, Job Title: Data Analyst - Data Analyst
Candidate ID: 313, Job Title: Data Scientist - Data Scientist
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 304, Job Title: Data Scientist Leveraging Python Power BI SQL Machine Learning and Deep Learning to Drive Insights
Candidate ID: 314, Job Title: Data Scientist Data Analyst AI ML Engineer Data Engineer Passionate About Turning Data into Intelligent Solutions
Candidate ID: 325, Job Title: Data Analyst Guru - This candidate has a master's degree in data science and is actively seeking full-time opportunities. They have experience in data analysis and machine learning.
Candidate ID: 328, Job Title: Software Engineer Mathematics - This candidate has a background in software engineering and mathematics. They have experience in data science and machine learning.
Candidate ID: 330, Job Title: Healthcare Data Scientist - This candidate has a background in healthcare and data science. They have experience in data analysis and machine learning.
Candidate ID: 335, Job Title: It Specialist Data Science Business Intelligence Data-Driven Decision Making
Candidate ID: 337, Job Title: MS Business Analytics University of Tampa 25 Graduate Research Assistant President U.T.
Candidate ID: 334, Job Title: Data Science U.C. Berkeley Undergraduate Researcher Innovative Genomics Institute
Candidate ID: 344, Job Title: data analyst at winfertility - This candidate has a dedicated role as a data analyst, indicating a strong focus and expertise in the field.
Candidate ID: 350, Job Title: data engineer at syzygy plasmonics - This candidate has experience in data engineering and actively seeks roles as a data analyst, demonstrating a proactive approach to pursuing opportunities.
Candidate ID: 355, Job Title: Data Analyst at a Leading Financial Institution
Candidate ID: 356, Job Title: Data Analyst at a Leading Healthcare Provider
Candidate ID: 357, Job Title: Data Analyst at a Leading Retailer
Candidate ID: 358, Job Title: Data Analyst at a Leading Technology Company
Candidate ID: 359, Job Title: Data Analyst at a Leading Insurance Provider
Candidate ID: 360, Job Title: Data Analyst at a Leading Automotive Manufacturer
Candidate ID: 361, Job Title: Data Analyst at a Leading Financial Institution
Candidate ID: 362, Job Title: Data Analyst at a Leading Healthcare Provider
Candidate ID: 363, Job Title: Data Analyst
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 354, Job Title: experienced data analyst
Candidate ID: 355, Job Title: student at the university of memphis
Candidate ID: 362, Job Title: actively looking for full-time opportunities mlds roles pnnl georgia tech
Candidate ID: 364, Job Title: m.s. in data analytics python django developer specializing in machine learning models data visualization and database management
Candidate ID: 374, Job Title: business professional mba data scientist data analyst transforming skills with triple ten coding bootcamp
Candidate ID: 393, Job Title: AI Machine Learning Engineer Full Stack Developer Data Scientist SQL Power BI Expert Cloud Automation Enthusiast
Candidate ID: 404, Job Title: data science graduate student at university at buffalo seeking for full time opportunities in data science data analyst business analyst sde roles
Candidate ID: 420, Job Title: Computer Science Graduate Aspiring Software Developer Passionate About Back-End Programming and AI Technologies
Candidate ID: 421, Job Title: Master of Science in Data Science
Candidate ID: 416, Job Title: Data Analyst Business Intelligence Data Quality Assurance SQL Project Management Supply Chain Management
Candidate ID: 422, Job Title: Data Analyst
Candidate ID: 423, Job Title: Data Analyst
Candidate ID: 424, Job Title: Data Analyst
Candidate ID: 425, Job Title: Data Analyst
Candidate ID: 426, Job Title: Data Analyst
Candidate ID: 427, Job Title: Data Analyst
Candidate ID: 428, Job Title: Data Analyst
Candidate ID: 429, Job Title: Data Analyst
Candidate ID: 430, Job Title: Data Analyst
Candidate ID: 431, Job Title: Data Analyst
Candidate ID: 432, Job Title: Data Analyst
Candidate ID: 433, Job Title: Data Analyst
Candidate ID
From the following candidates for 'data analyst', pick ONLY the top 2 most relevant. Output only ID and Title.

Candidates:
Candidate ID: 424, Job Title: data science tech enthusiast python machine learning r programming sci-kit learn and other python libraries.
Candidate ID: 471, Job Title: Senior Data Analyst - Turning Raw Data into Meaningful Stories with Python R SQL
Candidate ID: 469, Job Title: Data Engineer - SQL Python Power BI ETL Cloud
Candidate ID: 472, Job Title: Associate Data Analyst - Python SQL Tableau
Candidate ID: 488, Job Title: data scientist and systems operator delivering excellence with precision
Candidate ID: 499, Job Title: -data scientist analytics transforming business challenges into scalable ml solutions
Candidate ID: 497, Job Title: graduate student interdisciplinary data science data analysis machine learning sql python r
Candidate ID: 495, Job Title: data analyst at cdf and data aide at harlem children zone. data science data analyst python sql
Candidate ID: 504, Job Title: data scientist uae golden visa holder - As a data scientist, this candidate possesses advanced skills in data analysis, machine learning, and data science. Their expertise in Python, SQL, and Tableau makes them highly skilled in data-driven decision-making.
Candidate ID: 507, Job Title: data analyst skilled in python sql power bi tableau and machine learning - This candidate excels in data analysis and possesses expertise in Python, SQL, and Tableau. Their skills in machine learning enable them to develop advanced insights for data-driven decision-making.

# RAG (Retrieval-Augmented Generation)

In this section, I implemented a RAG pipeline to extend the ranking system's capabilities beyond the original candidate dataset.

By leveraging a vector-based retrieval mechanism (FAISS), the LLM can dynamically access and evaluate candidates from the extended dataset that were not part of the original corpus, ensuring a more comprehensive ranking process.

In [ ]:
%pip install faiss-gpu-cu12

Collecting faiss-gpu-cu12
  Downloading faiss_gpu_cu12-1.14.1.post1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=2 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (26.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12>=12.1.105 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (12.8.90)
Requirement already satisfied: nvidia-cublas-cu12>=12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu-cu12) (12.8.4.1)
Downloading faiss_gpu_cu12-1.14.1.post1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (48.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 MB 23.4 MB/s eta 0:00:00
Installing collected packages: faiss-gpu-cu12
Successfully installed faiss-gpu-cu12-1.14.1.post1

In [ ]:
import faiss
import torch
from transformers import AutoTokenizer, AutoModel
from transformers import AutoModelForSeq2SeqLM

In [ ]:
# Model to use in retriever
retriever_tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
retriever_model = AutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
def generate_embedding(docs, model, tokenizer):
    # Tokenize each text and convert to PyTorch tensors
    inputs = tokenizer(docs, padding=True, truncation=True, return_tensors="pt", max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)

    # Embedding defined as mean pooling of all tokens
    attention_mask = inputs["attention_mask"]
    embeddings = outputs.last_hidden_state

    expanded_mask = attention_mask.unsqueeze(-1).expand(embeddings.shape).float()
    sum_embeddings = torch.sum(embeddings * expanded_mask, axis=1)
    sum_mask = torch.clamp(expanded_mask.sum(axis=1), min=1e-9)
    mean_embeddings = sum_embeddings / sum_mask

    # Convert to numpy array
    return mean_embeddings.cpu().numpy()

def retrieve_documents(query, index, documents, k=3):
    # Generate embedding for the query
    query_embedding = generate_embedding(query, retriever_model, retriever_tokenizer)   # 1xD matrix
    # Search the index for similar documents
    distances, indices = index.search(query_embedding, k)  # 1xk matrices
    # Return the retrieved documents and their distances
    retrieved_docs = [(documents[idx], float(distances[0][i])) for i, idx in enumerate(indices[0])]
    return retrieved_docs

def rag_pipeline(query, documents, retriever_k=3, max_length=150):
    retrieved_docs = retrieve_documents(query, index, documents, k=retriever_k)
    docs = [doc for doc, distance in retrieved_docs]
    response = generate_response(query, docs, max_length=max_length)
    return response, retrieved_docs

## GLM

In [ ]:
import ollama

def generate_response(query, retrieved_docs, max_length=150):
    # Combine the retrieved documents into a single text block for the prompt
    if not retrieved_docs:
        return "No relevant candidates were found to rank."

    candidates_text = "\n".join([f"- {doc}" for doc in retrieved_docs])

    prompt = f"""As an expert recruiter, rank the following candidates based on the search term: '{query}'.

Candidates retrieved from database:
{candidates_text}

For each candidate, provide a Similarity Score (0.0 to 1.0) and a brief justification.
Format your response as a clear Markdown list."""

    # Invoke the GLM model via Ollama
    response = ollama.generate(model='glm-4.7-flash', prompt=prompt)

    return response['response']

In [ ]:
import pandas as pd

# Extract the job titles from the extended dataset to serve as the document corpus for retrieval
# We use the 'title' column from fine_tuning_df which contains the rich descriptions
documents = extended_df['title'].astype(str).tolist()

print(f"Converted {len(documents)} entries from the extended dataset into document format.")
print("Sample document:")
print(documents[0])

Converted 1285 entries from the extended dataset into document format.
Sample document:
innovative and driven professional seeking a role in data analyticsdata science in the information technology industry.

In [ ]:
# Generate embeddings for all documents, then create FAISS index for efficient similarity search
document_embeddings = generate_embedding(documents, retriever_model, retriever_tokenizer)
dimension = document_embeddings.shape[1]   # Dimension of the embeddings
index = faiss.IndexFlatL2(dimension)       # Using L2 (Euclidean) distance
index.add(document_embeddings)             # Add embeddings to the index
print(f"Created index with {index.ntotal} documents")

Created index with 1285 documents

In [ ]:
query = "Software Engineer"
response, retrieved_docs = rag_pipeline(query, documents, retriever_k=5)

print(f"Query: {query}")
print("\n--- Retrieved from FAISS index ---")
for i, (doc, distance) in enumerate(retrieved_docs):
    print(f"{i+1}. (L2 Distance: {distance:.4f}) {doc}")

print("\n--- GLM-4 Expert Ranking ---")
from IPython.display import Markdown, display
display(Markdown(response))

Query: Software Engineer

--- Retrieved from FAISS index ---
1. (L2 Distance: 0.0000) Software Engineer
2. (L2 Distance: 0.0000) software engineer
3. (L2 Distance: 0.0000) software engineer
4. (L2 Distance: 0.0000) software engineer
5. (L2 Distance: 0.0000) software engineer

--- GLM-4 Expert Ranking ---

Here are the ranked candidates based on the search term 'Software Engineer':

1.  **Software Engineer**
    *   **Similarity Score:** 1.0
    *   **Justification:** Exact character-for-character match with the search term.

2.  **software engineer**
    *   **Similarity Score:** 1.0
    *   **Justification:** Perfect case-insensitive match; semantically identical to the search term.

3.  **software engineer**
    *   **Similarity Score:** 1.0
    *   **Justification:** Perfect case-insensitive match; semantically identical to the search term.

4.  **software engineer**
    *   **Similarity Score:** 1.0
    *   **Justification:** Perfect case-insensitive match; semantically identical to the search term.

5.  **software engineer**
    *   **Similarity Score:** 1.0
    *   **Justification:** Perfect case-insensitive match; semantically identical to the search term.

In [ ]:
query = "Data Science professional with NLP experience"
response, retrieved_docs = rag_pipeline(query, documents, retriever_k=5)

print(f"Query: {query}")
print("\n--- Retrieved from FAISS index ---")
for i, (doc, distance) in enumerate(retrieved_docs):
    print(f"{i+1}. (L2 Distance: {distance:.4f}) {doc}")

print("\n--- GLM-4 Expert Ranking ---")
from IPython.display import Markdown, display
display(Markdown(response))

Query: Data Science professional with NLP experience

--- Retrieved from FAISS index ---
1. (L2 Distance: 20.6183) aiml enthusiast recent b.tech graduate deep learning nlp data science
2. (L2 Distance: 21.6152) actively seeking full time data analystdata scientist roles python r sql powerbi machine learning nlp pl300 certified
3. (L2 Distance: 22.0310) data science machine learning artificial intelligence nlp
4. (L2 Distance: 22.1520) data engineer scientist phd in computational engineering skilled in python pytorch aws databricks expertise in machine learning nlp scalable data solutions
5. (L2 Distance: 22.4260) open to data-driven opportunities 4 years experience data engineering data analyst data science masters student at university of new haven python sql unix power bi aws

--- GLM-4 Expert Ranking ---

Here is the ranking of the candidates based on the search term **'Data Science professional with NLP experience'**:

1.  **Candidate 4**
    *   **Similarity Score:** 0.95
    *   **Justification:** This candidate explicitly states "expertise in machine learning nlp" and holds a PhD in Computational Engineering, indicating high-level academic and professional capability in the specific domain.

2.  **Candidate 2**
    *   **Similarity Score:** 0.90
    *   **Justification:** Directly targets "data scientist roles" and lists "nlp" alongside a strong stack of tools (Python, SQL) and a specific certification (PL300), indicating a ready-to-hire professional with the required skill.

3.  **Candidate 1**
    *   **Similarity Score:** 0.85
    *   **Justification:** Clearly identifies as an "aiml enthusiast" and lists "nlp" and "deep learning" as key skills, though the "recent b.tech graduate" status suggests less seniority than the top-ranked candidates.

4.  **Candidate 3**
    *   **Similarity Score:** 0.70
    *   **Justification:** Contains the core keywords ("data science", "nlp") but lacks context regarding experience level or specific technical depth.

5.  **Candidate 5**
    *   **Similarity Score:** 0.15
    *   **Justification:** The candidate possesses strong Data Science experience (4 years, Masters student) but the profile **does not contain the keyword 'NLP'**. Therefore, they are disqualified for this specific search query.

In [ ]:
query = "Machine Learning Engineer specializing in high-energy physics and particle data analysis"
response, retrieved_docs = rag_pipeline(query, documents, retriever_k=5)

print(f"Query: {query}")
print("\n--- Retrieved from FAISS index ---")
for i, (doc, distance) in enumerate(retrieved_docs):
    print(f"{i+1}. (L2 Distance: {distance:.4f}) {doc}")

print("\n--- GLM-4 Expert Ranking ---")
from IPython.display import Markdown, display
display(Markdown(response))

Query: Machine Learning Engineer specializing in high-energy physics and particle data analysis

--- Retrieved from FAISS index ---
1. (L2 Distance: 19.2037) Machine Learning Engineer Google Certified Associate Cloud Engineer M-Tech Silver Medalist in Artificial Intelligence Data Science.
2. (L2 Distance: 19.9358) physics ms analytical problem solver proficient in data analysis and visualization and machine learning
3. (L2 Distance: 19.9387) Machine Learning Engineer at Cedar Gate Technologies Ex- Darazian Daraz Nepal Alibaba Group
4. (L2 Distance: 19.9690) machine learning engineer specializing in ai pipelines mlops and scalable solutions automating workflows to drive impact and learn continuously.
5. (L2 Distance: 20.0190) data scientist ai machine learning engineer graduate assistant statistician drug discovery scientist

--- GLM-4 Expert Ranking ---

Here are the ranked candidates based on their similarity to the search term **"Machine Learning Engineer specializing in high-energy physics and particle data analysis"**.

*   **Candidate:** physics ms analytical problem solver proficient in data analysis and visualization and machine learning
    *   **Similarity Score:** 0.65
    *   **Justification:** This candidate is the top match because it explicitly contains the specific domain keyword "physics," which is the primary focus of the search query. While the title is less specific, the background is the closest to high-energy physics.

*   **Candidate:** machine learning engineer specializing in ai pipelines mlops and scalable solutions automating workflows to drive impact and learn continuously.
    *   **Similarity Score:** 0.55
    *   **Justification:** This candidate holds the exact job title "Machine Learning Engineer" and describes technical skills (MLOps, scalable solutions) that are critical for processing the large datasets typically found in high-energy physics, even though the specific domain keyword is missing.

*   **Candidate:** Machine Learning Engineer Google Certified Associate Cloud Engineer M-Tech Silver Medalist in Artificial Intelligence Data Science.
    *   **Similarity Score:** 0.40
    *   **Justification:** Matches the job title well and demonstrates academic rigor with a silver medalist credential, but lacks any mention of physics or particle data analysis.

*   **Candidate:** Machine Learning Engineer at Cedar Gate Technologies Ex- Darazian Daraz Nepal Alibaba Group
    *   **Similarity Score:** 0.40
    *   **Justification:** Matches the job title well and has relevant industry experience, but the background is in e-commerce rather than high-energy physics.

*   **Candidate:** data scientist ai machine learning engineer graduate assistant statistician drug discovery scientist
    *   **Similarity Score:** 0.20
    *   **Justification:** This candidate focuses on "drug discovery," which is a biological domain, not the physical science of high-energy physics, making them the least relevant match.

## Deepseek

In [ ]:
# 1. Install dependencies, Ollama binary, and python library
!sudo apt-get update && sudo apt-get install -y zstd pciutils
!curl -fsSL https://ollama.com/install.sh | sh
!pip install -q ollama

import ollama
import threading
import subprocess
import time
import requests
from IPython.display import Markdown, display

# 2. Start Ollama service in the background
def run_ollama_serve():
    subprocess.Popen(["ollama", "serve"])

# Check if service is already running, if not, start it
try:
    requests.get('http://localhost:11434/api/tags')
    print("Ollama service already running.")
except requests.exceptions.ConnectionError:
    print("Starting Ollama service...")
    serve_thread = threading.Thread(target=run_ollama_serve)
    serve_thread.daemon = True
    serve_thread.start()

# Wait for the service to be responsive
print("Waiting for Ollama service to respond...")
for i in range(15):
    try:
        res = requests.get('http://localhost:11434/api/tags')
        if res.status_code == 200:
            print("Ollama service is up and running!")
            break
    except requests.exceptions.ConnectionError:
        time.sleep(2)
else:
    print("Error: Ollama service failed to start.")

# 3. Pull the DeepSeek model
# Using a standard deepseek-v2 tag
print("Pulling DeepSeek-V2 model...")
!ollama pull deepseek-v2

In [ ]:

# 4. Define the ranking function
def generate_response_deepseek(query, retrieved_docs, max_length=500):
    if not retrieved_docs:
        return "No relevant candidates were found to rank."
    candidates_text = "\n".join([f"- {doc}" for doc in retrieved_docs])
    prompt = f"""As an expert recruiter specializing in quantitative finance, rank the following candidates based on the search term: '{query}'.\n\nCandidates retrieved from database:\n{candidates_text}\n\nFor each candidate, provide a Similarity Score (0.0 to 1.0) and a brief justification focusing on their suitability for a Quant Developer role.\nFormat your response as a clear Markdown list."""
    response = ollama.generate(model='deepseek-v2', prompt=prompt)
    return response['response']

# 5. Run the RAG pipeline
query_quant = "quant developers"
num_candidates = 5 # <--- Specify the number of candidates to showcase here

import __main__
__main__.generate_response = generate_response_deepseek

# Updated call to use the num_candidates variable
response_text, retrieved_docs = rag_pipeline(query_quant, documents, retriever_k=num_candidates)

print(f"Query: {query_quant}")
print(f"\n--- Retrieved top {num_candidates} from FAISS index ---")
for i, (doc, distance) in enumerate(retrieved_docs):
    print(f"{i+1}. (L2 Distance: {distance:.4f}) {doc}")

print("\n--- DeepSeek Expert Ranking ---")
display(Markdown(response_text))

Query: quant developers

--- Retrieved top 5 from FAISS index ---
1. (L2 Distance: 32.5075) CAD Design IOT Developer Fullstack AI Developer Resercher Analyst Animator Building Innovative Products for the Future
2. (L2 Distance: 33.2727) full stack developer m.s. computer science at georgia institute of technology b.s. computer science at university of akron
3. (L2 Distance: 33.5477) software developer
4. (L2 Distance: 33.5477) software developer
5. (L2 Distance: 34.0649) full-stack developer mechanical engineer encoding the future

--- DeepSeek Expert Ranking ---

 | Candidate                     | Similarity Score | Justification                                                                                                       |
|---------------------------------|------------------|-----------------------------------------------------------------------------------------------------------------------|
| CAD Design IoT Developer      | 0.85             | The candidate's focus on design and development of Internet of Things (IoT) solutions, which can include quantitative finance applications such as market monitoring or algorithmic trading systems, is highly relevant to the role of a Quant Developer. |
| Full Stack Developer MS-CS at Georgia Tech & B.S. CS at University of Akron  | 0.8             | The candidate's advanced education and experience in computer science from prestigious institutions like Georgia Institute of Technology positions them well for technical roles requiring deep understanding of both front-end and back-end development processes, which are essential skills for a Quant Developer. |
| Software Developer            | 0.75             | This is a broad term that can encompass various roles within the technology sector including those focused on finance software development. The candidate could potentially be suitable if their experience aligns with developing financial applications or quantitative tools. |
| Full-stack developer (Mechanical Engineer) | 0.65            | Although not directly in quantitative finance, a full-stack developer who has worked on complex systems integration and process automation would have skills that are highly transferable to the development of advanced analytical software used in financial roles like Quant Developer. |
| Software Developer           | 0.7              | Similar reasoning as above but with slightly less specific justification; this candidate could be suitable if their skill set matches what is needed for a quant developer role, particularly within large tech firms where there might be multiple areas of application for technical skills in finance. |

## Gemini

### Note on API Quotas

When I attempted to execute the pipeline using **Gemini 2.0 Flash**, I encountered a `429 Quota Exceeded` error.

I learned that I can monitor real-time API usage and manage project quotas throught the [Google AI Studio Usage Monitor](https://ai.dev/rate-limit).

In [ ]:
import google.generativeai as genai
from google.colab import userdata
from IPython.display import Markdown, display
import __main__

# 1. Setup Gemini API using Colab Secrets
try:
    # Configure the SDK with your API key
    genai.configure(api_key=userdata.get('GEMINI_API_KEY'))

    # Use Gemini 2.0 Flash
    MODEL_ID = 'gemini-2.0-flash'
    client = genai.GenerativeModel(MODEL_ID)
except Exception as e:
    print("Error: Please add your API key to Colab Secrets as 'GEMINI_API_KEY'.")

# 2. Define the Gemini Generator Function
def generate_response_gemini(query, retrieved_docs, max_length=1000):
    if not retrieved_docs:
        return "No relevant candidates were found to rank."

    candidates_text = "\n".join([f"- {doc}" for doc in retrieved_docs])

    prompt = f"""As an expert recruiter specializing in quantitative finance and technology,
rank the following candidates based on the search term: '{query}'.

Candidates retrieved from database:
{candidates_text}

For each candidate, provide:
1. A Similarity Score (0.0 to 1.0)
2. A brief, professional justification for the score.

Format your response as a structured Markdown list or table."""

    # Generate content using the SDK
    response = client.generate_content(prompt)
    return response.text

# 3. Integrate into the RAG Pipeline
__main__.generate_response = generate_response_gemini

# 4. Execute Pipeline
query_tech = "quant developers with high-frequency trading experience"
num_candidates = 5

try:
    response_text, retrieved_docs = rag_pipeline(query_tech, documents, retriever_k=num_candidates)

    print(f"Query: {query_tech}")
    print(f"\n--- FAISS Retrieval: Top {num_candidates} Candidates ---")
    for i, (doc, distance) in enumerate(retrieved_docs):
        print(f"{i+1}. [Dist: {distance:.4f}] {doc}")

    print(f"\n--- {MODEL_ID} Expert Ranking ---")
    display(Markdown(response_text))
except Exception as e:
    print(f"Error: {e}")

WARNING:tornado.access:429 POST /v1beta/models/gemini-2.0-flash:generateContent?%24alt=json%3Benum-encoding%3Dint (::1) 595.46ms

Error: 429 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?%24alt=json%3Benum-encoding%3Dint: You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 0, model: gemini-2.0-flash
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_input_token_count, limit: 0, model: gemini-2.0-flash
Please retry in 49.462177175s.

# Gemini App

I developed a [Talent Match and Ranker app](https://ai.studio/apps/f6cb87d2-8383-449c-a658-3c16191f982e) that ranks candidates based on search terms. Powered by a LangGraph structure, the system intelligently detects and geographical details—automatically triggering a mapping tool to recalculate candidate scores based on location proximity.

# Conclusion


Throughout this project, I explored a spectrum of methodologies for candidate ranking, ranging from statistical approaches to state-of-the-art Large Language Models (LLMs).

1.  **TF-IDF Vectorization**: I began with TF-IDF, which demonstrated how word frequency and uniqueness within a corpus can be used to determine relevance. While effective for keyword matching, it lacked a deeper semantic understanding.
2.  **Word Embeddings**: Using word embeddings (Word2Vec, GloVe, FastText), I mathematically calculated semantic similarities by tokenizing the corpus and mapping each token to its corresponding vector space representation. This stage addressed the 'Out-of-Vocabulary' (OOV) limitation, identifying how unseen words could lead to errors.
3.  **Large Language Models (LLMs)**: Delegating the ranking task to LLMs (like Qwen and GLM) provided a significant improvement in performance and interpretability. The models provided high-quality reasoning for each ranking decision, moving the system closer to human-like evaluation. Using **Ollama** locally allowed for optimized inference.
4.  **Fine-Tuning**: To adapt the models to specific talent acquisition datasets, I utilized **QLoRA** for parameter-efficient fine-tuning. This process improved the model's ability to handle job titles outside the original training set, though it introduced considerations regarding model storage and deployment overhead.
5.  **Retrieval-Augmented Generation (RAG)**: I implemented a RAG pipeline leveraging **FAISS** to dynamically retrieve and inject relevant candidate profiles into the model's context during inference. This architecture provides a highly scalable solution, enabling the system to rank new, unseen data in real-time without the need for additional model training.
6.  **Gemini Integration & Agentic Workflows**: Finally, I explored the **Gemini API** to develop a dedicated **Talent Matcher App**. Despite free-tier rate limits, the app successfully showcased **agentic workflows** using **LangGraph**. The system intelligently detected geographical intent in search terms, automatically calling relevant tools to calculate location-based proximity.